// Crossbar: bridge_a_axi4_widthmix_4x4_xbar
// Generated by: CrossbarGenerator
// 
// Routes width-adapted signals from adapters to slaves.
// Selects correct width path based on address decode.

`timescale 1ns / 1ps

import bridge_a_axi4_widthmix_4x4_pkg::*;

module bridge_a_axi4_widthmix_4x4_xbar (
    input  logic aclk,
    input  logic aresetn,

    // cpu adapter outputs (multiple width paths)
    input  logic [NUM_SLAVES-1:0] cpu_slave_select_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] cpu_bridge_id_aw,
    input  logic [NUM_SLAVES-1:0] cpu_slave_select_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] cpu_bridge_id_ar,
    // 32b path
    input  axi4_aw_t     cpu_32b_aw,
    input  logic         cpu_32b_awvalid,
    output logic         cpu_32b_awready,
    input  axi4_w_32b_t  cpu_32b_w,
    input  logic         cpu_32b_wvalid,
    output logic         cpu_32b_wready,
    output axi4_b_t      cpu_32b_b,
    output logic         cpu_32b_bvalid,
    input  logic         cpu_32b_bready,
    input  axi4_ar_t     cpu_32b_ar,
    input  logic         cpu_32b_arvalid,
    output logic         cpu_32b_arready,
    output axi4_r_32b_t  cpu_32b_r,
    output logic         cpu_32b_rvalid,
    input  logic         cpu_32b_rready,
    // 64b path
    input  axi4_aw_t     cpu_64b_aw,
    input  logic         cpu_64b_awvalid,
    output logic         cpu_64b_awready,
    input  axi4_w_64b_t  cpu_64b_w,
    input  logic         cpu_64b_wvalid,
    output logic         cpu_64b_wready,
    output axi4_b_t      cpu_64b_b,
    output logic         cpu_64b_bvalid,
    input  logic         cpu_64b_bready,
    input  axi4_ar_t     cpu_64b_ar,
    input  logic         cpu_64b_arvalid,
    output logic         cpu_64b_arready,
    output axi4_r_64b_t  cpu_64b_r,
    output logic         cpu_64b_rvalid,
    input  logic         cpu_64b_rready,
    // 128b path
    input  axi4_aw_t     cpu_128b_aw,
    input  logic         cpu_128b_awvalid,
    output logic         cpu_128b_awready,
    input  axi4_w_128b_t  cpu_128b_w,
    input  logic         cpu_128b_wvalid,
    output logic         cpu_128b_wready,
    output axi4_b_t      cpu_128b_b,
    output logic         cpu_128b_bvalid,
    input  logic         cpu_128b_bready,
    input  axi4_ar_t     cpu_128b_ar,
    input  logic         cpu_128b_arvalid,
    output logic         cpu_128b_arready,
    output axi4_r_128b_t  cpu_128b_r,
    output logic         cpu_128b_rvalid,
    input  logic         cpu_128b_rready,
    // 256b path
    input  axi4_aw_t     cpu_256b_aw,
    input  logic         cpu_256b_awvalid,
    output logic         cpu_256b_awready,
    input  axi4_w_256b_t  cpu_256b_w,
    input  logic         cpu_256b_wvalid,
    output logic         cpu_256b_wready,
    output axi4_b_t      cpu_256b_b,
    output logic         cpu_256b_bvalid,
    input  logic         cpu_256b_bready,
    input  axi4_ar_t     cpu_256b_ar,
    input  logic         cpu_256b_arvalid,
    output logic         cpu_256b_arready,
    output axi4_r_256b_t  cpu_256b_r,
    output logic         cpu_256b_rvalid,
    input  logic         cpu_256b_rready,

    // dma adapter outputs (multiple width paths)
    input  logic [NUM_SLAVES-1:0] dma_slave_select_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] dma_bridge_id_aw,
    input  logic [NUM_SLAVES-1:0] dma_slave_select_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] dma_bridge_id_ar,
    // 32b path
    input  axi4_aw_t     dma_32b_aw,
    input  logic         dma_32b_awvalid,
    output logic         dma_32b_awready,
    input  axi4_w_32b_t  dma_32b_w,
    input  logic         dma_32b_wvalid,
    output logic         dma_32b_wready,
    output axi4_b_t      dma_32b_b,
    output logic         dma_32b_bvalid,
    input  logic         dma_32b_bready,
    input  axi4_ar_t     dma_32b_ar,
    input  logic         dma_32b_arvalid,
    output logic         dma_32b_arready,
    output axi4_r_32b_t  dma_32b_r,
    output logic         dma_32b_rvalid,
    input  logic         dma_32b_rready,
    // 64b path
    input  axi4_aw_t     dma_64b_aw,
    input  logic         dma_64b_awvalid,
    output logic         dma_64b_awready,
    input  axi4_w_64b_t  dma_64b_w,
    input  logic         dma_64b_wvalid,
    output logic         dma_64b_wready,
    output axi4_b_t      dma_64b_b,
    output logic         dma_64b_bvalid,
    input  logic         dma_64b_bready,
    input  axi4_ar_t     dma_64b_ar,
    input  logic         dma_64b_arvalid,
    output logic         dma_64b_arready,
    output axi4_r_64b_t  dma_64b_r,
    output logic         dma_64b_rvalid,
    input  logic         dma_64b_rready,
    // 128b path
    input  axi4_aw_t     dma_128b_aw,
    input  logic         dma_128b_awvalid,
    output logic         dma_128b_awready,
    input  axi4_w_128b_t  dma_128b_w,
    input  logic         dma_128b_wvalid,
    output logic         dma_128b_wready,
    output axi4_b_t      dma_128b_b,
    output logic         dma_128b_bvalid,
    input  logic         dma_128b_bready,
    input  axi4_ar_t     dma_128b_ar,
    input  logic         dma_128b_arvalid,
    output logic         dma_128b_arready,
    output axi4_r_128b_t  dma_128b_r,
    output logic         dma_128b_rvalid,
    input  logic         dma_128b_rready,
    // 256b path
    input  axi4_aw_t     dma_256b_aw,
    input  logic         dma_256b_awvalid,
    output logic         dma_256b_awready,
    input  axi4_w_256b_t  dma_256b_w,
    input  logic         dma_256b_wvalid,
    output logic         dma_256b_wready,
    output axi4_b_t      dma_256b_b,
    output logic         dma_256b_bvalid,
    input  logic         dma_256b_bready,
    input  axi4_ar_t     dma_256b_ar,
    input  logic         dma_256b_arvalid,
    output logic         dma_256b_arready,
    output axi4_r_256b_t  dma_256b_r,
    output logic         dma_256b_rvalid,
    input  logic         dma_256b_rready,

    // gpu adapter outputs (multiple width paths)
    input  logic [NUM_SLAVES-1:0] gpu_slave_select_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] gpu_bridge_id_aw,
    input  logic [NUM_SLAVES-1:0] gpu_slave_select_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] gpu_bridge_id_ar,
    // 32b path
    input  axi4_aw_t     gpu_32b_aw,
    input  logic         gpu_32b_awvalid,
    output logic         gpu_32b_awready,
    input  axi4_w_32b_t  gpu_32b_w,
    input  logic         gpu_32b_wvalid,
    output logic         gpu_32b_wready,
    output axi4_b_t      gpu_32b_b,
    output logic         gpu_32b_bvalid,
    input  logic         gpu_32b_bready,
    input  axi4_ar_t     gpu_32b_ar,
    input  logic         gpu_32b_arvalid,
    output logic         gpu_32b_arready,
    output axi4_r_32b_t  gpu_32b_r,
    output logic         gpu_32b_rvalid,
    input  logic         gpu_32b_rready,
    // 128b path
    input  axi4_aw_t     gpu_128b_aw,
    input  logic         gpu_128b_awvalid,
    output logic         gpu_128b_awready,
    input  axi4_w_128b_t  gpu_128b_w,
    input  logic         gpu_128b_wvalid,
    output logic         gpu_128b_wready,
    output axi4_b_t      gpu_128b_b,
    output logic         gpu_128b_bvalid,
    input  logic         gpu_128b_bready,
    input  axi4_ar_t     gpu_128b_ar,
    input  logic         gpu_128b_arvalid,
    output logic         gpu_128b_arready,
    output axi4_r_128b_t  gpu_128b_r,
    output logic         gpu_128b_rvalid,
    input  logic         gpu_128b_rready,
    // 256b path
    input  axi4_aw_t     gpu_256b_aw,
    input  logic         gpu_256b_awvalid,
    output logic         gpu_256b_awready,
    input  axi4_w_256b_t  gpu_256b_w,
    input  logic         gpu_256b_wvalid,
    output logic         gpu_256b_wready,
    output axi4_b_t      gpu_256b_b,
    output logic         gpu_256b_bvalid,
    input  logic         gpu_256b_bready,
    input  axi4_ar_t     gpu_256b_ar,
    input  logic         gpu_256b_arvalid,
    output logic         gpu_256b_arready,
    output axi4_r_256b_t  gpu_256b_r,
    output logic         gpu_256b_rvalid,
    input  logic         gpu_256b_rready,

    // vpu adapter outputs (multiple width paths)
    input  logic [NUM_SLAVES-1:0] vpu_slave_select_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] vpu_bridge_id_aw,
    input  logic [NUM_SLAVES-1:0] vpu_slave_select_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] vpu_bridge_id_ar,
    // 128b path
    input  axi4_aw_t     vpu_128b_aw,
    input  logic         vpu_128b_awvalid,
    output logic         vpu_128b_awready,
    input  axi4_w_128b_t  vpu_128b_w,
    input  logic         vpu_128b_wvalid,
    output logic         vpu_128b_wready,
    output axi4_b_t      vpu_128b_b,
    output logic         vpu_128b_bvalid,
    input  logic         vpu_128b_bready,
    input  axi4_ar_t     vpu_128b_ar,
    input  logic         vpu_128b_arvalid,
    output logic         vpu_128b_arready,
    output axi4_r_128b_t  vpu_128b_r,
    output logic         vpu_128b_rvalid,
    input  logic         vpu_128b_rready,
    // 256b path
    input  axi4_aw_t     vpu_256b_aw,
    input  logic         vpu_256b_awvalid,
    output logic         vpu_256b_awready,
    input  axi4_w_256b_t  vpu_256b_w,
    input  logic         vpu_256b_wvalid,
    output logic         vpu_256b_wready,
    output axi4_b_t      vpu_256b_b,
    output logic         vpu_256b_bvalid,
    input  logic         vpu_256b_bready,
    input  axi4_ar_t     vpu_256b_ar,
    input  logic         vpu_256b_arvalid,
    output logic         vpu_256b_arready,
    output axi4_r_256b_t  vpu_256b_r,
    output logic         vpu_256b_rvalid,
    input  logic         vpu_256b_rready,

    // Slave 0: ddr0
    output logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_bridge_id_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_bid_bridge_id,
    input  logic                       ddr0_axi_bid_valid,

    output logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_bridge_id_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_rid_bridge_id,
    input  logic                       ddr0_axi_rid_valid,

    output  logic [3:0]  ddr0_axi_awid,
    output  logic [31:0]  ddr0_axi_awaddr,
    output  logic [7:0]  ddr0_axi_awlen,
    output  logic [2:0]  ddr0_axi_awsize,
    output  logic [1:0]  ddr0_axi_awburst,
    output  logic         ddr0_axi_awlock,
    output  logic [3:0]  ddr0_axi_awcache,
    output  logic [2:0]  ddr0_axi_awprot,
    output  logic [3:0]  ddr0_axi_awqos,
    output  logic [3:0]  ddr0_axi_awregion,
    output  logic         ddr0_axi_awuser,
    output  logic         ddr0_axi_awvalid,
    input  logic         ddr0_axi_awready,

    output  logic [255:0]  ddr0_axi_wdata,
    output  logic [31:0]  ddr0_axi_wstrb,
    output  logic         ddr0_axi_wlast,
    output  logic         ddr0_axi_wuser,
    output  logic         ddr0_axi_wvalid,
    input  logic         ddr0_axi_wready,

    input  logic [3:0]  ddr0_axi_bid,
    input  logic [1:0]  ddr0_axi_bresp,
    input  logic         ddr0_axi_buser,
    input  logic         ddr0_axi_bvalid,
    output  logic         ddr0_axi_bready,

    output  logic [3:0]  ddr0_axi_arid,
    output  logic [31:0]  ddr0_axi_araddr,
    output  logic [7:0]  ddr0_axi_arlen,
    output  logic [2:0]  ddr0_axi_arsize,
    output  logic [1:0]  ddr0_axi_arburst,
    output  logic         ddr0_axi_arlock,
    output  logic [3:0]  ddr0_axi_arcache,
    output  logic [2:0]  ddr0_axi_arprot,
    output  logic [3:0]  ddr0_axi_arqos,
    output  logic [3:0]  ddr0_axi_arregion,
    output  logic         ddr0_axi_aruser,
    output  logic         ddr0_axi_arvalid,
    input  logic         ddr0_axi_arready,

    input  logic [3:0]  ddr0_axi_rid,
    input  logic [255:0]  ddr0_axi_rdata,
    input  logic [1:0]  ddr0_axi_rresp,
    input  logic         ddr0_axi_rlast,
    input  logic         ddr0_axi_ruser,
    input  logic         ddr0_axi_rvalid,
    output  logic         ddr0_axi_rready,

    // Slave 1: ddr1
    output logic [BRIDGE_ID_WIDTH-1:0] ddr1_axi_bridge_id_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] ddr1_axi_bid_bridge_id,
    input  logic                       ddr1_axi_bid_valid,

    output logic [BRIDGE_ID_WIDTH-1:0] ddr1_axi_bridge_id_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] ddr1_axi_rid_bridge_id,
    input  logic                       ddr1_axi_rid_valid,

    output  logic [3:0]  ddr1_axi_awid,
    output  logic [31:0]  ddr1_axi_awaddr,
    output  logic [7:0]  ddr1_axi_awlen,
    output  logic [2:0]  ddr1_axi_awsize,
    output  logic [1:0]  ddr1_axi_awburst,
    output  logic         ddr1_axi_awlock,
    output  logic [3:0]  ddr1_axi_awcache,
    output  logic [2:0]  ddr1_axi_awprot,
    output  logic [3:0]  ddr1_axi_awqos,
    output  logic [3:0]  ddr1_axi_awregion,
    output  logic         ddr1_axi_awuser,
    output  logic         ddr1_axi_awvalid,
    input  logic         ddr1_axi_awready,

    output  logic [127:0]  ddr1_axi_wdata,
    output  logic [15:0]  ddr1_axi_wstrb,
    output  logic         ddr1_axi_wlast,
    output  logic         ddr1_axi_wuser,
    output  logic         ddr1_axi_wvalid,
    input  logic         ddr1_axi_wready,

    input  logic [3:0]  ddr1_axi_bid,
    input  logic [1:0]  ddr1_axi_bresp,
    input  logic         ddr1_axi_buser,
    input  logic         ddr1_axi_bvalid,
    output  logic         ddr1_axi_bready,

    output  logic [3:0]  ddr1_axi_arid,
    output  logic [31:0]  ddr1_axi_araddr,
    output  logic [7:0]  ddr1_axi_arlen,
    output  logic [2:0]  ddr1_axi_arsize,
    output  logic [1:0]  ddr1_axi_arburst,
    output  logic         ddr1_axi_arlock,
    output  logic [3:0]  ddr1_axi_arcache,
    output  logic [2:0]  ddr1_axi_arprot,
    output  logic [3:0]  ddr1_axi_arqos,
    output  logic [3:0]  ddr1_axi_arregion,
    output  logic         ddr1_axi_aruser,
    output  logic         ddr1_axi_arvalid,
    input  logic         ddr1_axi_arready,

    input  logic [3:0]  ddr1_axi_rid,
    input  logic [127:0]  ddr1_axi_rdata,
    input  logic [1:0]  ddr1_axi_rresp,
    input  logic         ddr1_axi_rlast,
    input  logic         ddr1_axi_ruser,
    input  logic         ddr1_axi_rvalid,
    output  logic         ddr1_axi_rready,

    // Slave 2: sram
    output logic [BRIDGE_ID_WIDTH-1:0] sram_axi_bridge_id_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] sram_axi_bid_bridge_id,
    input  logic                       sram_axi_bid_valid,

    output logic [BRIDGE_ID_WIDTH-1:0] sram_axi_bridge_id_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] sram_axi_rid_bridge_id,
    input  logic                       sram_axi_rid_valid,

    output  logic [3:0]  sram_axi_awid,
    output  logic [31:0]  sram_axi_awaddr,
    output  logic [7:0]  sram_axi_awlen,
    output  logic [2:0]  sram_axi_awsize,
    output  logic [1:0]  sram_axi_awburst,
    output  logic         sram_axi_awlock,
    output  logic [3:0]  sram_axi_awcache,
    output  logic [2:0]  sram_axi_awprot,
    output  logic [3:0]  sram_axi_awqos,
    output  logic [3:0]  sram_axi_awregion,
    output  logic         sram_axi_awuser,
    output  logic         sram_axi_awvalid,
    input  logic         sram_axi_awready,

    output  logic [63:0]  sram_axi_wdata,
    output  logic [7:0]  sram_axi_wstrb,
    output  logic         sram_axi_wlast,
    output  logic         sram_axi_wuser,
    output  logic         sram_axi_wvalid,
    input  logic         sram_axi_wready,

    input  logic [3:0]  sram_axi_bid,
    input  logic [1:0]  sram_axi_bresp,
    input  logic         sram_axi_buser,
    input  logic         sram_axi_bvalid,
    output  logic         sram_axi_bready,

    output  logic [3:0]  sram_axi_arid,
    output  logic [31:0]  sram_axi_araddr,
    output  logic [7:0]  sram_axi_arlen,
    output  logic [2:0]  sram_axi_arsize,
    output  logic [1:0]  sram_axi_arburst,
    output  logic         sram_axi_arlock,
    output  logic [3:0]  sram_axi_arcache,
    output  logic [2:0]  sram_axi_arprot,
    output  logic [3:0]  sram_axi_arqos,
    output  logic [3:0]  sram_axi_arregion,
    output  logic         sram_axi_aruser,
    output  logic         sram_axi_arvalid,
    input  logic         sram_axi_arready,

    input  logic [3:0]  sram_axi_rid,
    input  logic [63:0]  sram_axi_rdata,
    input  logic [1:0]  sram_axi_rresp,
    input  logic         sram_axi_rlast,
    input  logic         sram_axi_ruser,
    input  logic         sram_axi_rvalid,
    output  logic         sram_axi_rready,

    // Slave 3: scratch
    output logic [BRIDGE_ID_WIDTH-1:0] scratch_axi_bridge_id_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] scratch_axi_bid_bridge_id,
    input  logic                       scratch_axi_bid_valid,

    output logic [BRIDGE_ID_WIDTH-1:0] scratch_axi_bridge_id_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] scratch_axi_rid_bridge_id,
    input  logic                       scratch_axi_rid_valid,

    output  logic [3:0]  scratch_axi_awid,
    output  logic [31:0]  scratch_axi_awaddr,
    output  logic [7:0]  scratch_axi_awlen,
    output  logic [2:0]  scratch_axi_awsize,
    output  logic [1:0]  scratch_axi_awburst,
    output  logic         scratch_axi_awlock,
    output  logic [3:0]  scratch_axi_awcache,
    output  logic [2:0]  scratch_axi_awprot,
    output  logic [3:0]  scratch_axi_awqos,
    output  logic [3:0]  scratch_axi_awregion,
    output  logic         scratch_axi_awuser,
    output  logic         scratch_axi_awvalid,
    input  logic         scratch_axi_awready,

    output  logic [31:0]  scratch_axi_wdata,
    output  logic [3:0]  scratch_axi_wstrb,
    output  logic         scratch_axi_wlast,
    output  logic         scratch_axi_wuser,
    output  logic         scratch_axi_wvalid,
    input  logic         scratch_axi_wready,

    input  logic [3:0]  scratch_axi_bid,
    input  logic [1:0]  scratch_axi_bresp,
    input  logic         scratch_axi_buser,
    input  logic         scratch_axi_bvalid,
    output  logic         scratch_axi_bready,

    output  logic [3:0]  scratch_axi_arid,
    output  logic [31:0]  scratch_axi_araddr,
    output  logic [7:0]  scratch_axi_arlen,
    output  logic [2:0]  scratch_axi_arsize,
    output  logic [1:0]  scratch_axi_arburst,
    output  logic         scratch_axi_arlock,
    output  logic [3:0]  scratch_axi_arcache,
    output  logic [2:0]  scratch_axi_arprot,
    output  logic [3:0]  scratch_axi_arqos,
    output  logic [3:0]  scratch_axi_arregion,
    output  logic         scratch_axi_aruser,
    output  logic         scratch_axi_arvalid,
    input  logic         scratch_axi_arready,

    input  logic [3:0]  scratch_axi_rid,
    input  logic [31:0]  scratch_axi_rdata,
    input  logic [1:0]  scratch_axi_rresp,
    input  logic         scratch_axi_rlast,
    input  logic         scratch_axi_ruser,
    input  logic         scratch_axi_rvalid,
    output  logic         scratch_axi_rready
);

    // ================================================================
    // Crossbar Routing
    // ================================================================
    localparam NUM_SLAVES = 4;

    // ================================================================
    // Slave 0: ddr0 (256b)
    // ================================================================
    // Multi-master (4 masters) → ddr0
    //   - cpu (rw)
    //   - dma (rw)
    //   - gpu (rw)
    //   - vpu (rw)

    wire cpu_256b_aw_to_ddr0 = (cpu_256b_aw.addr <= 32'h3fffffff);
    wire cpu_256b_ar_to_ddr0 = (cpu_256b_ar.addr <= 32'h3fffffff);
    wire dma_256b_aw_to_ddr0 = (dma_256b_aw.addr <= 32'h3fffffff);
    wire dma_256b_ar_to_ddr0 = (dma_256b_ar.addr <= 32'h3fffffff);
    wire gpu_256b_aw_to_ddr0 = (gpu_256b_aw.addr <= 32'h3fffffff);
    wire gpu_256b_ar_to_ddr0 = (gpu_256b_ar.addr <= 32'h3fffffff);
    wire vpu_256b_aw_to_ddr0 = (vpu_256b_aw.addr <= 32'h3fffffff);
    wire vpu_256b_ar_to_ddr0 = (vpu_256b_ar.addr <= 32'h3fffffff);

    // AW channel (OR-merged across writing masters)
    assign ddr0_axi_awid = ((cpu_256b_aw_to_ddr0 && cpu_256b_awvalid) ? cpu_256b_aw.id : '0) |
        ((dma_256b_aw_to_ddr0 && dma_256b_awvalid) ? dma_256b_aw.id : '0) |
        ((gpu_256b_aw_to_ddr0 && gpu_256b_awvalid) ? gpu_256b_aw.id : '0) |
        ((vpu_256b_aw_to_ddr0 && vpu_256b_awvalid) ? vpu_256b_aw.id : '0);
    assign ddr0_axi_awaddr = ((cpu_256b_aw_to_ddr0 && cpu_256b_awvalid) ? cpu_256b_aw.addr : '0) |
        ((dma_256b_aw_to_ddr0 && dma_256b_awvalid) ? dma_256b_aw.addr : '0) |
        ((gpu_256b_aw_to_ddr0 && gpu_256b_awvalid) ? gpu_256b_aw.addr : '0) |
        ((vpu_256b_aw_to_ddr0 && vpu_256b_awvalid) ? vpu_256b_aw.addr : '0);
    assign ddr0_axi_awlen = ((cpu_256b_aw_to_ddr0 && cpu_256b_awvalid) ? cpu_256b_aw.len : '0) |
        ((dma_256b_aw_to_ddr0 && dma_256b_awvalid) ? dma_256b_aw.len : '0) |
        ((gpu_256b_aw_to_ddr0 && gpu_256b_awvalid) ? gpu_256b_aw.len : '0) |
        ((vpu_256b_aw_to_ddr0 && vpu_256b_awvalid) ? vpu_256b_aw.len : '0);
    assign ddr0_axi_awsize = ((cpu_256b_aw_to_ddr0 && cpu_256b_awvalid) ? cpu_256b_aw.size : '0) |
        ((dma_256b_aw_to_ddr0 && dma_256b_awvalid) ? dma_256b_aw.size : '0) |
        ((gpu_256b_aw_to_ddr0 && gpu_256b_awvalid) ? gpu_256b_aw.size : '0) |
        ((vpu_256b_aw_to_ddr0 && vpu_256b_awvalid) ? vpu_256b_aw.size : '0);
    assign ddr0_axi_awburst = ((cpu_256b_aw_to_ddr0 && cpu_256b_awvalid) ? cpu_256b_aw.burst : '0) |
        ((dma_256b_aw_to_ddr0 && dma_256b_awvalid) ? dma_256b_aw.burst : '0) |
        ((gpu_256b_aw_to_ddr0 && gpu_256b_awvalid) ? gpu_256b_aw.burst : '0) |
        ((vpu_256b_aw_to_ddr0 && vpu_256b_awvalid) ? vpu_256b_aw.burst : '0);
    assign ddr0_axi_awlock = ((cpu_256b_aw_to_ddr0 && cpu_256b_awvalid) ? cpu_256b_aw.lock : '0) |
        ((dma_256b_aw_to_ddr0 && dma_256b_awvalid) ? dma_256b_aw.lock : '0) |
        ((gpu_256b_aw_to_ddr0 && gpu_256b_awvalid) ? gpu_256b_aw.lock : '0) |
        ((vpu_256b_aw_to_ddr0 && vpu_256b_awvalid) ? vpu_256b_aw.lock : '0);
    assign ddr0_axi_awcache = ((cpu_256b_aw_to_ddr0 && cpu_256b_awvalid) ? cpu_256b_aw.cache : '0) |
        ((dma_256b_aw_to_ddr0 && dma_256b_awvalid) ? dma_256b_aw.cache : '0) |
        ((gpu_256b_aw_to_ddr0 && gpu_256b_awvalid) ? gpu_256b_aw.cache : '0) |
        ((vpu_256b_aw_to_ddr0 && vpu_256b_awvalid) ? vpu_256b_aw.cache : '0);
    assign ddr0_axi_awprot = ((cpu_256b_aw_to_ddr0 && cpu_256b_awvalid) ? cpu_256b_aw.prot : '0) |
        ((dma_256b_aw_to_ddr0 && dma_256b_awvalid) ? dma_256b_aw.prot : '0) |
        ((gpu_256b_aw_to_ddr0 && gpu_256b_awvalid) ? gpu_256b_aw.prot : '0) |
        ((vpu_256b_aw_to_ddr0 && vpu_256b_awvalid) ? vpu_256b_aw.prot : '0);
    assign ddr0_axi_awvalid = ((cpu_256b_aw_to_ddr0 && cpu_256b_awvalid) ? cpu_256b_awvalid : '0) |
        ((dma_256b_aw_to_ddr0 && dma_256b_awvalid) ? dma_256b_awvalid : '0) |
        ((gpu_256b_aw_to_ddr0 && gpu_256b_awvalid) ? gpu_256b_awvalid : '0) |
        ((vpu_256b_aw_to_ddr0 && vpu_256b_awvalid) ? vpu_256b_awvalid : '0);

    // AW->W tracking FIFO: cpu -> ddr0
    logic cpu_256b_w_to_ddr0;
    logic [3:0] cpu_256b_aw_to_ddr0_w_wptr, cpu_256b_aw_to_ddr0_w_rptr;
    logic cpu_256b_aw_to_ddr0_w_mem [16];
    logic cpu_256b_aw_to_ddr0_w_push, cpu_256b_aw_to_ddr0_w_pop;
    assign cpu_256b_aw_to_ddr0_w_push = cpu_256b_awvalid && cpu_256b_awready && cpu_256b_aw_to_ddr0;
    assign cpu_256b_aw_to_ddr0_w_pop  = cpu_256b_wvalid && cpu_256b_wready && cpu_256b_w.last && cpu_256b_w_to_ddr0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            cpu_256b_aw_to_ddr0_w_wptr <= '0;
            cpu_256b_aw_to_ddr0_w_rptr <= '0;
        end else begin
            if (cpu_256b_aw_to_ddr0_w_push) begin
                cpu_256b_aw_to_ddr0_w_mem[cpu_256b_aw_to_ddr0_w_wptr] <= 1'b1;
                cpu_256b_aw_to_ddr0_w_wptr <= cpu_256b_aw_to_ddr0_w_wptr + 1'b1;
            end
            if (cpu_256b_aw_to_ddr0_w_pop) begin
                cpu_256b_aw_to_ddr0_w_rptr <= cpu_256b_aw_to_ddr0_w_rptr + 1'b1;
            end
        end
    end
    assign cpu_256b_w_to_ddr0 = (cpu_256b_aw_to_ddr0_w_wptr != cpu_256b_aw_to_ddr0_w_rptr) ? cpu_256b_aw_to_ddr0_w_mem[cpu_256b_aw_to_ddr0_w_rptr] : 1'b0;

    // AW->W tracking FIFO: dma -> ddr0
    logic dma_256b_w_to_ddr0;
    logic [3:0] dma_256b_aw_to_ddr0_w_wptr, dma_256b_aw_to_ddr0_w_rptr;
    logic dma_256b_aw_to_ddr0_w_mem [16];
    logic dma_256b_aw_to_ddr0_w_push, dma_256b_aw_to_ddr0_w_pop;
    assign dma_256b_aw_to_ddr0_w_push = dma_256b_awvalid && dma_256b_awready && dma_256b_aw_to_ddr0;
    assign dma_256b_aw_to_ddr0_w_pop  = dma_256b_wvalid && dma_256b_wready && dma_256b_w.last && dma_256b_w_to_ddr0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            dma_256b_aw_to_ddr0_w_wptr <= '0;
            dma_256b_aw_to_ddr0_w_rptr <= '0;
        end else begin
            if (dma_256b_aw_to_ddr0_w_push) begin
                dma_256b_aw_to_ddr0_w_mem[dma_256b_aw_to_ddr0_w_wptr] <= 1'b1;
                dma_256b_aw_to_ddr0_w_wptr <= dma_256b_aw_to_ddr0_w_wptr + 1'b1;
            end
            if (dma_256b_aw_to_ddr0_w_pop) begin
                dma_256b_aw_to_ddr0_w_rptr <= dma_256b_aw_to_ddr0_w_rptr + 1'b1;
            end
        end
    end
    assign dma_256b_w_to_ddr0 = (dma_256b_aw_to_ddr0_w_wptr != dma_256b_aw_to_ddr0_w_rptr) ? dma_256b_aw_to_ddr0_w_mem[dma_256b_aw_to_ddr0_w_rptr] : 1'b0;

    // AW->W tracking FIFO: gpu -> ddr0
    logic gpu_256b_w_to_ddr0;
    logic [3:0] gpu_256b_aw_to_ddr0_w_wptr, gpu_256b_aw_to_ddr0_w_rptr;
    logic gpu_256b_aw_to_ddr0_w_mem [16];
    logic gpu_256b_aw_to_ddr0_w_push, gpu_256b_aw_to_ddr0_w_pop;
    assign gpu_256b_aw_to_ddr0_w_push = gpu_256b_awvalid && gpu_256b_awready && gpu_256b_aw_to_ddr0;
    assign gpu_256b_aw_to_ddr0_w_pop  = gpu_256b_wvalid && gpu_256b_wready && gpu_256b_w.last && gpu_256b_w_to_ddr0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            gpu_256b_aw_to_ddr0_w_wptr <= '0;
            gpu_256b_aw_to_ddr0_w_rptr <= '0;
        end else begin
            if (gpu_256b_aw_to_ddr0_w_push) begin
                gpu_256b_aw_to_ddr0_w_mem[gpu_256b_aw_to_ddr0_w_wptr] <= 1'b1;
                gpu_256b_aw_to_ddr0_w_wptr <= gpu_256b_aw_to_ddr0_w_wptr + 1'b1;
            end
            if (gpu_256b_aw_to_ddr0_w_pop) begin
                gpu_256b_aw_to_ddr0_w_rptr <= gpu_256b_aw_to_ddr0_w_rptr + 1'b1;
            end
        end
    end
    assign gpu_256b_w_to_ddr0 = (gpu_256b_aw_to_ddr0_w_wptr != gpu_256b_aw_to_ddr0_w_rptr) ? gpu_256b_aw_to_ddr0_w_mem[gpu_256b_aw_to_ddr0_w_rptr] : 1'b0;

    // AW->W tracking FIFO: vpu -> ddr0
    logic vpu_256b_w_to_ddr0;
    logic [3:0] vpu_256b_aw_to_ddr0_w_wptr, vpu_256b_aw_to_ddr0_w_rptr;
    logic vpu_256b_aw_to_ddr0_w_mem [16];
    logic vpu_256b_aw_to_ddr0_w_push, vpu_256b_aw_to_ddr0_w_pop;
    assign vpu_256b_aw_to_ddr0_w_push = vpu_256b_awvalid && vpu_256b_awready && vpu_256b_aw_to_ddr0;
    assign vpu_256b_aw_to_ddr0_w_pop  = vpu_256b_wvalid && vpu_256b_wready && vpu_256b_w.last && vpu_256b_w_to_ddr0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            vpu_256b_aw_to_ddr0_w_wptr <= '0;
            vpu_256b_aw_to_ddr0_w_rptr <= '0;
        end else begin
            if (vpu_256b_aw_to_ddr0_w_push) begin
                vpu_256b_aw_to_ddr0_w_mem[vpu_256b_aw_to_ddr0_w_wptr] <= 1'b1;
                vpu_256b_aw_to_ddr0_w_wptr <= vpu_256b_aw_to_ddr0_w_wptr + 1'b1;
            end
            if (vpu_256b_aw_to_ddr0_w_pop) begin
                vpu_256b_aw_to_ddr0_w_rptr <= vpu_256b_aw_to_ddr0_w_rptr + 1'b1;
            end
        end
    end
    assign vpu_256b_w_to_ddr0 = (vpu_256b_aw_to_ddr0_w_wptr != vpu_256b_aw_to_ddr0_w_rptr) ? vpu_256b_aw_to_ddr0_w_mem[vpu_256b_aw_to_ddr0_w_rptr] : 1'b0;

    // W channel (OR-merged across writing masters, gated by w_to_<slave> FIFO)
    assign ddr0_axi_wdata = ((cpu_256b_w_to_ddr0 && cpu_256b_wvalid) ? cpu_256b_w.data : '0) |
        ((dma_256b_w_to_ddr0 && dma_256b_wvalid) ? dma_256b_w.data : '0) |
        ((gpu_256b_w_to_ddr0 && gpu_256b_wvalid) ? gpu_256b_w.data : '0) |
        ((vpu_256b_w_to_ddr0 && vpu_256b_wvalid) ? vpu_256b_w.data : '0);
    assign ddr0_axi_wstrb = ((cpu_256b_w_to_ddr0 && cpu_256b_wvalid) ? cpu_256b_w.strb : '0) |
        ((dma_256b_w_to_ddr0 && dma_256b_wvalid) ? dma_256b_w.strb : '0) |
        ((gpu_256b_w_to_ddr0 && gpu_256b_wvalid) ? gpu_256b_w.strb : '0) |
        ((vpu_256b_w_to_ddr0 && vpu_256b_wvalid) ? vpu_256b_w.strb : '0);
    assign ddr0_axi_wlast = ((cpu_256b_w_to_ddr0 && cpu_256b_wvalid) ? cpu_256b_w.last : '0) |
        ((dma_256b_w_to_ddr0 && dma_256b_wvalid) ? dma_256b_w.last : '0) |
        ((gpu_256b_w_to_ddr0 && gpu_256b_wvalid) ? gpu_256b_w.last : '0) |
        ((vpu_256b_w_to_ddr0 && vpu_256b_wvalid) ? vpu_256b_w.last : '0);
    assign ddr0_axi_wvalid = ((cpu_256b_w_to_ddr0 && cpu_256b_wvalid) ? cpu_256b_wvalid : '0) |
        ((dma_256b_w_to_ddr0 && dma_256b_wvalid) ? dma_256b_wvalid : '0) |
        ((gpu_256b_w_to_ddr0 && gpu_256b_wvalid) ? gpu_256b_wvalid : '0) |
        ((vpu_256b_w_to_ddr0 && vpu_256b_wvalid) ? vpu_256b_wvalid : '0);

    // Bready (slave → owning master, by bid_bridge_id)
    assign ddr0_axi_bready = ((ddr0_axi_bid_bridge_id == 0) && ddr0_axi_bid_valid ? cpu_256b_bready : '0) |
        ((ddr0_axi_bid_bridge_id == 1) && ddr0_axi_bid_valid ? dma_256b_bready : '0) |
        ((ddr0_axi_bid_bridge_id == 2) && ddr0_axi_bid_valid ? gpu_256b_bready : '0) |
        ((ddr0_axi_bid_bridge_id == 3) && ddr0_axi_bid_valid ? vpu_256b_bready : '0);

    // Bridge ID (writes) — picks the originating master's id
    assign ddr0_axi_bridge_id_aw = ((cpu_256b_aw_to_ddr0 && cpu_256b_awvalid) ? cpu_bridge_id_aw : '0) |
        ((dma_256b_aw_to_ddr0 && dma_256b_awvalid) ? dma_bridge_id_aw : '0) |
        ((gpu_256b_aw_to_ddr0 && gpu_256b_awvalid) ? gpu_bridge_id_aw : '0) |
        ((vpu_256b_aw_to_ddr0 && vpu_256b_awvalid) ? vpu_bridge_id_aw : '0);

    // AR channel (OR-merged across reading masters)
    assign ddr0_axi_arid = ((cpu_256b_ar_to_ddr0 && cpu_256b_arvalid) ? cpu_256b_ar.id : '0) |
        ((dma_256b_ar_to_ddr0 && dma_256b_arvalid) ? dma_256b_ar.id : '0) |
        ((gpu_256b_ar_to_ddr0 && gpu_256b_arvalid) ? gpu_256b_ar.id : '0) |
        ((vpu_256b_ar_to_ddr0 && vpu_256b_arvalid) ? vpu_256b_ar.id : '0);
    assign ddr0_axi_araddr = ((cpu_256b_ar_to_ddr0 && cpu_256b_arvalid) ? cpu_256b_ar.addr : '0) |
        ((dma_256b_ar_to_ddr0 && dma_256b_arvalid) ? dma_256b_ar.addr : '0) |
        ((gpu_256b_ar_to_ddr0 && gpu_256b_arvalid) ? gpu_256b_ar.addr : '0) |
        ((vpu_256b_ar_to_ddr0 && vpu_256b_arvalid) ? vpu_256b_ar.addr : '0);
    assign ddr0_axi_arlen = ((cpu_256b_ar_to_ddr0 && cpu_256b_arvalid) ? cpu_256b_ar.len : '0) |
        ((dma_256b_ar_to_ddr0 && dma_256b_arvalid) ? dma_256b_ar.len : '0) |
        ((gpu_256b_ar_to_ddr0 && gpu_256b_arvalid) ? gpu_256b_ar.len : '0) |
        ((vpu_256b_ar_to_ddr0 && vpu_256b_arvalid) ? vpu_256b_ar.len : '0);
    assign ddr0_axi_arsize = ((cpu_256b_ar_to_ddr0 && cpu_256b_arvalid) ? cpu_256b_ar.size : '0) |
        ((dma_256b_ar_to_ddr0 && dma_256b_arvalid) ? dma_256b_ar.size : '0) |
        ((gpu_256b_ar_to_ddr0 && gpu_256b_arvalid) ? gpu_256b_ar.size : '0) |
        ((vpu_256b_ar_to_ddr0 && vpu_256b_arvalid) ? vpu_256b_ar.size : '0);
    assign ddr0_axi_arburst = ((cpu_256b_ar_to_ddr0 && cpu_256b_arvalid) ? cpu_256b_ar.burst : '0) |
        ((dma_256b_ar_to_ddr0 && dma_256b_arvalid) ? dma_256b_ar.burst : '0) |
        ((gpu_256b_ar_to_ddr0 && gpu_256b_arvalid) ? gpu_256b_ar.burst : '0) |
        ((vpu_256b_ar_to_ddr0 && vpu_256b_arvalid) ? vpu_256b_ar.burst : '0);
    assign ddr0_axi_arlock = ((cpu_256b_ar_to_ddr0 && cpu_256b_arvalid) ? cpu_256b_ar.lock : '0) |
        ((dma_256b_ar_to_ddr0 && dma_256b_arvalid) ? dma_256b_ar.lock : '0) |
        ((gpu_256b_ar_to_ddr0 && gpu_256b_arvalid) ? gpu_256b_ar.lock : '0) |
        ((vpu_256b_ar_to_ddr0 && vpu_256b_arvalid) ? vpu_256b_ar.lock : '0);
    assign ddr0_axi_arcache = ((cpu_256b_ar_to_ddr0 && cpu_256b_arvalid) ? cpu_256b_ar.cache : '0) |
        ((dma_256b_ar_to_ddr0 && dma_256b_arvalid) ? dma_256b_ar.cache : '0) |
        ((gpu_256b_ar_to_ddr0 && gpu_256b_arvalid) ? gpu_256b_ar.cache : '0) |
        ((vpu_256b_ar_to_ddr0 && vpu_256b_arvalid) ? vpu_256b_ar.cache : '0);
    assign ddr0_axi_arprot = ((cpu_256b_ar_to_ddr0 && cpu_256b_arvalid) ? cpu_256b_ar.prot : '0) |
        ((dma_256b_ar_to_ddr0 && dma_256b_arvalid) ? dma_256b_ar.prot : '0) |
        ((gpu_256b_ar_to_ddr0 && gpu_256b_arvalid) ? gpu_256b_ar.prot : '0) |
        ((vpu_256b_ar_to_ddr0 && vpu_256b_arvalid) ? vpu_256b_ar.prot : '0);
    assign ddr0_axi_arvalid = ((cpu_256b_ar_to_ddr0 && cpu_256b_arvalid) ? cpu_256b_arvalid : '0) |
        ((dma_256b_ar_to_ddr0 && dma_256b_arvalid) ? dma_256b_arvalid : '0) |
        ((gpu_256b_ar_to_ddr0 && gpu_256b_arvalid) ? gpu_256b_arvalid : '0) |
        ((vpu_256b_ar_to_ddr0 && vpu_256b_arvalid) ? vpu_256b_arvalid : '0);

    // Rready (slave → owning master, by rid_bridge_id)
    assign ddr0_axi_rready = ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? cpu_256b_rready : '0) |
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? dma_256b_rready : '0) |
        ((ddr0_axi_rid_bridge_id == 2) && ddr0_axi_rid_valid ? gpu_256b_rready : '0) |
        ((ddr0_axi_rid_bridge_id == 3) && ddr0_axi_rid_valid ? vpu_256b_rready : '0);

    // Bridge ID (reads) — picks the originating master's id
    assign ddr0_axi_bridge_id_ar = ((cpu_256b_ar_to_ddr0 && cpu_256b_arvalid) ? cpu_bridge_id_ar : '0) |
        ((dma_256b_ar_to_ddr0 && dma_256b_arvalid) ? dma_bridge_id_ar : '0) |
        ((gpu_256b_ar_to_ddr0 && gpu_256b_arvalid) ? gpu_bridge_id_ar : '0) |
        ((vpu_256b_ar_to_ddr0 && vpu_256b_arvalid) ? vpu_bridge_id_ar : '0);


    // ================================================================
    // Slave 1: ddr1 (128b)
    // ================================================================
    // Multi-master (4 masters) → ddr1
    //   - cpu (rw)
    //   - dma (rw)
    //   - gpu (rw)
    //   - vpu (rw)

    wire cpu_128b_aw_to_ddr1 = ((cpu_128b_aw.addr >= 32'h40000000) && (cpu_128b_aw.addr <= 32'h7fffffff));
    wire cpu_128b_ar_to_ddr1 = ((cpu_128b_ar.addr >= 32'h40000000) && (cpu_128b_ar.addr <= 32'h7fffffff));
    wire dma_128b_aw_to_ddr1 = ((dma_128b_aw.addr >= 32'h40000000) && (dma_128b_aw.addr <= 32'h7fffffff));
    wire dma_128b_ar_to_ddr1 = ((dma_128b_ar.addr >= 32'h40000000) && (dma_128b_ar.addr <= 32'h7fffffff));
    wire gpu_128b_aw_to_ddr1 = ((gpu_128b_aw.addr >= 32'h40000000) && (gpu_128b_aw.addr <= 32'h7fffffff));
    wire gpu_128b_ar_to_ddr1 = ((gpu_128b_ar.addr >= 32'h40000000) && (gpu_128b_ar.addr <= 32'h7fffffff));
    wire vpu_128b_aw_to_ddr1 = ((vpu_128b_aw.addr >= 32'h40000000) && (vpu_128b_aw.addr <= 32'h7fffffff));
    wire vpu_128b_ar_to_ddr1 = ((vpu_128b_ar.addr >= 32'h40000000) && (vpu_128b_ar.addr <= 32'h7fffffff));

    // AW channel (OR-merged across writing masters)
    assign ddr1_axi_awid = ((cpu_128b_aw_to_ddr1 && cpu_128b_awvalid) ? cpu_128b_aw.id : '0) |
        ((dma_128b_aw_to_ddr1 && dma_128b_awvalid) ? dma_128b_aw.id : '0) |
        ((gpu_128b_aw_to_ddr1 && gpu_128b_awvalid) ? gpu_128b_aw.id : '0) |
        ((vpu_128b_aw_to_ddr1 && vpu_128b_awvalid) ? vpu_128b_aw.id : '0);
    assign ddr1_axi_awaddr = ((cpu_128b_aw_to_ddr1 && cpu_128b_awvalid) ? cpu_128b_aw.addr : '0) |
        ((dma_128b_aw_to_ddr1 && dma_128b_awvalid) ? dma_128b_aw.addr : '0) |
        ((gpu_128b_aw_to_ddr1 && gpu_128b_awvalid) ? gpu_128b_aw.addr : '0) |
        ((vpu_128b_aw_to_ddr1 && vpu_128b_awvalid) ? vpu_128b_aw.addr : '0);
    assign ddr1_axi_awlen = ((cpu_128b_aw_to_ddr1 && cpu_128b_awvalid) ? cpu_128b_aw.len : '0) |
        ((dma_128b_aw_to_ddr1 && dma_128b_awvalid) ? dma_128b_aw.len : '0) |
        ((gpu_128b_aw_to_ddr1 && gpu_128b_awvalid) ? gpu_128b_aw.len : '0) |
        ((vpu_128b_aw_to_ddr1 && vpu_128b_awvalid) ? vpu_128b_aw.len : '0);
    assign ddr1_axi_awsize = ((cpu_128b_aw_to_ddr1 && cpu_128b_awvalid) ? cpu_128b_aw.size : '0) |
        ((dma_128b_aw_to_ddr1 && dma_128b_awvalid) ? dma_128b_aw.size : '0) |
        ((gpu_128b_aw_to_ddr1 && gpu_128b_awvalid) ? gpu_128b_aw.size : '0) |
        ((vpu_128b_aw_to_ddr1 && vpu_128b_awvalid) ? vpu_128b_aw.size : '0);
    assign ddr1_axi_awburst = ((cpu_128b_aw_to_ddr1 && cpu_128b_awvalid) ? cpu_128b_aw.burst : '0) |
        ((dma_128b_aw_to_ddr1 && dma_128b_awvalid) ? dma_128b_aw.burst : '0) |
        ((gpu_128b_aw_to_ddr1 && gpu_128b_awvalid) ? gpu_128b_aw.burst : '0) |
        ((vpu_128b_aw_to_ddr1 && vpu_128b_awvalid) ? vpu_128b_aw.burst : '0);
    assign ddr1_axi_awlock = ((cpu_128b_aw_to_ddr1 && cpu_128b_awvalid) ? cpu_128b_aw.lock : '0) |
        ((dma_128b_aw_to_ddr1 && dma_128b_awvalid) ? dma_128b_aw.lock : '0) |
        ((gpu_128b_aw_to_ddr1 && gpu_128b_awvalid) ? gpu_128b_aw.lock : '0) |
        ((vpu_128b_aw_to_ddr1 && vpu_128b_awvalid) ? vpu_128b_aw.lock : '0);
    assign ddr1_axi_awcache = ((cpu_128b_aw_to_ddr1 && cpu_128b_awvalid) ? cpu_128b_aw.cache : '0) |
        ((dma_128b_aw_to_ddr1 && dma_128b_awvalid) ? dma_128b_aw.cache : '0) |
        ((gpu_128b_aw_to_ddr1 && gpu_128b_awvalid) ? gpu_128b_aw.cache : '0) |
        ((vpu_128b_aw_to_ddr1 && vpu_128b_awvalid) ? vpu_128b_aw.cache : '0);
    assign ddr1_axi_awprot = ((cpu_128b_aw_to_ddr1 && cpu_128b_awvalid) ? cpu_128b_aw.prot : '0) |
        ((dma_128b_aw_to_ddr1 && dma_128b_awvalid) ? dma_128b_aw.prot : '0) |
        ((gpu_128b_aw_to_ddr1 && gpu_128b_awvalid) ? gpu_128b_aw.prot : '0) |
        ((vpu_128b_aw_to_ddr1 && vpu_128b_awvalid) ? vpu_128b_aw.prot : '0);
    assign ddr1_axi_awvalid = ((cpu_128b_aw_to_ddr1 && cpu_128b_awvalid) ? cpu_128b_awvalid : '0) |
        ((dma_128b_aw_to_ddr1 && dma_128b_awvalid) ? dma_128b_awvalid : '0) |
        ((gpu_128b_aw_to_ddr1 && gpu_128b_awvalid) ? gpu_128b_awvalid : '0) |
        ((vpu_128b_aw_to_ddr1 && vpu_128b_awvalid) ? vpu_128b_awvalid : '0);

    // AW->W tracking FIFO: cpu -> ddr1
    logic cpu_128b_w_to_ddr1;
    logic [3:0] cpu_128b_aw_to_ddr1_w_wptr, cpu_128b_aw_to_ddr1_w_rptr;
    logic cpu_128b_aw_to_ddr1_w_mem [16];
    logic cpu_128b_aw_to_ddr1_w_push, cpu_128b_aw_to_ddr1_w_pop;
    assign cpu_128b_aw_to_ddr1_w_push = cpu_128b_awvalid && cpu_128b_awready && cpu_128b_aw_to_ddr1;
    assign cpu_128b_aw_to_ddr1_w_pop  = cpu_128b_wvalid && cpu_128b_wready && cpu_128b_w.last && cpu_128b_w_to_ddr1;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            cpu_128b_aw_to_ddr1_w_wptr <= '0;
            cpu_128b_aw_to_ddr1_w_rptr <= '0;
        end else begin
            if (cpu_128b_aw_to_ddr1_w_push) begin
                cpu_128b_aw_to_ddr1_w_mem[cpu_128b_aw_to_ddr1_w_wptr] <= 1'b1;
                cpu_128b_aw_to_ddr1_w_wptr <= cpu_128b_aw_to_ddr1_w_wptr + 1'b1;
            end
            if (cpu_128b_aw_to_ddr1_w_pop) begin
                cpu_128b_aw_to_ddr1_w_rptr <= cpu_128b_aw_to_ddr1_w_rptr + 1'b1;
            end
        end
    end
    assign cpu_128b_w_to_ddr1 = (cpu_128b_aw_to_ddr1_w_wptr != cpu_128b_aw_to_ddr1_w_rptr) ? cpu_128b_aw_to_ddr1_w_mem[cpu_128b_aw_to_ddr1_w_rptr] : 1'b0;

    // AW->W tracking FIFO: dma -> ddr1
    logic dma_128b_w_to_ddr1;
    logic [3:0] dma_128b_aw_to_ddr1_w_wptr, dma_128b_aw_to_ddr1_w_rptr;
    logic dma_128b_aw_to_ddr1_w_mem [16];
    logic dma_128b_aw_to_ddr1_w_push, dma_128b_aw_to_ddr1_w_pop;
    assign dma_128b_aw_to_ddr1_w_push = dma_128b_awvalid && dma_128b_awready && dma_128b_aw_to_ddr1;
    assign dma_128b_aw_to_ddr1_w_pop  = dma_128b_wvalid && dma_128b_wready && dma_128b_w.last && dma_128b_w_to_ddr1;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            dma_128b_aw_to_ddr1_w_wptr <= '0;
            dma_128b_aw_to_ddr1_w_rptr <= '0;
        end else begin
            if (dma_128b_aw_to_ddr1_w_push) begin
                dma_128b_aw_to_ddr1_w_mem[dma_128b_aw_to_ddr1_w_wptr] <= 1'b1;
                dma_128b_aw_to_ddr1_w_wptr <= dma_128b_aw_to_ddr1_w_wptr + 1'b1;
            end
            if (dma_128b_aw_to_ddr1_w_pop) begin
                dma_128b_aw_to_ddr1_w_rptr <= dma_128b_aw_to_ddr1_w_rptr + 1'b1;
            end
        end
    end
    assign dma_128b_w_to_ddr1 = (dma_128b_aw_to_ddr1_w_wptr != dma_128b_aw_to_ddr1_w_rptr) ? dma_128b_aw_to_ddr1_w_mem[dma_128b_aw_to_ddr1_w_rptr] : 1'b0;

    // AW->W tracking FIFO: gpu -> ddr1
    logic gpu_128b_w_to_ddr1;
    logic [3:0] gpu_128b_aw_to_ddr1_w_wptr, gpu_128b_aw_to_ddr1_w_rptr;
    logic gpu_128b_aw_to_ddr1_w_mem [16];
    logic gpu_128b_aw_to_ddr1_w_push, gpu_128b_aw_to_ddr1_w_pop;
    assign gpu_128b_aw_to_ddr1_w_push = gpu_128b_awvalid && gpu_128b_awready && gpu_128b_aw_to_ddr1;
    assign gpu_128b_aw_to_ddr1_w_pop  = gpu_128b_wvalid && gpu_128b_wready && gpu_128b_w.last && gpu_128b_w_to_ddr1;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            gpu_128b_aw_to_ddr1_w_wptr <= '0;
            gpu_128b_aw_to_ddr1_w_rptr <= '0;
        end else begin
            if (gpu_128b_aw_to_ddr1_w_push) begin
                gpu_128b_aw_to_ddr1_w_mem[gpu_128b_aw_to_ddr1_w_wptr] <= 1'b1;
                gpu_128b_aw_to_ddr1_w_wptr <= gpu_128b_aw_to_ddr1_w_wptr + 1'b1;
            end
            if (gpu_128b_aw_to_ddr1_w_pop) begin
                gpu_128b_aw_to_ddr1_w_rptr <= gpu_128b_aw_to_ddr1_w_rptr + 1'b1;
            end
        end
    end
    assign gpu_128b_w_to_ddr1 = (gpu_128b_aw_to_ddr1_w_wptr != gpu_128b_aw_to_ddr1_w_rptr) ? gpu_128b_aw_to_ddr1_w_mem[gpu_128b_aw_to_ddr1_w_rptr] : 1'b0;

    // AW->W tracking FIFO: vpu -> ddr1
    logic vpu_128b_w_to_ddr1;
    logic [3:0] vpu_128b_aw_to_ddr1_w_wptr, vpu_128b_aw_to_ddr1_w_rptr;
    logic vpu_128b_aw_to_ddr1_w_mem [16];
    logic vpu_128b_aw_to_ddr1_w_push, vpu_128b_aw_to_ddr1_w_pop;
    assign vpu_128b_aw_to_ddr1_w_push = vpu_128b_awvalid && vpu_128b_awready && vpu_128b_aw_to_ddr1;
    assign vpu_128b_aw_to_ddr1_w_pop  = vpu_128b_wvalid && vpu_128b_wready && vpu_128b_w.last && vpu_128b_w_to_ddr1;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            vpu_128b_aw_to_ddr1_w_wptr <= '0;
            vpu_128b_aw_to_ddr1_w_rptr <= '0;
        end else begin
            if (vpu_128b_aw_to_ddr1_w_push) begin
                vpu_128b_aw_to_ddr1_w_mem[vpu_128b_aw_to_ddr1_w_wptr] <= 1'b1;
                vpu_128b_aw_to_ddr1_w_wptr <= vpu_128b_aw_to_ddr1_w_wptr + 1'b1;
            end
            if (vpu_128b_aw_to_ddr1_w_pop) begin
                vpu_128b_aw_to_ddr1_w_rptr <= vpu_128b_aw_to_ddr1_w_rptr + 1'b1;
            end
        end
    end
    assign vpu_128b_w_to_ddr1 = (vpu_128b_aw_to_ddr1_w_wptr != vpu_128b_aw_to_ddr1_w_rptr) ? vpu_128b_aw_to_ddr1_w_mem[vpu_128b_aw_to_ddr1_w_rptr] : 1'b0;

    // W channel (OR-merged across writing masters, gated by w_to_<slave> FIFO)
    assign ddr1_axi_wdata = ((cpu_128b_w_to_ddr1 && cpu_128b_wvalid) ? cpu_128b_w.data : '0) |
        ((dma_128b_w_to_ddr1 && dma_128b_wvalid) ? dma_128b_w.data : '0) |
        ((gpu_128b_w_to_ddr1 && gpu_128b_wvalid) ? gpu_128b_w.data : '0) |
        ((vpu_128b_w_to_ddr1 && vpu_128b_wvalid) ? vpu_128b_w.data : '0);
    assign ddr1_axi_wstrb = ((cpu_128b_w_to_ddr1 && cpu_128b_wvalid) ? cpu_128b_w.strb : '0) |
        ((dma_128b_w_to_ddr1 && dma_128b_wvalid) ? dma_128b_w.strb : '0) |
        ((gpu_128b_w_to_ddr1 && gpu_128b_wvalid) ? gpu_128b_w.strb : '0) |
        ((vpu_128b_w_to_ddr1 && vpu_128b_wvalid) ? vpu_128b_w.strb : '0);
    assign ddr1_axi_wlast = ((cpu_128b_w_to_ddr1 && cpu_128b_wvalid) ? cpu_128b_w.last : '0) |
        ((dma_128b_w_to_ddr1 && dma_128b_wvalid) ? dma_128b_w.last : '0) |
        ((gpu_128b_w_to_ddr1 && gpu_128b_wvalid) ? gpu_128b_w.last : '0) |
        ((vpu_128b_w_to_ddr1 && vpu_128b_wvalid) ? vpu_128b_w.last : '0);
    assign ddr1_axi_wvalid = ((cpu_128b_w_to_ddr1 && cpu_128b_wvalid) ? cpu_128b_wvalid : '0) |
        ((dma_128b_w_to_ddr1 && dma_128b_wvalid) ? dma_128b_wvalid : '0) |
        ((gpu_128b_w_to_ddr1 && gpu_128b_wvalid) ? gpu_128b_wvalid : '0) |
        ((vpu_128b_w_to_ddr1 && vpu_128b_wvalid) ? vpu_128b_wvalid : '0);

    // Bready (slave → owning master, by bid_bridge_id)
    assign ddr1_axi_bready = ((ddr1_axi_bid_bridge_id == 0) && ddr1_axi_bid_valid ? cpu_128b_bready : '0) |
        ((ddr1_axi_bid_bridge_id == 1) && ddr1_axi_bid_valid ? dma_128b_bready : '0) |
        ((ddr1_axi_bid_bridge_id == 2) && ddr1_axi_bid_valid ? gpu_128b_bready : '0) |
        ((ddr1_axi_bid_bridge_id == 3) && ddr1_axi_bid_valid ? vpu_128b_bready : '0);

    // Bridge ID (writes) — picks the originating master's id
    assign ddr1_axi_bridge_id_aw = ((cpu_128b_aw_to_ddr1 && cpu_128b_awvalid) ? cpu_bridge_id_aw : '0) |
        ((dma_128b_aw_to_ddr1 && dma_128b_awvalid) ? dma_bridge_id_aw : '0) |
        ((gpu_128b_aw_to_ddr1 && gpu_128b_awvalid) ? gpu_bridge_id_aw : '0) |
        ((vpu_128b_aw_to_ddr1 && vpu_128b_awvalid) ? vpu_bridge_id_aw : '0);

    // AR channel (OR-merged across reading masters)
    assign ddr1_axi_arid = ((cpu_128b_ar_to_ddr1 && cpu_128b_arvalid) ? cpu_128b_ar.id : '0) |
        ((dma_128b_ar_to_ddr1 && dma_128b_arvalid) ? dma_128b_ar.id : '0) |
        ((gpu_128b_ar_to_ddr1 && gpu_128b_arvalid) ? gpu_128b_ar.id : '0) |
        ((vpu_128b_ar_to_ddr1 && vpu_128b_arvalid) ? vpu_128b_ar.id : '0);
    assign ddr1_axi_araddr = ((cpu_128b_ar_to_ddr1 && cpu_128b_arvalid) ? cpu_128b_ar.addr : '0) |
        ((dma_128b_ar_to_ddr1 && dma_128b_arvalid) ? dma_128b_ar.addr : '0) |
        ((gpu_128b_ar_to_ddr1 && gpu_128b_arvalid) ? gpu_128b_ar.addr : '0) |
        ((vpu_128b_ar_to_ddr1 && vpu_128b_arvalid) ? vpu_128b_ar.addr : '0);
    assign ddr1_axi_arlen = ((cpu_128b_ar_to_ddr1 && cpu_128b_arvalid) ? cpu_128b_ar.len : '0) |
        ((dma_128b_ar_to_ddr1 && dma_128b_arvalid) ? dma_128b_ar.len : '0) |
        ((gpu_128b_ar_to_ddr1 && gpu_128b_arvalid) ? gpu_128b_ar.len : '0) |
        ((vpu_128b_ar_to_ddr1 && vpu_128b_arvalid) ? vpu_128b_ar.len : '0);
    assign ddr1_axi_arsize = ((cpu_128b_ar_to_ddr1 && cpu_128b_arvalid) ? cpu_128b_ar.size : '0) |
        ((dma_128b_ar_to_ddr1 && dma_128b_arvalid) ? dma_128b_ar.size : '0) |
        ((gpu_128b_ar_to_ddr1 && gpu_128b_arvalid) ? gpu_128b_ar.size : '0) |
        ((vpu_128b_ar_to_ddr1 && vpu_128b_arvalid) ? vpu_128b_ar.size : '0);
    assign ddr1_axi_arburst = ((cpu_128b_ar_to_ddr1 && cpu_128b_arvalid) ? cpu_128b_ar.burst : '0) |
        ((dma_128b_ar_to_ddr1 && dma_128b_arvalid) ? dma_128b_ar.burst : '0) |
        ((gpu_128b_ar_to_ddr1 && gpu_128b_arvalid) ? gpu_128b_ar.burst : '0) |
        ((vpu_128b_ar_to_ddr1 && vpu_128b_arvalid) ? vpu_128b_ar.burst : '0);
    assign ddr1_axi_arlock = ((cpu_128b_ar_to_ddr1 && cpu_128b_arvalid) ? cpu_128b_ar.lock : '0) |
        ((dma_128b_ar_to_ddr1 && dma_128b_arvalid) ? dma_128b_ar.lock : '0) |
        ((gpu_128b_ar_to_ddr1 && gpu_128b_arvalid) ? gpu_128b_ar.lock : '0) |
        ((vpu_128b_ar_to_ddr1 && vpu_128b_arvalid) ? vpu_128b_ar.lock : '0);
    assign ddr1_axi_arcache = ((cpu_128b_ar_to_ddr1 && cpu_128b_arvalid) ? cpu_128b_ar.cache : '0) |
        ((dma_128b_ar_to_ddr1 && dma_128b_arvalid) ? dma_128b_ar.cache : '0) |
        ((gpu_128b_ar_to_ddr1 && gpu_128b_arvalid) ? gpu_128b_ar.cache : '0) |
        ((vpu_128b_ar_to_ddr1 && vpu_128b_arvalid) ? vpu_128b_ar.cache : '0);
    assign ddr1_axi_arprot = ((cpu_128b_ar_to_ddr1 && cpu_128b_arvalid) ? cpu_128b_ar.prot : '0) |
        ((dma_128b_ar_to_ddr1 && dma_128b_arvalid) ? dma_128b_ar.prot : '0) |
        ((gpu_128b_ar_to_ddr1 && gpu_128b_arvalid) ? gpu_128b_ar.prot : '0) |
        ((vpu_128b_ar_to_ddr1 && vpu_128b_arvalid) ? vpu_128b_ar.prot : '0);
    assign ddr1_axi_arvalid = ((cpu_128b_ar_to_ddr1 && cpu_128b_arvalid) ? cpu_128b_arvalid : '0) |
        ((dma_128b_ar_to_ddr1 && dma_128b_arvalid) ? dma_128b_arvalid : '0) |
        ((gpu_128b_ar_to_ddr1 && gpu_128b_arvalid) ? gpu_128b_arvalid : '0) |
        ((vpu_128b_ar_to_ddr1 && vpu_128b_arvalid) ? vpu_128b_arvalid : '0);

    // Rready (slave → owning master, by rid_bridge_id)
    assign ddr1_axi_rready = ((ddr1_axi_rid_bridge_id == 0) && ddr1_axi_rid_valid ? cpu_128b_rready : '0) |
        ((ddr1_axi_rid_bridge_id == 1) && ddr1_axi_rid_valid ? dma_128b_rready : '0) |
        ((ddr1_axi_rid_bridge_id == 2) && ddr1_axi_rid_valid ? gpu_128b_rready : '0) |
        ((ddr1_axi_rid_bridge_id == 3) && ddr1_axi_rid_valid ? vpu_128b_rready : '0);

    // Bridge ID (reads) — picks the originating master's id
    assign ddr1_axi_bridge_id_ar = ((cpu_128b_ar_to_ddr1 && cpu_128b_arvalid) ? cpu_bridge_id_ar : '0) |
        ((dma_128b_ar_to_ddr1 && dma_128b_arvalid) ? dma_bridge_id_ar : '0) |
        ((gpu_128b_ar_to_ddr1 && gpu_128b_arvalid) ? gpu_bridge_id_ar : '0) |
        ((vpu_128b_ar_to_ddr1 && vpu_128b_arvalid) ? vpu_bridge_id_ar : '0);


    // ================================================================
    // Slave 2: sram (64b)
    // ================================================================
    // Multi-master (2 masters) → sram
    //   - cpu (rw)
    //   - dma (rw)

    wire cpu_64b_aw_to_sram = ((cpu_64b_aw.addr >= 32'h80000000) && (cpu_64b_aw.addr <= 32'h80ffffff));
    wire cpu_64b_ar_to_sram = ((cpu_64b_ar.addr >= 32'h80000000) && (cpu_64b_ar.addr <= 32'h80ffffff));
    wire dma_64b_aw_to_sram = ((dma_64b_aw.addr >= 32'h80000000) && (dma_64b_aw.addr <= 32'h80ffffff));
    wire dma_64b_ar_to_sram = ((dma_64b_ar.addr >= 32'h80000000) && (dma_64b_ar.addr <= 32'h80ffffff));

    // AW channel (OR-merged across writing masters)
    assign sram_axi_awid = ((cpu_64b_aw_to_sram && cpu_64b_awvalid) ? cpu_64b_aw.id : '0) |
        ((dma_64b_aw_to_sram && dma_64b_awvalid) ? dma_64b_aw.id : '0);
    assign sram_axi_awaddr = ((cpu_64b_aw_to_sram && cpu_64b_awvalid) ? cpu_64b_aw.addr : '0) |
        ((dma_64b_aw_to_sram && dma_64b_awvalid) ? dma_64b_aw.addr : '0);
    assign sram_axi_awlen = ((cpu_64b_aw_to_sram && cpu_64b_awvalid) ? cpu_64b_aw.len : '0) |
        ((dma_64b_aw_to_sram && dma_64b_awvalid) ? dma_64b_aw.len : '0);
    assign sram_axi_awsize = ((cpu_64b_aw_to_sram && cpu_64b_awvalid) ? cpu_64b_aw.size : '0) |
        ((dma_64b_aw_to_sram && dma_64b_awvalid) ? dma_64b_aw.size : '0);
    assign sram_axi_awburst = ((cpu_64b_aw_to_sram && cpu_64b_awvalid) ? cpu_64b_aw.burst : '0) |
        ((dma_64b_aw_to_sram && dma_64b_awvalid) ? dma_64b_aw.burst : '0);
    assign sram_axi_awlock = ((cpu_64b_aw_to_sram && cpu_64b_awvalid) ? cpu_64b_aw.lock : '0) |
        ((dma_64b_aw_to_sram && dma_64b_awvalid) ? dma_64b_aw.lock : '0);
    assign sram_axi_awcache = ((cpu_64b_aw_to_sram && cpu_64b_awvalid) ? cpu_64b_aw.cache : '0) |
        ((dma_64b_aw_to_sram && dma_64b_awvalid) ? dma_64b_aw.cache : '0);
    assign sram_axi_awprot = ((cpu_64b_aw_to_sram && cpu_64b_awvalid) ? cpu_64b_aw.prot : '0) |
        ((dma_64b_aw_to_sram && dma_64b_awvalid) ? dma_64b_aw.prot : '0);
    assign sram_axi_awvalid = ((cpu_64b_aw_to_sram && cpu_64b_awvalid) ? cpu_64b_awvalid : '0) |
        ((dma_64b_aw_to_sram && dma_64b_awvalid) ? dma_64b_awvalid : '0);

    // AW->W tracking FIFO: cpu -> sram
    logic cpu_64b_w_to_sram;
    logic [3:0] cpu_64b_aw_to_sram_w_wptr, cpu_64b_aw_to_sram_w_rptr;
    logic cpu_64b_aw_to_sram_w_mem [16];
    logic cpu_64b_aw_to_sram_w_push, cpu_64b_aw_to_sram_w_pop;
    assign cpu_64b_aw_to_sram_w_push = cpu_64b_awvalid && cpu_64b_awready && cpu_64b_aw_to_sram;
    assign cpu_64b_aw_to_sram_w_pop  = cpu_64b_wvalid && cpu_64b_wready && cpu_64b_w.last && cpu_64b_w_to_sram;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            cpu_64b_aw_to_sram_w_wptr <= '0;
            cpu_64b_aw_to_sram_w_rptr <= '0;
        end else begin
            if (cpu_64b_aw_to_sram_w_push) begin
                cpu_64b_aw_to_sram_w_mem[cpu_64b_aw_to_sram_w_wptr] <= 1'b1;
                cpu_64b_aw_to_sram_w_wptr <= cpu_64b_aw_to_sram_w_wptr + 1'b1;
            end
            if (cpu_64b_aw_to_sram_w_pop) begin
                cpu_64b_aw_to_sram_w_rptr <= cpu_64b_aw_to_sram_w_rptr + 1'b1;
            end
        end
    end
    assign cpu_64b_w_to_sram = (cpu_64b_aw_to_sram_w_wptr != cpu_64b_aw_to_sram_w_rptr) ? cpu_64b_aw_to_sram_w_mem[cpu_64b_aw_to_sram_w_rptr] : 1'b0;

    // AW->W tracking FIFO: dma -> sram
    logic dma_64b_w_to_sram;
    logic [3:0] dma_64b_aw_to_sram_w_wptr, dma_64b_aw_to_sram_w_rptr;
    logic dma_64b_aw_to_sram_w_mem [16];
    logic dma_64b_aw_to_sram_w_push, dma_64b_aw_to_sram_w_pop;
    assign dma_64b_aw_to_sram_w_push = dma_64b_awvalid && dma_64b_awready && dma_64b_aw_to_sram;
    assign dma_64b_aw_to_sram_w_pop  = dma_64b_wvalid && dma_64b_wready && dma_64b_w.last && dma_64b_w_to_sram;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            dma_64b_aw_to_sram_w_wptr <= '0;
            dma_64b_aw_to_sram_w_rptr <= '0;
        end else begin
            if (dma_64b_aw_to_sram_w_push) begin
                dma_64b_aw_to_sram_w_mem[dma_64b_aw_to_sram_w_wptr] <= 1'b1;
                dma_64b_aw_to_sram_w_wptr <= dma_64b_aw_to_sram_w_wptr + 1'b1;
            end
            if (dma_64b_aw_to_sram_w_pop) begin
                dma_64b_aw_to_sram_w_rptr <= dma_64b_aw_to_sram_w_rptr + 1'b1;
            end
        end
    end
    assign dma_64b_w_to_sram = (dma_64b_aw_to_sram_w_wptr != dma_64b_aw_to_sram_w_rptr) ? dma_64b_aw_to_sram_w_mem[dma_64b_aw_to_sram_w_rptr] : 1'b0;

    // W channel (OR-merged across writing masters, gated by w_to_<slave> FIFO)
    assign sram_axi_wdata = ((cpu_64b_w_to_sram && cpu_64b_wvalid) ? cpu_64b_w.data : '0) |
        ((dma_64b_w_to_sram && dma_64b_wvalid) ? dma_64b_w.data : '0);
    assign sram_axi_wstrb = ((cpu_64b_w_to_sram && cpu_64b_wvalid) ? cpu_64b_w.strb : '0) |
        ((dma_64b_w_to_sram && dma_64b_wvalid) ? dma_64b_w.strb : '0);
    assign sram_axi_wlast = ((cpu_64b_w_to_sram && cpu_64b_wvalid) ? cpu_64b_w.last : '0) |
        ((dma_64b_w_to_sram && dma_64b_wvalid) ? dma_64b_w.last : '0);
    assign sram_axi_wvalid = ((cpu_64b_w_to_sram && cpu_64b_wvalid) ? cpu_64b_wvalid : '0) |
        ((dma_64b_w_to_sram && dma_64b_wvalid) ? dma_64b_wvalid : '0);

    // Bready (slave → owning master, by bid_bridge_id)
    assign sram_axi_bready = ((sram_axi_bid_bridge_id == 0) && sram_axi_bid_valid ? cpu_64b_bready : '0) |
        ((sram_axi_bid_bridge_id == 1) && sram_axi_bid_valid ? dma_64b_bready : '0);

    // Bridge ID (writes) — picks the originating master's id
    assign sram_axi_bridge_id_aw = ((cpu_64b_aw_to_sram && cpu_64b_awvalid) ? cpu_bridge_id_aw : '0) |
        ((dma_64b_aw_to_sram && dma_64b_awvalid) ? dma_bridge_id_aw : '0);

    // AR channel (OR-merged across reading masters)
    assign sram_axi_arid = ((cpu_64b_ar_to_sram && cpu_64b_arvalid) ? cpu_64b_ar.id : '0) |
        ((dma_64b_ar_to_sram && dma_64b_arvalid) ? dma_64b_ar.id : '0);
    assign sram_axi_araddr = ((cpu_64b_ar_to_sram && cpu_64b_arvalid) ? cpu_64b_ar.addr : '0) |
        ((dma_64b_ar_to_sram && dma_64b_arvalid) ? dma_64b_ar.addr : '0);
    assign sram_axi_arlen = ((cpu_64b_ar_to_sram && cpu_64b_arvalid) ? cpu_64b_ar.len : '0) |
        ((dma_64b_ar_to_sram && dma_64b_arvalid) ? dma_64b_ar.len : '0);
    assign sram_axi_arsize = ((cpu_64b_ar_to_sram && cpu_64b_arvalid) ? cpu_64b_ar.size : '0) |
        ((dma_64b_ar_to_sram && dma_64b_arvalid) ? dma_64b_ar.size : '0);
    assign sram_axi_arburst = ((cpu_64b_ar_to_sram && cpu_64b_arvalid) ? cpu_64b_ar.burst : '0) |
        ((dma_64b_ar_to_sram && dma_64b_arvalid) ? dma_64b_ar.burst : '0);
    assign sram_axi_arlock = ((cpu_64b_ar_to_sram && cpu_64b_arvalid) ? cpu_64b_ar.lock : '0) |
        ((dma_64b_ar_to_sram && dma_64b_arvalid) ? dma_64b_ar.lock : '0);
    assign sram_axi_arcache = ((cpu_64b_ar_to_sram && cpu_64b_arvalid) ? cpu_64b_ar.cache : '0) |
        ((dma_64b_ar_to_sram && dma_64b_arvalid) ? dma_64b_ar.cache : '0);
    assign sram_axi_arprot = ((cpu_64b_ar_to_sram && cpu_64b_arvalid) ? cpu_64b_ar.prot : '0) |
        ((dma_64b_ar_to_sram && dma_64b_arvalid) ? dma_64b_ar.prot : '0);
    assign sram_axi_arvalid = ((cpu_64b_ar_to_sram && cpu_64b_arvalid) ? cpu_64b_arvalid : '0) |
        ((dma_64b_ar_to_sram && dma_64b_arvalid) ? dma_64b_arvalid : '0);

    // Rready (slave → owning master, by rid_bridge_id)
    assign sram_axi_rready = ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? cpu_64b_rready : '0) |
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? dma_64b_rready : '0);

    // Bridge ID (reads) — picks the originating master's id
    assign sram_axi_bridge_id_ar = ((cpu_64b_ar_to_sram && cpu_64b_arvalid) ? cpu_bridge_id_ar : '0) |
        ((dma_64b_ar_to_sram && dma_64b_arvalid) ? dma_bridge_id_ar : '0);


    // ================================================================
    // Slave 3: scratch (32b)
    // ================================================================
    // Multi-master (3 masters) → scratch
    //   - cpu (rw)
    //   - dma (rw)
    //   - gpu (rw)

    wire cpu_32b_aw_to_scratch = ((cpu_32b_aw.addr >= 32'h81000000) && (cpu_32b_aw.addr <= 32'h81ffffff));
    wire cpu_32b_ar_to_scratch = ((cpu_32b_ar.addr >= 32'h81000000) && (cpu_32b_ar.addr <= 32'h81ffffff));
    wire dma_32b_aw_to_scratch = ((dma_32b_aw.addr >= 32'h81000000) && (dma_32b_aw.addr <= 32'h81ffffff));
    wire dma_32b_ar_to_scratch = ((dma_32b_ar.addr >= 32'h81000000) && (dma_32b_ar.addr <= 32'h81ffffff));
    wire gpu_32b_aw_to_scratch = ((gpu_32b_aw.addr >= 32'h81000000) && (gpu_32b_aw.addr <= 32'h81ffffff));
    wire gpu_32b_ar_to_scratch = ((gpu_32b_ar.addr >= 32'h81000000) && (gpu_32b_ar.addr <= 32'h81ffffff));

    // AW channel (OR-merged across writing masters)
    assign scratch_axi_awid = ((cpu_32b_aw_to_scratch && cpu_32b_awvalid) ? cpu_32b_aw.id : '0) |
        ((dma_32b_aw_to_scratch && dma_32b_awvalid) ? dma_32b_aw.id : '0) |
        ((gpu_32b_aw_to_scratch && gpu_32b_awvalid) ? gpu_32b_aw.id : '0);
    assign scratch_axi_awaddr = ((cpu_32b_aw_to_scratch && cpu_32b_awvalid) ? cpu_32b_aw.addr : '0) |
        ((dma_32b_aw_to_scratch && dma_32b_awvalid) ? dma_32b_aw.addr : '0) |
        ((gpu_32b_aw_to_scratch && gpu_32b_awvalid) ? gpu_32b_aw.addr : '0);
    assign scratch_axi_awlen = ((cpu_32b_aw_to_scratch && cpu_32b_awvalid) ? cpu_32b_aw.len : '0) |
        ((dma_32b_aw_to_scratch && dma_32b_awvalid) ? dma_32b_aw.len : '0) |
        ((gpu_32b_aw_to_scratch && gpu_32b_awvalid) ? gpu_32b_aw.len : '0);
    assign scratch_axi_awsize = ((cpu_32b_aw_to_scratch && cpu_32b_awvalid) ? cpu_32b_aw.size : '0) |
        ((dma_32b_aw_to_scratch && dma_32b_awvalid) ? dma_32b_aw.size : '0) |
        ((gpu_32b_aw_to_scratch && gpu_32b_awvalid) ? gpu_32b_aw.size : '0);
    assign scratch_axi_awburst = ((cpu_32b_aw_to_scratch && cpu_32b_awvalid) ? cpu_32b_aw.burst : '0) |
        ((dma_32b_aw_to_scratch && dma_32b_awvalid) ? dma_32b_aw.burst : '0) |
        ((gpu_32b_aw_to_scratch && gpu_32b_awvalid) ? gpu_32b_aw.burst : '0);
    assign scratch_axi_awlock = ((cpu_32b_aw_to_scratch && cpu_32b_awvalid) ? cpu_32b_aw.lock : '0) |
        ((dma_32b_aw_to_scratch && dma_32b_awvalid) ? dma_32b_aw.lock : '0) |
        ((gpu_32b_aw_to_scratch && gpu_32b_awvalid) ? gpu_32b_aw.lock : '0);
    assign scratch_axi_awcache = ((cpu_32b_aw_to_scratch && cpu_32b_awvalid) ? cpu_32b_aw.cache : '0) |
        ((dma_32b_aw_to_scratch && dma_32b_awvalid) ? dma_32b_aw.cache : '0) |
        ((gpu_32b_aw_to_scratch && gpu_32b_awvalid) ? gpu_32b_aw.cache : '0);
    assign scratch_axi_awprot = ((cpu_32b_aw_to_scratch && cpu_32b_awvalid) ? cpu_32b_aw.prot : '0) |
        ((dma_32b_aw_to_scratch && dma_32b_awvalid) ? dma_32b_aw.prot : '0) |
        ((gpu_32b_aw_to_scratch && gpu_32b_awvalid) ? gpu_32b_aw.prot : '0);
    assign scratch_axi_awvalid = ((cpu_32b_aw_to_scratch && cpu_32b_awvalid) ? cpu_32b_awvalid : '0) |
        ((dma_32b_aw_to_scratch && dma_32b_awvalid) ? dma_32b_awvalid : '0) |
        ((gpu_32b_aw_to_scratch && gpu_32b_awvalid) ? gpu_32b_awvalid : '0);

    // AW->W tracking FIFO: cpu -> scratch
    logic cpu_32b_w_to_scratch;
    logic [3:0] cpu_32b_aw_to_scratch_w_wptr, cpu_32b_aw_to_scratch_w_rptr;
    logic cpu_32b_aw_to_scratch_w_mem [16];
    logic cpu_32b_aw_to_scratch_w_push, cpu_32b_aw_to_scratch_w_pop;
    assign cpu_32b_aw_to_scratch_w_push = cpu_32b_awvalid && cpu_32b_awready && cpu_32b_aw_to_scratch;
    assign cpu_32b_aw_to_scratch_w_pop  = cpu_32b_wvalid && cpu_32b_wready && cpu_32b_w.last && cpu_32b_w_to_scratch;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            cpu_32b_aw_to_scratch_w_wptr <= '0;
            cpu_32b_aw_to_scratch_w_rptr <= '0;
        end else begin
            if (cpu_32b_aw_to_scratch_w_push) begin
                cpu_32b_aw_to_scratch_w_mem[cpu_32b_aw_to_scratch_w_wptr] <= 1'b1;
                cpu_32b_aw_to_scratch_w_wptr <= cpu_32b_aw_to_scratch_w_wptr + 1'b1;
            end
            if (cpu_32b_aw_to_scratch_w_pop) begin
                cpu_32b_aw_to_scratch_w_rptr <= cpu_32b_aw_to_scratch_w_rptr + 1'b1;
            end
        end
    end
    assign cpu_32b_w_to_scratch = (cpu_32b_aw_to_scratch_w_wptr != cpu_32b_aw_to_scratch_w_rptr) ? cpu_32b_aw_to_scratch_w_mem[cpu_32b_aw_to_scratch_w_rptr] : 1'b0;

    // AW->W tracking FIFO: dma -> scratch
    logic dma_32b_w_to_scratch;
    logic [3:0] dma_32b_aw_to_scratch_w_wptr, dma_32b_aw_to_scratch_w_rptr;
    logic dma_32b_aw_to_scratch_w_mem [16];
    logic dma_32b_aw_to_scratch_w_push, dma_32b_aw_to_scratch_w_pop;
    assign dma_32b_aw_to_scratch_w_push = dma_32b_awvalid && dma_32b_awready && dma_32b_aw_to_scratch;
    assign dma_32b_aw_to_scratch_w_pop  = dma_32b_wvalid && dma_32b_wready && dma_32b_w.last && dma_32b_w_to_scratch;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            dma_32b_aw_to_scratch_w_wptr <= '0;
            dma_32b_aw_to_scratch_w_rptr <= '0;
        end else begin
            if (dma_32b_aw_to_scratch_w_push) begin
                dma_32b_aw_to_scratch_w_mem[dma_32b_aw_to_scratch_w_wptr] <= 1'b1;
                dma_32b_aw_to_scratch_w_wptr <= dma_32b_aw_to_scratch_w_wptr + 1'b1;
            end
            if (dma_32b_aw_to_scratch_w_pop) begin
                dma_32b_aw_to_scratch_w_rptr <= dma_32b_aw_to_scratch_w_rptr + 1'b1;
            end
        end
    end
    assign dma_32b_w_to_scratch = (dma_32b_aw_to_scratch_w_wptr != dma_32b_aw_to_scratch_w_rptr) ? dma_32b_aw_to_scratch_w_mem[dma_32b_aw_to_scratch_w_rptr] : 1'b0;

    // AW->W tracking FIFO: gpu -> scratch
    logic gpu_32b_w_to_scratch;
    logic [3:0] gpu_32b_aw_to_scratch_w_wptr, gpu_32b_aw_to_scratch_w_rptr;
    logic gpu_32b_aw_to_scratch_w_mem [16];
    logic gpu_32b_aw_to_scratch_w_push, gpu_32b_aw_to_scratch_w_pop;
    assign gpu_32b_aw_to_scratch_w_push = gpu_32b_awvalid && gpu_32b_awready && gpu_32b_aw_to_scratch;
    assign gpu_32b_aw_to_scratch_w_pop  = gpu_32b_wvalid && gpu_32b_wready && gpu_32b_w.last && gpu_32b_w_to_scratch;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            gpu_32b_aw_to_scratch_w_wptr <= '0;
            gpu_32b_aw_to_scratch_w_rptr <= '0;
        end else begin
            if (gpu_32b_aw_to_scratch_w_push) begin
                gpu_32b_aw_to_scratch_w_mem[gpu_32b_aw_to_scratch_w_wptr] <= 1'b1;
                gpu_32b_aw_to_scratch_w_wptr <= gpu_32b_aw_to_scratch_w_wptr + 1'b1;
            end
            if (gpu_32b_aw_to_scratch_w_pop) begin
                gpu_32b_aw_to_scratch_w_rptr <= gpu_32b_aw_to_scratch_w_rptr + 1'b1;
            end
        end
    end
    assign gpu_32b_w_to_scratch = (gpu_32b_aw_to_scratch_w_wptr != gpu_32b_aw_to_scratch_w_rptr) ? gpu_32b_aw_to_scratch_w_mem[gpu_32b_aw_to_scratch_w_rptr] : 1'b0;

    // W channel (OR-merged across writing masters, gated by w_to_<slave> FIFO)
    assign scratch_axi_wdata = ((cpu_32b_w_to_scratch && cpu_32b_wvalid) ? cpu_32b_w.data : '0) |
        ((dma_32b_w_to_scratch && dma_32b_wvalid) ? dma_32b_w.data : '0) |
        ((gpu_32b_w_to_scratch && gpu_32b_wvalid) ? gpu_32b_w.data : '0);
    assign scratch_axi_wstrb = ((cpu_32b_w_to_scratch && cpu_32b_wvalid) ? cpu_32b_w.strb : '0) |
        ((dma_32b_w_to_scratch && dma_32b_wvalid) ? dma_32b_w.strb : '0) |
        ((gpu_32b_w_to_scratch && gpu_32b_wvalid) ? gpu_32b_w.strb : '0);
    assign scratch_axi_wlast = ((cpu_32b_w_to_scratch && cpu_32b_wvalid) ? cpu_32b_w.last : '0) |
        ((dma_32b_w_to_scratch && dma_32b_wvalid) ? dma_32b_w.last : '0) |
        ((gpu_32b_w_to_scratch && gpu_32b_wvalid) ? gpu_32b_w.last : '0);
    assign scratch_axi_wvalid = ((cpu_32b_w_to_scratch && cpu_32b_wvalid) ? cpu_32b_wvalid : '0) |
        ((dma_32b_w_to_scratch && dma_32b_wvalid) ? dma_32b_wvalid : '0) |
        ((gpu_32b_w_to_scratch && gpu_32b_wvalid) ? gpu_32b_wvalid : '0);

    // Bready (slave → owning master, by bid_bridge_id)
    assign scratch_axi_bready = ((scratch_axi_bid_bridge_id == 0) && scratch_axi_bid_valid ? cpu_32b_bready : '0) |
        ((scratch_axi_bid_bridge_id == 1) && scratch_axi_bid_valid ? dma_32b_bready : '0) |
        ((scratch_axi_bid_bridge_id == 2) && scratch_axi_bid_valid ? gpu_32b_bready : '0);

    // Bridge ID (writes) — picks the originating master's id
    assign scratch_axi_bridge_id_aw = ((cpu_32b_aw_to_scratch && cpu_32b_awvalid) ? cpu_bridge_id_aw : '0) |
        ((dma_32b_aw_to_scratch && dma_32b_awvalid) ? dma_bridge_id_aw : '0) |
        ((gpu_32b_aw_to_scratch && gpu_32b_awvalid) ? gpu_bridge_id_aw : '0);

    // AR channel (OR-merged across reading masters)
    assign scratch_axi_arid = ((cpu_32b_ar_to_scratch && cpu_32b_arvalid) ? cpu_32b_ar.id : '0) |
        ((dma_32b_ar_to_scratch && dma_32b_arvalid) ? dma_32b_ar.id : '0) |
        ((gpu_32b_ar_to_scratch && gpu_32b_arvalid) ? gpu_32b_ar.id : '0);
    assign scratch_axi_araddr = ((cpu_32b_ar_to_scratch && cpu_32b_arvalid) ? cpu_32b_ar.addr : '0) |
        ((dma_32b_ar_to_scratch && dma_32b_arvalid) ? dma_32b_ar.addr : '0) |
        ((gpu_32b_ar_to_scratch && gpu_32b_arvalid) ? gpu_32b_ar.addr : '0);
    assign scratch_axi_arlen = ((cpu_32b_ar_to_scratch && cpu_32b_arvalid) ? cpu_32b_ar.len : '0) |
        ((dma_32b_ar_to_scratch && dma_32b_arvalid) ? dma_32b_ar.len : '0) |
        ((gpu_32b_ar_to_scratch && gpu_32b_arvalid) ? gpu_32b_ar.len : '0);
    assign scratch_axi_arsize = ((cpu_32b_ar_to_scratch && cpu_32b_arvalid) ? cpu_32b_ar.size : '0) |
        ((dma_32b_ar_to_scratch && dma_32b_arvalid) ? dma_32b_ar.size : '0) |
        ((gpu_32b_ar_to_scratch && gpu_32b_arvalid) ? gpu_32b_ar.size : '0);
    assign scratch_axi_arburst = ((cpu_32b_ar_to_scratch && cpu_32b_arvalid) ? cpu_32b_ar.burst : '0) |
        ((dma_32b_ar_to_scratch && dma_32b_arvalid) ? dma_32b_ar.burst : '0) |
        ((gpu_32b_ar_to_scratch && gpu_32b_arvalid) ? gpu_32b_ar.burst : '0);
    assign scratch_axi_arlock = ((cpu_32b_ar_to_scratch && cpu_32b_arvalid) ? cpu_32b_ar.lock : '0) |
        ((dma_32b_ar_to_scratch && dma_32b_arvalid) ? dma_32b_ar.lock : '0) |
        ((gpu_32b_ar_to_scratch && gpu_32b_arvalid) ? gpu_32b_ar.lock : '0);
    assign scratch_axi_arcache = ((cpu_32b_ar_to_scratch && cpu_32b_arvalid) ? cpu_32b_ar.cache : '0) |
        ((dma_32b_ar_to_scratch && dma_32b_arvalid) ? dma_32b_ar.cache : '0) |
        ((gpu_32b_ar_to_scratch && gpu_32b_arvalid) ? gpu_32b_ar.cache : '0);
    assign scratch_axi_arprot = ((cpu_32b_ar_to_scratch && cpu_32b_arvalid) ? cpu_32b_ar.prot : '0) |
        ((dma_32b_ar_to_scratch && dma_32b_arvalid) ? dma_32b_ar.prot : '0) |
        ((gpu_32b_ar_to_scratch && gpu_32b_arvalid) ? gpu_32b_ar.prot : '0);
    assign scratch_axi_arvalid = ((cpu_32b_ar_to_scratch && cpu_32b_arvalid) ? cpu_32b_arvalid : '0) |
        ((dma_32b_ar_to_scratch && dma_32b_arvalid) ? dma_32b_arvalid : '0) |
        ((gpu_32b_ar_to_scratch && gpu_32b_arvalid) ? gpu_32b_arvalid : '0);

    // Rready (slave → owning master, by rid_bridge_id)
    assign scratch_axi_rready = ((scratch_axi_rid_bridge_id == 0) && scratch_axi_rid_valid ? cpu_32b_rready : '0) |
        ((scratch_axi_rid_bridge_id == 1) && scratch_axi_rid_valid ? dma_32b_rready : '0) |
        ((scratch_axi_rid_bridge_id == 2) && scratch_axi_rid_valid ? gpu_32b_rready : '0);

    // Bridge ID (reads) — picks the originating master's id
    assign scratch_axi_bridge_id_ar = ((cpu_32b_ar_to_scratch && cpu_32b_arvalid) ? cpu_bridge_id_ar : '0) |
        ((dma_32b_ar_to_scratch && dma_32b_arvalid) ? dma_bridge_id_ar : '0) |
        ((gpu_32b_ar_to_scratch && gpu_32b_arvalid) ? gpu_bridge_id_ar : '0);


    // ================================================================
    // Response MUXes (OR together all slave responses)
    // ================================================================

    // Master: cpu, Width path: 32b
    assign cpu_32b_awready = 
        (cpu_32b_aw_to_scratch ? scratch_axi_awready : '0);

    assign cpu_32b_wready = 
        (cpu_32b_w_to_scratch ? scratch_axi_wready : '0);

    assign cpu_32b_b.id = 
        ((scratch_axi_bid_bridge_id == 0) && scratch_axi_bid_valid ? scratch_axi_bid : '0);

    assign cpu_32b_b.resp = 
        ((scratch_axi_bid_bridge_id == 0) && scratch_axi_bid_valid ? scratch_axi_bresp : '0);

    assign cpu_32b_bvalid = 
        ((scratch_axi_bid_bridge_id == 0) && scratch_axi_bid_valid ? scratch_axi_bvalid : '0);

    assign cpu_32b_arready = 
        (cpu_32b_ar_to_scratch ? scratch_axi_arready : '0);

    assign cpu_32b_r.id = 
        ((scratch_axi_rid_bridge_id == 0) && scratch_axi_rid_valid ? scratch_axi_rid : '0);

    assign cpu_32b_r.data = 
        ((scratch_axi_rid_bridge_id == 0) && scratch_axi_rid_valid ? scratch_axi_rdata : 32'b0);

    assign cpu_32b_r.resp = 
        ((scratch_axi_rid_bridge_id == 0) && scratch_axi_rid_valid ? scratch_axi_rresp : '0);

    assign cpu_32b_r.last = 
        ((scratch_axi_rid_bridge_id == 0) && scratch_axi_rid_valid ? scratch_axi_rlast : '0);

    assign cpu_32b_rvalid = 
        ((scratch_axi_rid_bridge_id == 0) && scratch_axi_rid_valid ? scratch_axi_rvalid : '0);


    // Master: cpu, Width path: 64b
    assign cpu_64b_awready = 
        (cpu_64b_aw_to_sram ? sram_axi_awready : '0);

    assign cpu_64b_wready = 
        (cpu_64b_w_to_sram ? sram_axi_wready : '0);

    assign cpu_64b_b.id = 
        ((sram_axi_bid_bridge_id == 0) && sram_axi_bid_valid ? sram_axi_bid : '0);

    assign cpu_64b_b.resp = 
        ((sram_axi_bid_bridge_id == 0) && sram_axi_bid_valid ? sram_axi_bresp : '0);

    assign cpu_64b_bvalid = 
        ((sram_axi_bid_bridge_id == 0) && sram_axi_bid_valid ? sram_axi_bvalid : '0);

    assign cpu_64b_arready = 
        (cpu_64b_ar_to_sram ? sram_axi_arready : '0);

    assign cpu_64b_r.id = 
        ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? sram_axi_rid : '0);

    assign cpu_64b_r.data = 
        ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? sram_axi_rdata : 64'b0);

    assign cpu_64b_r.resp = 
        ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? sram_axi_rresp : '0);

    assign cpu_64b_r.last = 
        ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? sram_axi_rlast : '0);

    assign cpu_64b_rvalid = 
        ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? sram_axi_rvalid : '0);


    // Master: cpu, Width path: 128b
    assign cpu_128b_awready = 
        (cpu_128b_aw_to_ddr1 ? ddr1_axi_awready : '0);

    assign cpu_128b_wready = 
        (cpu_128b_w_to_ddr1 ? ddr1_axi_wready : '0);

    assign cpu_128b_b.id = 
        ((ddr1_axi_bid_bridge_id == 0) && ddr1_axi_bid_valid ? ddr1_axi_bid : '0);

    assign cpu_128b_b.resp = 
        ((ddr1_axi_bid_bridge_id == 0) && ddr1_axi_bid_valid ? ddr1_axi_bresp : '0);

    assign cpu_128b_bvalid = 
        ((ddr1_axi_bid_bridge_id == 0) && ddr1_axi_bid_valid ? ddr1_axi_bvalid : '0);

    assign cpu_128b_arready = 
        (cpu_128b_ar_to_ddr1 ? ddr1_axi_arready : '0);

    assign cpu_128b_r.id = 
        ((ddr1_axi_rid_bridge_id == 0) && ddr1_axi_rid_valid ? ddr1_axi_rid : '0);

    assign cpu_128b_r.data = 
        ((ddr1_axi_rid_bridge_id == 0) && ddr1_axi_rid_valid ? ddr1_axi_rdata : 128'b0);

    assign cpu_128b_r.resp = 
        ((ddr1_axi_rid_bridge_id == 0) && ddr1_axi_rid_valid ? ddr1_axi_rresp : '0);

    assign cpu_128b_r.last = 
        ((ddr1_axi_rid_bridge_id == 0) && ddr1_axi_rid_valid ? ddr1_axi_rlast : '0);

    assign cpu_128b_rvalid = 
        ((ddr1_axi_rid_bridge_id == 0) && ddr1_axi_rid_valid ? ddr1_axi_rvalid : '0);


    // Master: cpu, Width path: 256b
    assign cpu_256b_awready = 
        (cpu_256b_aw_to_ddr0 ? ddr0_axi_awready : '0);

    assign cpu_256b_wready = 
        (cpu_256b_w_to_ddr0 ? ddr0_axi_wready : '0);

    assign cpu_256b_b.id = 
        ((ddr0_axi_bid_bridge_id == 0) && ddr0_axi_bid_valid ? ddr0_axi_bid : '0);

    assign cpu_256b_b.resp = 
        ((ddr0_axi_bid_bridge_id == 0) && ddr0_axi_bid_valid ? ddr0_axi_bresp : '0);

    assign cpu_256b_bvalid = 
        ((ddr0_axi_bid_bridge_id == 0) && ddr0_axi_bid_valid ? ddr0_axi_bvalid : '0);

    assign cpu_256b_arready = 
        (cpu_256b_ar_to_ddr0 ? ddr0_axi_arready : '0);

    assign cpu_256b_r.id = 
        ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? ddr0_axi_rid : '0);

    assign cpu_256b_r.data = 
        ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? ddr0_axi_rdata : 256'b0);

    assign cpu_256b_r.resp = 
        ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? ddr0_axi_rresp : '0);

    assign cpu_256b_r.last = 
        ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? ddr0_axi_rlast : '0);

    assign cpu_256b_rvalid = 
        ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? ddr0_axi_rvalid : '0);


    // Master: dma, Width path: 32b
    assign dma_32b_awready = 
        (dma_32b_aw_to_scratch ? scratch_axi_awready : '0);

    assign dma_32b_wready = 
        (dma_32b_w_to_scratch ? scratch_axi_wready : '0);

    assign dma_32b_b.id = 
        ((scratch_axi_bid_bridge_id == 1) && scratch_axi_bid_valid ? scratch_axi_bid : '0);

    assign dma_32b_b.resp = 
        ((scratch_axi_bid_bridge_id == 1) && scratch_axi_bid_valid ? scratch_axi_bresp : '0);

    assign dma_32b_bvalid = 
        ((scratch_axi_bid_bridge_id == 1) && scratch_axi_bid_valid ? scratch_axi_bvalid : '0);

    assign dma_32b_arready = 
        (dma_32b_ar_to_scratch ? scratch_axi_arready : '0);

    assign dma_32b_r.id = 
        ((scratch_axi_rid_bridge_id == 1) && scratch_axi_rid_valid ? scratch_axi_rid : '0);

    assign dma_32b_r.data = 
        ((scratch_axi_rid_bridge_id == 1) && scratch_axi_rid_valid ? scratch_axi_rdata : 32'b0);

    assign dma_32b_r.resp = 
        ((scratch_axi_rid_bridge_id == 1) && scratch_axi_rid_valid ? scratch_axi_rresp : '0);

    assign dma_32b_r.last = 
        ((scratch_axi_rid_bridge_id == 1) && scratch_axi_rid_valid ? scratch_axi_rlast : '0);

    assign dma_32b_rvalid = 
        ((scratch_axi_rid_bridge_id == 1) && scratch_axi_rid_valid ? scratch_axi_rvalid : '0);


    // Master: dma, Width path: 64b
    assign dma_64b_awready = 
        (dma_64b_aw_to_sram ? sram_axi_awready : '0);

    assign dma_64b_wready = 
        (dma_64b_w_to_sram ? sram_axi_wready : '0);

    assign dma_64b_b.id = 
        ((sram_axi_bid_bridge_id == 1) && sram_axi_bid_valid ? sram_axi_bid : '0);

    assign dma_64b_b.resp = 
        ((sram_axi_bid_bridge_id == 1) && sram_axi_bid_valid ? sram_axi_bresp : '0);

    assign dma_64b_bvalid = 
        ((sram_axi_bid_bridge_id == 1) && sram_axi_bid_valid ? sram_axi_bvalid : '0);

    assign dma_64b_arready = 
        (dma_64b_ar_to_sram ? sram_axi_arready : '0);

    assign dma_64b_r.id = 
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? sram_axi_rid : '0);

    assign dma_64b_r.data = 
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? sram_axi_rdata : 64'b0);

    assign dma_64b_r.resp = 
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? sram_axi_rresp : '0);

    assign dma_64b_r.last = 
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? sram_axi_rlast : '0);

    assign dma_64b_rvalid = 
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? sram_axi_rvalid : '0);


    // Master: dma, Width path: 128b
    assign dma_128b_awready = 
        (dma_128b_aw_to_ddr1 ? ddr1_axi_awready : '0);

    assign dma_128b_wready = 
        (dma_128b_w_to_ddr1 ? ddr1_axi_wready : '0);

    assign dma_128b_b.id = 
        ((ddr1_axi_bid_bridge_id == 1) && ddr1_axi_bid_valid ? ddr1_axi_bid : '0);

    assign dma_128b_b.resp = 
        ((ddr1_axi_bid_bridge_id == 1) && ddr1_axi_bid_valid ? ddr1_axi_bresp : '0);

    assign dma_128b_bvalid = 
        ((ddr1_axi_bid_bridge_id == 1) && ddr1_axi_bid_valid ? ddr1_axi_bvalid : '0);

    assign dma_128b_arready = 
        (dma_128b_ar_to_ddr1 ? ddr1_axi_arready : '0);

    assign dma_128b_r.id = 
        ((ddr1_axi_rid_bridge_id == 1) && ddr1_axi_rid_valid ? ddr1_axi_rid : '0);

    assign dma_128b_r.data = 
        ((ddr1_axi_rid_bridge_id == 1) && ddr1_axi_rid_valid ? ddr1_axi_rdata : 128'b0);

    assign dma_128b_r.resp = 
        ((ddr1_axi_rid_bridge_id == 1) && ddr1_axi_rid_valid ? ddr1_axi_rresp : '0);

    assign dma_128b_r.last = 
        ((ddr1_axi_rid_bridge_id == 1) && ddr1_axi_rid_valid ? ddr1_axi_rlast : '0);

    assign dma_128b_rvalid = 
        ((ddr1_axi_rid_bridge_id == 1) && ddr1_axi_rid_valid ? ddr1_axi_rvalid : '0);


    // Master: dma, Width path: 256b
    assign dma_256b_awready = 
        (dma_256b_aw_to_ddr0 ? ddr0_axi_awready : '0);

    assign dma_256b_wready = 
        (dma_256b_w_to_ddr0 ? ddr0_axi_wready : '0);

    assign dma_256b_b.id = 
        ((ddr0_axi_bid_bridge_id == 1) && ddr0_axi_bid_valid ? ddr0_axi_bid : '0);

    assign dma_256b_b.resp = 
        ((ddr0_axi_bid_bridge_id == 1) && ddr0_axi_bid_valid ? ddr0_axi_bresp : '0);

    assign dma_256b_bvalid = 
        ((ddr0_axi_bid_bridge_id == 1) && ddr0_axi_bid_valid ? ddr0_axi_bvalid : '0);

    assign dma_256b_arready = 
        (dma_256b_ar_to_ddr0 ? ddr0_axi_arready : '0);

    assign dma_256b_r.id = 
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? ddr0_axi_rid : '0);

    assign dma_256b_r.data = 
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? ddr0_axi_rdata : 256'b0);

    assign dma_256b_r.resp = 
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? ddr0_axi_rresp : '0);

    assign dma_256b_r.last = 
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? ddr0_axi_rlast : '0);

    assign dma_256b_rvalid = 
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? ddr0_axi_rvalid : '0);


    // Master: gpu, Width path: 32b
    assign gpu_32b_awready = 
        (gpu_32b_aw_to_scratch ? scratch_axi_awready : '0);

    assign gpu_32b_wready = 
        (gpu_32b_w_to_scratch ? scratch_axi_wready : '0);

    assign gpu_32b_b.id = 
        ((scratch_axi_bid_bridge_id == 2) && scratch_axi_bid_valid ? scratch_axi_bid : '0);

    assign gpu_32b_b.resp = 
        ((scratch_axi_bid_bridge_id == 2) && scratch_axi_bid_valid ? scratch_axi_bresp : '0);

    assign gpu_32b_bvalid = 
        ((scratch_axi_bid_bridge_id == 2) && scratch_axi_bid_valid ? scratch_axi_bvalid : '0);

    assign gpu_32b_arready = 
        (gpu_32b_ar_to_scratch ? scratch_axi_arready : '0);

    assign gpu_32b_r.id = 
        ((scratch_axi_rid_bridge_id == 2) && scratch_axi_rid_valid ? scratch_axi_rid : '0);

    assign gpu_32b_r.data = 
        ((scratch_axi_rid_bridge_id == 2) && scratch_axi_rid_valid ? scratch_axi_rdata : 32'b0);

    assign gpu_32b_r.resp = 
        ((scratch_axi_rid_bridge_id == 2) && scratch_axi_rid_valid ? scratch_axi_rresp : '0);

    assign gpu_32b_r.last = 
        ((scratch_axi_rid_bridge_id == 2) && scratch_axi_rid_valid ? scratch_axi_rlast : '0);

    assign gpu_32b_rvalid = 
        ((scratch_axi_rid_bridge_id == 2) && scratch_axi_rid_valid ? scratch_axi_rvalid : '0);


    // Master: gpu, Width path: 128b
    assign gpu_128b_awready = 
        (gpu_128b_aw_to_ddr1 ? ddr1_axi_awready : '0);

    assign gpu_128b_wready = 
        (gpu_128b_w_to_ddr1 ? ddr1_axi_wready : '0);

    assign gpu_128b_b.id = 
        ((ddr1_axi_bid_bridge_id == 2) && ddr1_axi_bid_valid ? ddr1_axi_bid : '0);

    assign gpu_128b_b.resp = 
        ((ddr1_axi_bid_bridge_id == 2) && ddr1_axi_bid_valid ? ddr1_axi_bresp : '0);

    assign gpu_128b_bvalid = 
        ((ddr1_axi_bid_bridge_id == 2) && ddr1_axi_bid_valid ? ddr1_axi_bvalid : '0);

    assign gpu_128b_arready = 
        (gpu_128b_ar_to_ddr1 ? ddr1_axi_arready : '0);

    assign gpu_128b_r.id = 
        ((ddr1_axi_rid_bridge_id == 2) && ddr1_axi_rid_valid ? ddr1_axi_rid : '0);

    assign gpu_128b_r.data = 
        ((ddr1_axi_rid_bridge_id == 2) && ddr1_axi_rid_valid ? ddr1_axi_rdata : 128'b0);

    assign gpu_128b_r.resp = 
        ((ddr1_axi_rid_bridge_id == 2) && ddr1_axi_rid_valid ? ddr1_axi_rresp : '0);

    assign gpu_128b_r.last = 
        ((ddr1_axi_rid_bridge_id == 2) && ddr1_axi_rid_valid ? ddr1_axi_rlast : '0);

    assign gpu_128b_rvalid = 
        ((ddr1_axi_rid_bridge_id == 2) && ddr1_axi_rid_valid ? ddr1_axi_rvalid : '0);


    // Master: gpu, Width path: 256b
    assign gpu_256b_awready = 
        (gpu_256b_aw_to_ddr0 ? ddr0_axi_awready : '0);

    assign gpu_256b_wready = 
        (gpu_256b_w_to_ddr0 ? ddr0_axi_wready : '0);

    assign gpu_256b_b.id = 
        ((ddr0_axi_bid_bridge_id == 2) && ddr0_axi_bid_valid ? ddr0_axi_bid : '0);

    assign gpu_256b_b.resp = 
        ((ddr0_axi_bid_bridge_id == 2) && ddr0_axi_bid_valid ? ddr0_axi_bresp : '0);

    assign gpu_256b_bvalid = 
        ((ddr0_axi_bid_bridge_id == 2) && ddr0_axi_bid_valid ? ddr0_axi_bvalid : '0);

    assign gpu_256b_arready = 
        (gpu_256b_ar_to_ddr0 ? ddr0_axi_arready : '0);

    assign gpu_256b_r.id = 
        ((ddr0_axi_rid_bridge_id == 2) && ddr0_axi_rid_valid ? ddr0_axi_rid : '0);

    assign gpu_256b_r.data = 
        ((ddr0_axi_rid_bridge_id == 2) && ddr0_axi_rid_valid ? ddr0_axi_rdata : 256'b0);

    assign gpu_256b_r.resp = 
        ((ddr0_axi_rid_bridge_id == 2) && ddr0_axi_rid_valid ? ddr0_axi_rresp : '0);

    assign gpu_256b_r.last = 
        ((ddr0_axi_rid_bridge_id == 2) && ddr0_axi_rid_valid ? ddr0_axi_rlast : '0);

    assign gpu_256b_rvalid = 
        ((ddr0_axi_rid_bridge_id == 2) && ddr0_axi_rid_valid ? ddr0_axi_rvalid : '0);


    // Master: vpu, Width path: 128b
    assign vpu_128b_awready = 
        (vpu_128b_aw_to_ddr1 ? ddr1_axi_awready : '0);

    assign vpu_128b_wready = 
        (vpu_128b_w_to_ddr1 ? ddr1_axi_wready : '0);

    assign vpu_128b_b.id = 
        ((ddr1_axi_bid_bridge_id == 3) && ddr1_axi_bid_valid ? ddr1_axi_bid : '0);

    assign vpu_128b_b.resp = 
        ((ddr1_axi_bid_bridge_id == 3) && ddr1_axi_bid_valid ? ddr1_axi_bresp : '0);

    assign vpu_128b_bvalid = 
        ((ddr1_axi_bid_bridge_id == 3) && ddr1_axi_bid_valid ? ddr1_axi_bvalid : '0);

    assign vpu_128b_arready = 
        (vpu_128b_ar_to_ddr1 ? ddr1_axi_arready : '0);

    assign vpu_128b_r.id = 
        ((ddr1_axi_rid_bridge_id == 3) && ddr1_axi_rid_valid ? ddr1_axi_rid : '0);

    assign vpu_128b_r.data = 
        ((ddr1_axi_rid_bridge_id == 3) && ddr1_axi_rid_valid ? ddr1_axi_rdata : 128'b0);

    assign vpu_128b_r.resp = 
        ((ddr1_axi_rid_bridge_id == 3) && ddr1_axi_rid_valid ? ddr1_axi_rresp : '0);

    assign vpu_128b_r.last = 
        ((ddr1_axi_rid_bridge_id == 3) && ddr1_axi_rid_valid ? ddr1_axi_rlast : '0);

    assign vpu_128b_rvalid = 
        ((ddr1_axi_rid_bridge_id == 3) && ddr1_axi_rid_valid ? ddr1_axi_rvalid : '0);


    // Master: vpu, Width path: 256b
    assign vpu_256b_awready = 
        (vpu_256b_aw_to_ddr0 ? ddr0_axi_awready : '0);

    assign vpu_256b_wready = 
        (vpu_256b_w_to_ddr0 ? ddr0_axi_wready : '0);

    assign vpu_256b_b.id = 
        ((ddr0_axi_bid_bridge_id == 3) && ddr0_axi_bid_valid ? ddr0_axi_bid : '0);

    assign vpu_256b_b.resp = 
        ((ddr0_axi_bid_bridge_id == 3) && ddr0_axi_bid_valid ? ddr0_axi_bresp : '0);

    assign vpu_256b_bvalid = 
        ((ddr0_axi_bid_bridge_id == 3) && ddr0_axi_bid_valid ? ddr0_axi_bvalid : '0);

    assign vpu_256b_arready = 
        (vpu_256b_ar_to_ddr0 ? ddr0_axi_arready : '0);

    assign vpu_256b_r.id = 
        ((ddr0_axi_rid_bridge_id == 3) && ddr0_axi_rid_valid ? ddr0_axi_rid : '0);

    assign vpu_256b_r.data = 
        ((ddr0_axi_rid_bridge_id == 3) && ddr0_axi_rid_valid ? ddr0_axi_rdata : 256'b0);

    assign vpu_256b_r.resp = 
        ((ddr0_axi_rid_bridge_id == 3) && ddr0_axi_rid_valid ? ddr0_axi_rresp : '0);

    assign vpu_256b_r.last = 
        ((ddr0_axi_rid_bridge_id == 3) && ddr0_axi_rid_valid ? ddr0_axi_rlast : '0);

    assign vpu_256b_rvalid = 
        ((ddr0_axi_rid_bridge_id == 3) && ddr0_axi_rid_valid ? ddr0_axi_rvalid : '0);


endmodule : bridge_a_axi4_widthmix_4x4_xbar
