// Crossbar: bridge_b_axi4_axil_3x5_xbar
// Generated by: CrossbarGenerator
// 
// Routes width-adapted signals from adapters to slaves.
// Selects correct width path based on address decode.

`timescale 1ns / 1ps

import bridge_b_axi4_axil_3x5_pkg::*;

module bridge_b_axi4_axil_3x5_xbar (
    input  logic aclk,
    input  logic aresetn,

    // cpu_axi4 adapter outputs (multiple width paths)
    input  logic [NUM_SLAVES-1:0] cpu_axi4_slave_select_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] cpu_axi4_bridge_id_aw,
    input  logic [NUM_SLAVES-1:0] cpu_axi4_slave_select_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] cpu_axi4_bridge_id_ar,
    // 32b path
    input  axi4_aw_t     cpu_axi4_32b_aw,
    input  logic         cpu_axi4_32b_awvalid,
    output logic         cpu_axi4_32b_awready,
    input  axi4_w_32b_t  cpu_axi4_32b_w,
    input  logic         cpu_axi4_32b_wvalid,
    output logic         cpu_axi4_32b_wready,
    output axi4_b_t      cpu_axi4_32b_b,
    output logic         cpu_axi4_32b_bvalid,
    input  logic         cpu_axi4_32b_bready,
    input  axi4_ar_t     cpu_axi4_32b_ar,
    input  logic         cpu_axi4_32b_arvalid,
    output logic         cpu_axi4_32b_arready,
    output axi4_r_32b_t  cpu_axi4_32b_r,
    output logic         cpu_axi4_32b_rvalid,
    input  logic         cpu_axi4_32b_rready,
    // 64b path
    input  axi4_aw_t     cpu_axi4_64b_aw,
    input  logic         cpu_axi4_64b_awvalid,
    output logic         cpu_axi4_64b_awready,
    input  axi4_w_64b_t  cpu_axi4_64b_w,
    input  logic         cpu_axi4_64b_wvalid,
    output logic         cpu_axi4_64b_wready,
    output axi4_b_t      cpu_axi4_64b_b,
    output logic         cpu_axi4_64b_bvalid,
    input  logic         cpu_axi4_64b_bready,
    input  axi4_ar_t     cpu_axi4_64b_ar,
    input  logic         cpu_axi4_64b_arvalid,
    output logic         cpu_axi4_64b_arready,
    output axi4_r_64b_t  cpu_axi4_64b_r,
    output logic         cpu_axi4_64b_rvalid,
    input  logic         cpu_axi4_64b_rready,
    // 128b path
    input  axi4_aw_t     cpu_axi4_128b_aw,
    input  logic         cpu_axi4_128b_awvalid,
    output logic         cpu_axi4_128b_awready,
    input  axi4_w_128b_t  cpu_axi4_128b_w,
    input  logic         cpu_axi4_128b_wvalid,
    output logic         cpu_axi4_128b_wready,
    output axi4_b_t      cpu_axi4_128b_b,
    output logic         cpu_axi4_128b_bvalid,
    input  logic         cpu_axi4_128b_bready,
    input  axi4_ar_t     cpu_axi4_128b_ar,
    input  logic         cpu_axi4_128b_arvalid,
    output logic         cpu_axi4_128b_arready,
    output axi4_r_128b_t  cpu_axi4_128b_r,
    output logic         cpu_axi4_128b_rvalid,
    input  logic         cpu_axi4_128b_rready,

    // dma_axi4 adapter outputs (multiple width paths)
    input  logic [NUM_SLAVES-1:0] dma_axi4_slave_select_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] dma_axi4_bridge_id_aw,
    input  logic [NUM_SLAVES-1:0] dma_axi4_slave_select_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] dma_axi4_bridge_id_ar,
    // 32b path
    input  axi4_aw_t     dma_axi4_32b_aw,
    input  logic         dma_axi4_32b_awvalid,
    output logic         dma_axi4_32b_awready,
    input  axi4_w_32b_t  dma_axi4_32b_w,
    input  logic         dma_axi4_32b_wvalid,
    output logic         dma_axi4_32b_wready,
    output axi4_b_t      dma_axi4_32b_b,
    output logic         dma_axi4_32b_bvalid,
    input  logic         dma_axi4_32b_bready,
    input  axi4_ar_t     dma_axi4_32b_ar,
    input  logic         dma_axi4_32b_arvalid,
    output logic         dma_axi4_32b_arready,
    output axi4_r_32b_t  dma_axi4_32b_r,
    output logic         dma_axi4_32b_rvalid,
    input  logic         dma_axi4_32b_rready,
    // 64b path
    input  axi4_aw_t     dma_axi4_64b_aw,
    input  logic         dma_axi4_64b_awvalid,
    output logic         dma_axi4_64b_awready,
    input  axi4_w_64b_t  dma_axi4_64b_w,
    input  logic         dma_axi4_64b_wvalid,
    output logic         dma_axi4_64b_wready,
    output axi4_b_t      dma_axi4_64b_b,
    output logic         dma_axi4_64b_bvalid,
    input  logic         dma_axi4_64b_bready,
    input  axi4_ar_t     dma_axi4_64b_ar,
    input  logic         dma_axi4_64b_arvalid,
    output logic         dma_axi4_64b_arready,
    output axi4_r_64b_t  dma_axi4_64b_r,
    output logic         dma_axi4_64b_rvalid,
    input  logic         dma_axi4_64b_rready,
    // 128b path
    input  axi4_aw_t     dma_axi4_128b_aw,
    input  logic         dma_axi4_128b_awvalid,
    output logic         dma_axi4_128b_awready,
    input  axi4_w_128b_t  dma_axi4_128b_w,
    input  logic         dma_axi4_128b_wvalid,
    output logic         dma_axi4_128b_wready,
    output axi4_b_t      dma_axi4_128b_b,
    output logic         dma_axi4_128b_bvalid,
    input  logic         dma_axi4_128b_bready,
    input  axi4_ar_t     dma_axi4_128b_ar,
    input  logic         dma_axi4_128b_arvalid,
    output logic         dma_axi4_128b_arready,
    output axi4_r_128b_t  dma_axi4_128b_r,
    output logic         dma_axi4_128b_rvalid,
    input  logic         dma_axi4_128b_rready,

    // host_axil adapter outputs (multiple width paths)
    input  logic [NUM_SLAVES-1:0] host_axil_slave_select_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] host_axil_bridge_id_aw,
    input  logic [NUM_SLAVES-1:0] host_axil_slave_select_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] host_axil_bridge_id_ar,
    // 32b path
    input  axi4_aw_t     host_axil_32b_aw,
    input  logic         host_axil_32b_awvalid,
    output logic         host_axil_32b_awready,
    input  axi4_w_32b_t  host_axil_32b_w,
    input  logic         host_axil_32b_wvalid,
    output logic         host_axil_32b_wready,
    output axi4_b_t      host_axil_32b_b,
    output logic         host_axil_32b_bvalid,
    input  logic         host_axil_32b_bready,
    input  axi4_ar_t     host_axil_32b_ar,
    input  logic         host_axil_32b_arvalid,
    output logic         host_axil_32b_arready,
    output axi4_r_32b_t  host_axil_32b_r,
    output logic         host_axil_32b_rvalid,
    input  logic         host_axil_32b_rready,
    // 64b path
    input  axi4_aw_t     host_axil_64b_aw,
    input  logic         host_axil_64b_awvalid,
    output logic         host_axil_64b_awready,
    input  axi4_w_64b_t  host_axil_64b_w,
    input  logic         host_axil_64b_wvalid,
    output logic         host_axil_64b_wready,
    output axi4_b_t      host_axil_64b_b,
    output logic         host_axil_64b_bvalid,
    input  logic         host_axil_64b_bready,
    input  axi4_ar_t     host_axil_64b_ar,
    input  logic         host_axil_64b_arvalid,
    output logic         host_axil_64b_arready,
    output axi4_r_64b_t  host_axil_64b_r,
    output logic         host_axil_64b_rvalid,
    input  logic         host_axil_64b_rready,

    // Slave 0: ddr0
    output logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_bridge_id_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_bid_bridge_id,
    input  logic                       ddr0_axi_bid_valid,

    output logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_bridge_id_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_rid_bridge_id,
    input  logic                       ddr0_axi_rid_valid,

    output  logic [3:0]  ddr0_axi_awid,
    output  logic [31:0]  ddr0_axi_awaddr,
    output  logic [7:0]  ddr0_axi_awlen,
    output  logic [2:0]  ddr0_axi_awsize,
    output  logic [1:0]  ddr0_axi_awburst,
    output  logic         ddr0_axi_awlock,
    output  logic [3:0]  ddr0_axi_awcache,
    output  logic [2:0]  ddr0_axi_awprot,
    output  logic [3:0]  ddr0_axi_awqos,
    output  logic [3:0]  ddr0_axi_awregion,
    output  logic         ddr0_axi_awuser,
    output  logic         ddr0_axi_awvalid,
    input  logic         ddr0_axi_awready,

    output  logic [127:0]  ddr0_axi_wdata,
    output  logic [15:0]  ddr0_axi_wstrb,
    output  logic         ddr0_axi_wlast,
    output  logic         ddr0_axi_wuser,
    output  logic         ddr0_axi_wvalid,
    input  logic         ddr0_axi_wready,

    input  logic [3:0]  ddr0_axi_bid,
    input  logic [1:0]  ddr0_axi_bresp,
    input  logic         ddr0_axi_buser,
    input  logic         ddr0_axi_bvalid,
    output  logic         ddr0_axi_bready,

    output  logic [3:0]  ddr0_axi_arid,
    output  logic [31:0]  ddr0_axi_araddr,
    output  logic [7:0]  ddr0_axi_arlen,
    output  logic [2:0]  ddr0_axi_arsize,
    output  logic [1:0]  ddr0_axi_arburst,
    output  logic         ddr0_axi_arlock,
    output  logic [3:0]  ddr0_axi_arcache,
    output  logic [2:0]  ddr0_axi_arprot,
    output  logic [3:0]  ddr0_axi_arqos,
    output  logic [3:0]  ddr0_axi_arregion,
    output  logic         ddr0_axi_aruser,
    output  logic         ddr0_axi_arvalid,
    input  logic         ddr0_axi_arready,

    input  logic [3:0]  ddr0_axi_rid,
    input  logic [127:0]  ddr0_axi_rdata,
    input  logic [1:0]  ddr0_axi_rresp,
    input  logic         ddr0_axi_rlast,
    input  logic         ddr0_axi_ruser,
    input  logic         ddr0_axi_rvalid,
    output  logic         ddr0_axi_rready,

    // Slave 1: sram
    output logic [BRIDGE_ID_WIDTH-1:0] sram_axi_bridge_id_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] sram_axi_bid_bridge_id,
    input  logic                       sram_axi_bid_valid,

    output logic [BRIDGE_ID_WIDTH-1:0] sram_axi_bridge_id_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] sram_axi_rid_bridge_id,
    input  logic                       sram_axi_rid_valid,

    output  logic [3:0]  sram_axi_awid,
    output  logic [31:0]  sram_axi_awaddr,
    output  logic [7:0]  sram_axi_awlen,
    output  logic [2:0]  sram_axi_awsize,
    output  logic [1:0]  sram_axi_awburst,
    output  logic         sram_axi_awlock,
    output  logic [3:0]  sram_axi_awcache,
    output  logic [2:0]  sram_axi_awprot,
    output  logic [3:0]  sram_axi_awqos,
    output  logic [3:0]  sram_axi_awregion,
    output  logic         sram_axi_awuser,
    output  logic         sram_axi_awvalid,
    input  logic         sram_axi_awready,

    output  logic [63:0]  sram_axi_wdata,
    output  logic [7:0]  sram_axi_wstrb,
    output  logic         sram_axi_wlast,
    output  logic         sram_axi_wuser,
    output  logic         sram_axi_wvalid,
    input  logic         sram_axi_wready,

    input  logic [3:0]  sram_axi_bid,
    input  logic [1:0]  sram_axi_bresp,
    input  logic         sram_axi_buser,
    input  logic         sram_axi_bvalid,
    output  logic         sram_axi_bready,

    output  logic [3:0]  sram_axi_arid,
    output  logic [31:0]  sram_axi_araddr,
    output  logic [7:0]  sram_axi_arlen,
    output  logic [2:0]  sram_axi_arsize,
    output  logic [1:0]  sram_axi_arburst,
    output  logic         sram_axi_arlock,
    output  logic [3:0]  sram_axi_arcache,
    output  logic [2:0]  sram_axi_arprot,
    output  logic [3:0]  sram_axi_arqos,
    output  logic [3:0]  sram_axi_arregion,
    output  logic         sram_axi_aruser,
    output  logic         sram_axi_arvalid,
    input  logic         sram_axi_arready,

    input  logic [3:0]  sram_axi_rid,
    input  logic [63:0]  sram_axi_rdata,
    input  logic [1:0]  sram_axi_rresp,
    input  logic         sram_axi_rlast,
    input  logic         sram_axi_ruser,
    input  logic         sram_axi_rvalid,
    output  logic         sram_axi_rready,

    // Slave 2: axil_periph0
    output logic [BRIDGE_ID_WIDTH-1:0] axil_periph0_axi_bridge_id_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] axil_periph0_axi_bid_bridge_id,
    input  logic                       axil_periph0_axi_bid_valid,

    output logic [BRIDGE_ID_WIDTH-1:0] axil_periph0_axi_bridge_id_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] axil_periph0_axi_rid_bridge_id,
    input  logic                       axil_periph0_axi_rid_valid,

    output  logic [3:0]  axil_periph0_axi_awid,
    output  logic [31:0]  axil_periph0_axi_awaddr,
    output  logic [7:0]  axil_periph0_axi_awlen,
    output  logic [2:0]  axil_periph0_axi_awsize,
    output  logic [1:0]  axil_periph0_axi_awburst,
    output  logic         axil_periph0_axi_awlock,
    output  logic [3:0]  axil_periph0_axi_awcache,
    output  logic [2:0]  axil_periph0_axi_awprot,
    output  logic [3:0]  axil_periph0_axi_awqos,
    output  logic [3:0]  axil_periph0_axi_awregion,
    output  logic         axil_periph0_axi_awuser,
    output  logic         axil_periph0_axi_awvalid,
    input  logic         axil_periph0_axi_awready,

    output  logic [31:0]  axil_periph0_axi_wdata,
    output  logic [3:0]  axil_periph0_axi_wstrb,
    output  logic         axil_periph0_axi_wlast,
    output  logic         axil_periph0_axi_wuser,
    output  logic         axil_periph0_axi_wvalid,
    input  logic         axil_periph0_axi_wready,

    input  logic [3:0]  axil_periph0_axi_bid,
    input  logic [1:0]  axil_periph0_axi_bresp,
    input  logic         axil_periph0_axi_buser,
    input  logic         axil_periph0_axi_bvalid,
    output  logic         axil_periph0_axi_bready,

    output  logic [3:0]  axil_periph0_axi_arid,
    output  logic [31:0]  axil_periph0_axi_araddr,
    output  logic [7:0]  axil_periph0_axi_arlen,
    output  logic [2:0]  axil_periph0_axi_arsize,
    output  logic [1:0]  axil_periph0_axi_arburst,
    output  logic         axil_periph0_axi_arlock,
    output  logic [3:0]  axil_periph0_axi_arcache,
    output  logic [2:0]  axil_periph0_axi_arprot,
    output  logic [3:0]  axil_periph0_axi_arqos,
    output  logic [3:0]  axil_periph0_axi_arregion,
    output  logic         axil_periph0_axi_aruser,
    output  logic         axil_periph0_axi_arvalid,
    input  logic         axil_periph0_axi_arready,

    input  logic [3:0]  axil_periph0_axi_rid,
    input  logic [31:0]  axil_periph0_axi_rdata,
    input  logic [1:0]  axil_periph0_axi_rresp,
    input  logic         axil_periph0_axi_rlast,
    input  logic         axil_periph0_axi_ruser,
    input  logic         axil_periph0_axi_rvalid,
    output  logic         axil_periph0_axi_rready,

    // Slave 3: axil_periph1
    output logic [BRIDGE_ID_WIDTH-1:0] axil_periph1_axi_bridge_id_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] axil_periph1_axi_bid_bridge_id,
    input  logic                       axil_periph1_axi_bid_valid,

    output logic [BRIDGE_ID_WIDTH-1:0] axil_periph1_axi_bridge_id_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] axil_periph1_axi_rid_bridge_id,
    input  logic                       axil_periph1_axi_rid_valid,

    output  logic [3:0]  axil_periph1_axi_awid,
    output  logic [31:0]  axil_periph1_axi_awaddr,
    output  logic [7:0]  axil_periph1_axi_awlen,
    output  logic [2:0]  axil_periph1_axi_awsize,
    output  logic [1:0]  axil_periph1_axi_awburst,
    output  logic         axil_periph1_axi_awlock,
    output  logic [3:0]  axil_periph1_axi_awcache,
    output  logic [2:0]  axil_periph1_axi_awprot,
    output  logic [3:0]  axil_periph1_axi_awqos,
    output  logic [3:0]  axil_periph1_axi_awregion,
    output  logic         axil_periph1_axi_awuser,
    output  logic         axil_periph1_axi_awvalid,
    input  logic         axil_periph1_axi_awready,

    output  logic [31:0]  axil_periph1_axi_wdata,
    output  logic [3:0]  axil_periph1_axi_wstrb,
    output  logic         axil_periph1_axi_wlast,
    output  logic         axil_periph1_axi_wuser,
    output  logic         axil_periph1_axi_wvalid,
    input  logic         axil_periph1_axi_wready,

    input  logic [3:0]  axil_periph1_axi_bid,
    input  logic [1:0]  axil_periph1_axi_bresp,
    input  logic         axil_periph1_axi_buser,
    input  logic         axil_periph1_axi_bvalid,
    output  logic         axil_periph1_axi_bready,

    output  logic [3:0]  axil_periph1_axi_arid,
    output  logic [31:0]  axil_periph1_axi_araddr,
    output  logic [7:0]  axil_periph1_axi_arlen,
    output  logic [2:0]  axil_periph1_axi_arsize,
    output  logic [1:0]  axil_periph1_axi_arburst,
    output  logic         axil_periph1_axi_arlock,
    output  logic [3:0]  axil_periph1_axi_arcache,
    output  logic [2:0]  axil_periph1_axi_arprot,
    output  logic [3:0]  axil_periph1_axi_arqos,
    output  logic [3:0]  axil_periph1_axi_arregion,
    output  logic         axil_periph1_axi_aruser,
    output  logic         axil_periph1_axi_arvalid,
    input  logic         axil_periph1_axi_arready,

    input  logic [3:0]  axil_periph1_axi_rid,
    input  logic [31:0]  axil_periph1_axi_rdata,
    input  logic [1:0]  axil_periph1_axi_rresp,
    input  logic         axil_periph1_axi_rlast,
    input  logic         axil_periph1_axi_ruser,
    input  logic         axil_periph1_axi_rvalid,
    output  logic         axil_periph1_axi_rready,

    // Slave 4: apb_periph0
    output logic [BRIDGE_ID_WIDTH-1:0] apb_periph0_axi_bridge_id_aw,
    input  logic [BRIDGE_ID_WIDTH-1:0] apb_periph0_axi_bid_bridge_id,
    input  logic                       apb_periph0_axi_bid_valid,

    output logic [BRIDGE_ID_WIDTH-1:0] apb_periph0_axi_bridge_id_ar,
    input  logic [BRIDGE_ID_WIDTH-1:0] apb_periph0_axi_rid_bridge_id,
    input  logic                       apb_periph0_axi_rid_valid,

    output  logic [3:0]  apb_periph0_axi_awid,
    output  logic [31:0]  apb_periph0_axi_awaddr,
    output  logic [7:0]  apb_periph0_axi_awlen,
    output  logic [2:0]  apb_periph0_axi_awsize,
    output  logic [1:0]  apb_periph0_axi_awburst,
    output  logic         apb_periph0_axi_awlock,
    output  logic [3:0]  apb_periph0_axi_awcache,
    output  logic [2:0]  apb_periph0_axi_awprot,
    output  logic [3:0]  apb_periph0_axi_awqos,
    output  logic [3:0]  apb_periph0_axi_awregion,
    output  logic         apb_periph0_axi_awuser,
    output  logic         apb_periph0_axi_awvalid,
    input  logic         apb_periph0_axi_awready,

    output  logic [31:0]  apb_periph0_axi_wdata,
    output  logic [3:0]  apb_periph0_axi_wstrb,
    output  logic         apb_periph0_axi_wlast,
    output  logic         apb_periph0_axi_wuser,
    output  logic         apb_periph0_axi_wvalid,
    input  logic         apb_periph0_axi_wready,

    input  logic [3:0]  apb_periph0_axi_bid,
    input  logic [1:0]  apb_periph0_axi_bresp,
    input  logic         apb_periph0_axi_buser,
    input  logic         apb_periph0_axi_bvalid,
    output  logic         apb_periph0_axi_bready,

    output  logic [3:0]  apb_periph0_axi_arid,
    output  logic [31:0]  apb_periph0_axi_araddr,
    output  logic [7:0]  apb_periph0_axi_arlen,
    output  logic [2:0]  apb_periph0_axi_arsize,
    output  logic [1:0]  apb_periph0_axi_arburst,
    output  logic         apb_periph0_axi_arlock,
    output  logic [3:0]  apb_periph0_axi_arcache,
    output  logic [2:0]  apb_periph0_axi_arprot,
    output  logic [3:0]  apb_periph0_axi_arqos,
    output  logic [3:0]  apb_periph0_axi_arregion,
    output  logic         apb_periph0_axi_aruser,
    output  logic         apb_periph0_axi_arvalid,
    input  logic         apb_periph0_axi_arready,

    input  logic [3:0]  apb_periph0_axi_rid,
    input  logic [31:0]  apb_periph0_axi_rdata,
    input  logic [1:0]  apb_periph0_axi_rresp,
    input  logic         apb_periph0_axi_rlast,
    input  logic         apb_periph0_axi_ruser,
    input  logic         apb_periph0_axi_rvalid,
    output  logic         apb_periph0_axi_rready
);

    // ================================================================
    // Crossbar Routing
    // ================================================================
    localparam NUM_SLAVES = 5;

    // ================================================================
    // Slave 0: ddr0 (128b)
    // ================================================================
    // Multi-master (2 masters) → ddr0
    //   - cpu_axi4 (rw)
    //   - dma_axi4 (rw)

    wire cpu_axi4_128b_aw_to_ddr0 = (cpu_axi4_128b_aw.addr <= 32'h3fffffff);
    wire cpu_axi4_128b_ar_to_ddr0 = (cpu_axi4_128b_ar.addr <= 32'h3fffffff);
    wire dma_axi4_128b_aw_to_ddr0 = (dma_axi4_128b_aw.addr <= 32'h3fffffff);
    wire dma_axi4_128b_ar_to_ddr0 = (dma_axi4_128b_ar.addr <= 32'h3fffffff);

    // AW channel (OR-merged across writing masters)
    assign ddr0_axi_awid = ((cpu_axi4_128b_aw_to_ddr0 && cpu_axi4_128b_awvalid) ? cpu_axi4_128b_aw.id : '0) |
        ((dma_axi4_128b_aw_to_ddr0 && dma_axi4_128b_awvalid) ? dma_axi4_128b_aw.id : '0);
    assign ddr0_axi_awaddr = ((cpu_axi4_128b_aw_to_ddr0 && cpu_axi4_128b_awvalid) ? cpu_axi4_128b_aw.addr : '0) |
        ((dma_axi4_128b_aw_to_ddr0 && dma_axi4_128b_awvalid) ? dma_axi4_128b_aw.addr : '0);
    assign ddr0_axi_awlen = ((cpu_axi4_128b_aw_to_ddr0 && cpu_axi4_128b_awvalid) ? cpu_axi4_128b_aw.len : '0) |
        ((dma_axi4_128b_aw_to_ddr0 && dma_axi4_128b_awvalid) ? dma_axi4_128b_aw.len : '0);
    assign ddr0_axi_awsize = ((cpu_axi4_128b_aw_to_ddr0 && cpu_axi4_128b_awvalid) ? cpu_axi4_128b_aw.size : '0) |
        ((dma_axi4_128b_aw_to_ddr0 && dma_axi4_128b_awvalid) ? dma_axi4_128b_aw.size : '0);
    assign ddr0_axi_awburst = ((cpu_axi4_128b_aw_to_ddr0 && cpu_axi4_128b_awvalid) ? cpu_axi4_128b_aw.burst : '0) |
        ((dma_axi4_128b_aw_to_ddr0 && dma_axi4_128b_awvalid) ? dma_axi4_128b_aw.burst : '0);
    assign ddr0_axi_awlock = ((cpu_axi4_128b_aw_to_ddr0 && cpu_axi4_128b_awvalid) ? cpu_axi4_128b_aw.lock : '0) |
        ((dma_axi4_128b_aw_to_ddr0 && dma_axi4_128b_awvalid) ? dma_axi4_128b_aw.lock : '0);
    assign ddr0_axi_awcache = ((cpu_axi4_128b_aw_to_ddr0 && cpu_axi4_128b_awvalid) ? cpu_axi4_128b_aw.cache : '0) |
        ((dma_axi4_128b_aw_to_ddr0 && dma_axi4_128b_awvalid) ? dma_axi4_128b_aw.cache : '0);
    assign ddr0_axi_awprot = ((cpu_axi4_128b_aw_to_ddr0 && cpu_axi4_128b_awvalid) ? cpu_axi4_128b_aw.prot : '0) |
        ((dma_axi4_128b_aw_to_ddr0 && dma_axi4_128b_awvalid) ? dma_axi4_128b_aw.prot : '0);
    assign ddr0_axi_awvalid = ((cpu_axi4_128b_aw_to_ddr0 && cpu_axi4_128b_awvalid) ? cpu_axi4_128b_awvalid : '0) |
        ((dma_axi4_128b_aw_to_ddr0 && dma_axi4_128b_awvalid) ? dma_axi4_128b_awvalid : '0);

    // AW->W tracking FIFO: cpu_axi4 -> ddr0
    logic cpu_axi4_128b_w_to_ddr0;
    logic [3:0] cpu_axi4_128b_aw_to_ddr0_w_wptr, cpu_axi4_128b_aw_to_ddr0_w_rptr;
    logic cpu_axi4_128b_aw_to_ddr0_w_mem [16];
    logic cpu_axi4_128b_aw_to_ddr0_w_push, cpu_axi4_128b_aw_to_ddr0_w_pop;
    assign cpu_axi4_128b_aw_to_ddr0_w_push = cpu_axi4_128b_awvalid && cpu_axi4_128b_awready && cpu_axi4_128b_aw_to_ddr0;
    assign cpu_axi4_128b_aw_to_ddr0_w_pop  = cpu_axi4_128b_wvalid && cpu_axi4_128b_wready && cpu_axi4_128b_w.last && cpu_axi4_128b_w_to_ddr0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            cpu_axi4_128b_aw_to_ddr0_w_wptr <= '0;
            cpu_axi4_128b_aw_to_ddr0_w_rptr <= '0;
        end else begin
            if (cpu_axi4_128b_aw_to_ddr0_w_push) begin
                cpu_axi4_128b_aw_to_ddr0_w_mem[cpu_axi4_128b_aw_to_ddr0_w_wptr] <= 1'b1;
                cpu_axi4_128b_aw_to_ddr0_w_wptr <= cpu_axi4_128b_aw_to_ddr0_w_wptr + 1'b1;
            end
            if (cpu_axi4_128b_aw_to_ddr0_w_pop) begin
                cpu_axi4_128b_aw_to_ddr0_w_rptr <= cpu_axi4_128b_aw_to_ddr0_w_rptr + 1'b1;
            end
        end
    end
    assign cpu_axi4_128b_w_to_ddr0 = (cpu_axi4_128b_aw_to_ddr0_w_wptr != cpu_axi4_128b_aw_to_ddr0_w_rptr) ? cpu_axi4_128b_aw_to_ddr0_w_mem[cpu_axi4_128b_aw_to_ddr0_w_rptr] : 1'b0;

    // AW->W tracking FIFO: dma_axi4 -> ddr0
    logic dma_axi4_128b_w_to_ddr0;
    logic [3:0] dma_axi4_128b_aw_to_ddr0_w_wptr, dma_axi4_128b_aw_to_ddr0_w_rptr;
    logic dma_axi4_128b_aw_to_ddr0_w_mem [16];
    logic dma_axi4_128b_aw_to_ddr0_w_push, dma_axi4_128b_aw_to_ddr0_w_pop;
    assign dma_axi4_128b_aw_to_ddr0_w_push = dma_axi4_128b_awvalid && dma_axi4_128b_awready && dma_axi4_128b_aw_to_ddr0;
    assign dma_axi4_128b_aw_to_ddr0_w_pop  = dma_axi4_128b_wvalid && dma_axi4_128b_wready && dma_axi4_128b_w.last && dma_axi4_128b_w_to_ddr0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            dma_axi4_128b_aw_to_ddr0_w_wptr <= '0;
            dma_axi4_128b_aw_to_ddr0_w_rptr <= '0;
        end else begin
            if (dma_axi4_128b_aw_to_ddr0_w_push) begin
                dma_axi4_128b_aw_to_ddr0_w_mem[dma_axi4_128b_aw_to_ddr0_w_wptr] <= 1'b1;
                dma_axi4_128b_aw_to_ddr0_w_wptr <= dma_axi4_128b_aw_to_ddr0_w_wptr + 1'b1;
            end
            if (dma_axi4_128b_aw_to_ddr0_w_pop) begin
                dma_axi4_128b_aw_to_ddr0_w_rptr <= dma_axi4_128b_aw_to_ddr0_w_rptr + 1'b1;
            end
        end
    end
    assign dma_axi4_128b_w_to_ddr0 = (dma_axi4_128b_aw_to_ddr0_w_wptr != dma_axi4_128b_aw_to_ddr0_w_rptr) ? dma_axi4_128b_aw_to_ddr0_w_mem[dma_axi4_128b_aw_to_ddr0_w_rptr] : 1'b0;

    // W channel (OR-merged across writing masters, gated by w_to_<slave> FIFO)
    assign ddr0_axi_wdata = ((cpu_axi4_128b_w_to_ddr0 && cpu_axi4_128b_wvalid) ? cpu_axi4_128b_w.data : '0) |
        ((dma_axi4_128b_w_to_ddr0 && dma_axi4_128b_wvalid) ? dma_axi4_128b_w.data : '0);
    assign ddr0_axi_wstrb = ((cpu_axi4_128b_w_to_ddr0 && cpu_axi4_128b_wvalid) ? cpu_axi4_128b_w.strb : '0) |
        ((dma_axi4_128b_w_to_ddr0 && dma_axi4_128b_wvalid) ? dma_axi4_128b_w.strb : '0);
    assign ddr0_axi_wlast = ((cpu_axi4_128b_w_to_ddr0 && cpu_axi4_128b_wvalid) ? cpu_axi4_128b_w.last : '0) |
        ((dma_axi4_128b_w_to_ddr0 && dma_axi4_128b_wvalid) ? dma_axi4_128b_w.last : '0);
    assign ddr0_axi_wvalid = ((cpu_axi4_128b_w_to_ddr0 && cpu_axi4_128b_wvalid) ? cpu_axi4_128b_wvalid : '0) |
        ((dma_axi4_128b_w_to_ddr0 && dma_axi4_128b_wvalid) ? dma_axi4_128b_wvalid : '0);

    // Bready (slave → owning master, by bid_bridge_id)
    assign ddr0_axi_bready = ((ddr0_axi_bid_bridge_id == 0) && ddr0_axi_bid_valid ? cpu_axi4_128b_bready : '0) |
        ((ddr0_axi_bid_bridge_id == 1) && ddr0_axi_bid_valid ? dma_axi4_128b_bready : '0);

    // Bridge ID (writes) — picks the originating master's id
    assign ddr0_axi_bridge_id_aw = ((cpu_axi4_128b_aw_to_ddr0 && cpu_axi4_128b_awvalid) ? cpu_axi4_bridge_id_aw : '0) |
        ((dma_axi4_128b_aw_to_ddr0 && dma_axi4_128b_awvalid) ? dma_axi4_bridge_id_aw : '0);

    // AR channel (OR-merged across reading masters)
    assign ddr0_axi_arid = ((cpu_axi4_128b_ar_to_ddr0 && cpu_axi4_128b_arvalid) ? cpu_axi4_128b_ar.id : '0) |
        ((dma_axi4_128b_ar_to_ddr0 && dma_axi4_128b_arvalid) ? dma_axi4_128b_ar.id : '0);
    assign ddr0_axi_araddr = ((cpu_axi4_128b_ar_to_ddr0 && cpu_axi4_128b_arvalid) ? cpu_axi4_128b_ar.addr : '0) |
        ((dma_axi4_128b_ar_to_ddr0 && dma_axi4_128b_arvalid) ? dma_axi4_128b_ar.addr : '0);
    assign ddr0_axi_arlen = ((cpu_axi4_128b_ar_to_ddr0 && cpu_axi4_128b_arvalid) ? cpu_axi4_128b_ar.len : '0) |
        ((dma_axi4_128b_ar_to_ddr0 && dma_axi4_128b_arvalid) ? dma_axi4_128b_ar.len : '0);
    assign ddr0_axi_arsize = ((cpu_axi4_128b_ar_to_ddr0 && cpu_axi4_128b_arvalid) ? cpu_axi4_128b_ar.size : '0) |
        ((dma_axi4_128b_ar_to_ddr0 && dma_axi4_128b_arvalid) ? dma_axi4_128b_ar.size : '0);
    assign ddr0_axi_arburst = ((cpu_axi4_128b_ar_to_ddr0 && cpu_axi4_128b_arvalid) ? cpu_axi4_128b_ar.burst : '0) |
        ((dma_axi4_128b_ar_to_ddr0 && dma_axi4_128b_arvalid) ? dma_axi4_128b_ar.burst : '0);
    assign ddr0_axi_arlock = ((cpu_axi4_128b_ar_to_ddr0 && cpu_axi4_128b_arvalid) ? cpu_axi4_128b_ar.lock : '0) |
        ((dma_axi4_128b_ar_to_ddr0 && dma_axi4_128b_arvalid) ? dma_axi4_128b_ar.lock : '0);
    assign ddr0_axi_arcache = ((cpu_axi4_128b_ar_to_ddr0 && cpu_axi4_128b_arvalid) ? cpu_axi4_128b_ar.cache : '0) |
        ((dma_axi4_128b_ar_to_ddr0 && dma_axi4_128b_arvalid) ? dma_axi4_128b_ar.cache : '0);
    assign ddr0_axi_arprot = ((cpu_axi4_128b_ar_to_ddr0 && cpu_axi4_128b_arvalid) ? cpu_axi4_128b_ar.prot : '0) |
        ((dma_axi4_128b_ar_to_ddr0 && dma_axi4_128b_arvalid) ? dma_axi4_128b_ar.prot : '0);
    assign ddr0_axi_arvalid = ((cpu_axi4_128b_ar_to_ddr0 && cpu_axi4_128b_arvalid) ? cpu_axi4_128b_arvalid : '0) |
        ((dma_axi4_128b_ar_to_ddr0 && dma_axi4_128b_arvalid) ? dma_axi4_128b_arvalid : '0);

    // Rready (slave → owning master, by rid_bridge_id)
    assign ddr0_axi_rready = ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? cpu_axi4_128b_rready : '0) |
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? dma_axi4_128b_rready : '0);

    // Bridge ID (reads) — picks the originating master's id
    assign ddr0_axi_bridge_id_ar = ((cpu_axi4_128b_ar_to_ddr0 && cpu_axi4_128b_arvalid) ? cpu_axi4_bridge_id_ar : '0) |
        ((dma_axi4_128b_ar_to_ddr0 && dma_axi4_128b_arvalid) ? dma_axi4_bridge_id_ar : '0);


    // ================================================================
    // Slave 1: sram (64b)
    // ================================================================
    // Multi-master (3 masters) → sram
    //   - cpu_axi4 (rw)
    //   - dma_axi4 (rw)
    //   - host_axil (rw)

    wire cpu_axi4_64b_aw_to_sram = ((cpu_axi4_64b_aw.addr >= 32'h80000000) && (cpu_axi4_64b_aw.addr <= 32'h80ffffff));
    wire cpu_axi4_64b_ar_to_sram = ((cpu_axi4_64b_ar.addr >= 32'h80000000) && (cpu_axi4_64b_ar.addr <= 32'h80ffffff));
    wire dma_axi4_64b_aw_to_sram = ((dma_axi4_64b_aw.addr >= 32'h80000000) && (dma_axi4_64b_aw.addr <= 32'h80ffffff));
    wire dma_axi4_64b_ar_to_sram = ((dma_axi4_64b_ar.addr >= 32'h80000000) && (dma_axi4_64b_ar.addr <= 32'h80ffffff));
    wire host_axil_64b_aw_to_sram = ((host_axil_64b_aw.addr >= 32'h80000000) && (host_axil_64b_aw.addr <= 32'h80ffffff));
    wire host_axil_64b_ar_to_sram = ((host_axil_64b_ar.addr >= 32'h80000000) && (host_axil_64b_ar.addr <= 32'h80ffffff));

    // AW channel (OR-merged across writing masters)
    assign sram_axi_awid = ((cpu_axi4_64b_aw_to_sram && cpu_axi4_64b_awvalid) ? cpu_axi4_64b_aw.id : '0) |
        ((dma_axi4_64b_aw_to_sram && dma_axi4_64b_awvalid) ? dma_axi4_64b_aw.id : '0) |
        ((host_axil_64b_aw_to_sram && host_axil_64b_awvalid) ? host_axil_64b_aw.id : '0);
    assign sram_axi_awaddr = ((cpu_axi4_64b_aw_to_sram && cpu_axi4_64b_awvalid) ? cpu_axi4_64b_aw.addr : '0) |
        ((dma_axi4_64b_aw_to_sram && dma_axi4_64b_awvalid) ? dma_axi4_64b_aw.addr : '0) |
        ((host_axil_64b_aw_to_sram && host_axil_64b_awvalid) ? host_axil_64b_aw.addr : '0);
    assign sram_axi_awlen = ((cpu_axi4_64b_aw_to_sram && cpu_axi4_64b_awvalid) ? cpu_axi4_64b_aw.len : '0) |
        ((dma_axi4_64b_aw_to_sram && dma_axi4_64b_awvalid) ? dma_axi4_64b_aw.len : '0) |
        ((host_axil_64b_aw_to_sram && host_axil_64b_awvalid) ? host_axil_64b_aw.len : '0);
    assign sram_axi_awsize = ((cpu_axi4_64b_aw_to_sram && cpu_axi4_64b_awvalid) ? cpu_axi4_64b_aw.size : '0) |
        ((dma_axi4_64b_aw_to_sram && dma_axi4_64b_awvalid) ? dma_axi4_64b_aw.size : '0) |
        ((host_axil_64b_aw_to_sram && host_axil_64b_awvalid) ? host_axil_64b_aw.size : '0);
    assign sram_axi_awburst = ((cpu_axi4_64b_aw_to_sram && cpu_axi4_64b_awvalid) ? cpu_axi4_64b_aw.burst : '0) |
        ((dma_axi4_64b_aw_to_sram && dma_axi4_64b_awvalid) ? dma_axi4_64b_aw.burst : '0) |
        ((host_axil_64b_aw_to_sram && host_axil_64b_awvalid) ? host_axil_64b_aw.burst : '0);
    assign sram_axi_awlock = ((cpu_axi4_64b_aw_to_sram && cpu_axi4_64b_awvalid) ? cpu_axi4_64b_aw.lock : '0) |
        ((dma_axi4_64b_aw_to_sram && dma_axi4_64b_awvalid) ? dma_axi4_64b_aw.lock : '0) |
        ((host_axil_64b_aw_to_sram && host_axil_64b_awvalid) ? host_axil_64b_aw.lock : '0);
    assign sram_axi_awcache = ((cpu_axi4_64b_aw_to_sram && cpu_axi4_64b_awvalid) ? cpu_axi4_64b_aw.cache : '0) |
        ((dma_axi4_64b_aw_to_sram && dma_axi4_64b_awvalid) ? dma_axi4_64b_aw.cache : '0) |
        ((host_axil_64b_aw_to_sram && host_axil_64b_awvalid) ? host_axil_64b_aw.cache : '0);
    assign sram_axi_awprot = ((cpu_axi4_64b_aw_to_sram && cpu_axi4_64b_awvalid) ? cpu_axi4_64b_aw.prot : '0) |
        ((dma_axi4_64b_aw_to_sram && dma_axi4_64b_awvalid) ? dma_axi4_64b_aw.prot : '0) |
        ((host_axil_64b_aw_to_sram && host_axil_64b_awvalid) ? host_axil_64b_aw.prot : '0);
    assign sram_axi_awvalid = ((cpu_axi4_64b_aw_to_sram && cpu_axi4_64b_awvalid) ? cpu_axi4_64b_awvalid : '0) |
        ((dma_axi4_64b_aw_to_sram && dma_axi4_64b_awvalid) ? dma_axi4_64b_awvalid : '0) |
        ((host_axil_64b_aw_to_sram && host_axil_64b_awvalid) ? host_axil_64b_awvalid : '0);

    // AW->W tracking FIFO: cpu_axi4 -> sram
    logic cpu_axi4_64b_w_to_sram;
    logic [3:0] cpu_axi4_64b_aw_to_sram_w_wptr, cpu_axi4_64b_aw_to_sram_w_rptr;
    logic cpu_axi4_64b_aw_to_sram_w_mem [16];
    logic cpu_axi4_64b_aw_to_sram_w_push, cpu_axi4_64b_aw_to_sram_w_pop;
    assign cpu_axi4_64b_aw_to_sram_w_push = cpu_axi4_64b_awvalid && cpu_axi4_64b_awready && cpu_axi4_64b_aw_to_sram;
    assign cpu_axi4_64b_aw_to_sram_w_pop  = cpu_axi4_64b_wvalid && cpu_axi4_64b_wready && cpu_axi4_64b_w.last && cpu_axi4_64b_w_to_sram;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            cpu_axi4_64b_aw_to_sram_w_wptr <= '0;
            cpu_axi4_64b_aw_to_sram_w_rptr <= '0;
        end else begin
            if (cpu_axi4_64b_aw_to_sram_w_push) begin
                cpu_axi4_64b_aw_to_sram_w_mem[cpu_axi4_64b_aw_to_sram_w_wptr] <= 1'b1;
                cpu_axi4_64b_aw_to_sram_w_wptr <= cpu_axi4_64b_aw_to_sram_w_wptr + 1'b1;
            end
            if (cpu_axi4_64b_aw_to_sram_w_pop) begin
                cpu_axi4_64b_aw_to_sram_w_rptr <= cpu_axi4_64b_aw_to_sram_w_rptr + 1'b1;
            end
        end
    end
    assign cpu_axi4_64b_w_to_sram = (cpu_axi4_64b_aw_to_sram_w_wptr != cpu_axi4_64b_aw_to_sram_w_rptr) ? cpu_axi4_64b_aw_to_sram_w_mem[cpu_axi4_64b_aw_to_sram_w_rptr] : 1'b0;

    // AW->W tracking FIFO: dma_axi4 -> sram
    logic dma_axi4_64b_w_to_sram;
    logic [3:0] dma_axi4_64b_aw_to_sram_w_wptr, dma_axi4_64b_aw_to_sram_w_rptr;
    logic dma_axi4_64b_aw_to_sram_w_mem [16];
    logic dma_axi4_64b_aw_to_sram_w_push, dma_axi4_64b_aw_to_sram_w_pop;
    assign dma_axi4_64b_aw_to_sram_w_push = dma_axi4_64b_awvalid && dma_axi4_64b_awready && dma_axi4_64b_aw_to_sram;
    assign dma_axi4_64b_aw_to_sram_w_pop  = dma_axi4_64b_wvalid && dma_axi4_64b_wready && dma_axi4_64b_w.last && dma_axi4_64b_w_to_sram;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            dma_axi4_64b_aw_to_sram_w_wptr <= '0;
            dma_axi4_64b_aw_to_sram_w_rptr <= '0;
        end else begin
            if (dma_axi4_64b_aw_to_sram_w_push) begin
                dma_axi4_64b_aw_to_sram_w_mem[dma_axi4_64b_aw_to_sram_w_wptr] <= 1'b1;
                dma_axi4_64b_aw_to_sram_w_wptr <= dma_axi4_64b_aw_to_sram_w_wptr + 1'b1;
            end
            if (dma_axi4_64b_aw_to_sram_w_pop) begin
                dma_axi4_64b_aw_to_sram_w_rptr <= dma_axi4_64b_aw_to_sram_w_rptr + 1'b1;
            end
        end
    end
    assign dma_axi4_64b_w_to_sram = (dma_axi4_64b_aw_to_sram_w_wptr != dma_axi4_64b_aw_to_sram_w_rptr) ? dma_axi4_64b_aw_to_sram_w_mem[dma_axi4_64b_aw_to_sram_w_rptr] : 1'b0;

    // AW->W tracking FIFO: host_axil -> sram
    logic host_axil_64b_w_to_sram;
    logic [3:0] host_axil_64b_aw_to_sram_w_wptr, host_axil_64b_aw_to_sram_w_rptr;
    logic host_axil_64b_aw_to_sram_w_mem [16];
    logic host_axil_64b_aw_to_sram_w_push, host_axil_64b_aw_to_sram_w_pop;
    assign host_axil_64b_aw_to_sram_w_push = host_axil_64b_awvalid && host_axil_64b_awready && host_axil_64b_aw_to_sram;
    assign host_axil_64b_aw_to_sram_w_pop  = host_axil_64b_wvalid && host_axil_64b_wready && host_axil_64b_w.last && host_axil_64b_w_to_sram;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            host_axil_64b_aw_to_sram_w_wptr <= '0;
            host_axil_64b_aw_to_sram_w_rptr <= '0;
        end else begin
            if (host_axil_64b_aw_to_sram_w_push) begin
                host_axil_64b_aw_to_sram_w_mem[host_axil_64b_aw_to_sram_w_wptr] <= 1'b1;
                host_axil_64b_aw_to_sram_w_wptr <= host_axil_64b_aw_to_sram_w_wptr + 1'b1;
            end
            if (host_axil_64b_aw_to_sram_w_pop) begin
                host_axil_64b_aw_to_sram_w_rptr <= host_axil_64b_aw_to_sram_w_rptr + 1'b1;
            end
        end
    end
    assign host_axil_64b_w_to_sram = (host_axil_64b_aw_to_sram_w_wptr != host_axil_64b_aw_to_sram_w_rptr) ? host_axil_64b_aw_to_sram_w_mem[host_axil_64b_aw_to_sram_w_rptr] : 1'b0;

    // W channel (OR-merged across writing masters, gated by w_to_<slave> FIFO)
    assign sram_axi_wdata = ((cpu_axi4_64b_w_to_sram && cpu_axi4_64b_wvalid) ? cpu_axi4_64b_w.data : '0) |
        ((dma_axi4_64b_w_to_sram && dma_axi4_64b_wvalid) ? dma_axi4_64b_w.data : '0) |
        ((host_axil_64b_w_to_sram && host_axil_64b_wvalid) ? host_axil_64b_w.data : '0);
    assign sram_axi_wstrb = ((cpu_axi4_64b_w_to_sram && cpu_axi4_64b_wvalid) ? cpu_axi4_64b_w.strb : '0) |
        ((dma_axi4_64b_w_to_sram && dma_axi4_64b_wvalid) ? dma_axi4_64b_w.strb : '0) |
        ((host_axil_64b_w_to_sram && host_axil_64b_wvalid) ? host_axil_64b_w.strb : '0);
    assign sram_axi_wlast = ((cpu_axi4_64b_w_to_sram && cpu_axi4_64b_wvalid) ? cpu_axi4_64b_w.last : '0) |
        ((dma_axi4_64b_w_to_sram && dma_axi4_64b_wvalid) ? dma_axi4_64b_w.last : '0) |
        ((host_axil_64b_w_to_sram && host_axil_64b_wvalid) ? host_axil_64b_w.last : '0);
    assign sram_axi_wvalid = ((cpu_axi4_64b_w_to_sram && cpu_axi4_64b_wvalid) ? cpu_axi4_64b_wvalid : '0) |
        ((dma_axi4_64b_w_to_sram && dma_axi4_64b_wvalid) ? dma_axi4_64b_wvalid : '0) |
        ((host_axil_64b_w_to_sram && host_axil_64b_wvalid) ? host_axil_64b_wvalid : '0);

    // Bready (slave → owning master, by bid_bridge_id)
    assign sram_axi_bready = ((sram_axi_bid_bridge_id == 0) && sram_axi_bid_valid ? cpu_axi4_64b_bready : '0) |
        ((sram_axi_bid_bridge_id == 1) && sram_axi_bid_valid ? dma_axi4_64b_bready : '0) |
        ((sram_axi_bid_bridge_id == 2) && sram_axi_bid_valid ? host_axil_64b_bready : '0);

    // Bridge ID (writes) — picks the originating master's id
    assign sram_axi_bridge_id_aw = ((cpu_axi4_64b_aw_to_sram && cpu_axi4_64b_awvalid) ? cpu_axi4_bridge_id_aw : '0) |
        ((dma_axi4_64b_aw_to_sram && dma_axi4_64b_awvalid) ? dma_axi4_bridge_id_aw : '0) |
        ((host_axil_64b_aw_to_sram && host_axil_64b_awvalid) ? host_axil_bridge_id_aw : '0);

    // AR channel (OR-merged across reading masters)
    assign sram_axi_arid = ((cpu_axi4_64b_ar_to_sram && cpu_axi4_64b_arvalid) ? cpu_axi4_64b_ar.id : '0) |
        ((dma_axi4_64b_ar_to_sram && dma_axi4_64b_arvalid) ? dma_axi4_64b_ar.id : '0) |
        ((host_axil_64b_ar_to_sram && host_axil_64b_arvalid) ? host_axil_64b_ar.id : '0);
    assign sram_axi_araddr = ((cpu_axi4_64b_ar_to_sram && cpu_axi4_64b_arvalid) ? cpu_axi4_64b_ar.addr : '0) |
        ((dma_axi4_64b_ar_to_sram && dma_axi4_64b_arvalid) ? dma_axi4_64b_ar.addr : '0) |
        ((host_axil_64b_ar_to_sram && host_axil_64b_arvalid) ? host_axil_64b_ar.addr : '0);
    assign sram_axi_arlen = ((cpu_axi4_64b_ar_to_sram && cpu_axi4_64b_arvalid) ? cpu_axi4_64b_ar.len : '0) |
        ((dma_axi4_64b_ar_to_sram && dma_axi4_64b_arvalid) ? dma_axi4_64b_ar.len : '0) |
        ((host_axil_64b_ar_to_sram && host_axil_64b_arvalid) ? host_axil_64b_ar.len : '0);
    assign sram_axi_arsize = ((cpu_axi4_64b_ar_to_sram && cpu_axi4_64b_arvalid) ? cpu_axi4_64b_ar.size : '0) |
        ((dma_axi4_64b_ar_to_sram && dma_axi4_64b_arvalid) ? dma_axi4_64b_ar.size : '0) |
        ((host_axil_64b_ar_to_sram && host_axil_64b_arvalid) ? host_axil_64b_ar.size : '0);
    assign sram_axi_arburst = ((cpu_axi4_64b_ar_to_sram && cpu_axi4_64b_arvalid) ? cpu_axi4_64b_ar.burst : '0) |
        ((dma_axi4_64b_ar_to_sram && dma_axi4_64b_arvalid) ? dma_axi4_64b_ar.burst : '0) |
        ((host_axil_64b_ar_to_sram && host_axil_64b_arvalid) ? host_axil_64b_ar.burst : '0);
    assign sram_axi_arlock = ((cpu_axi4_64b_ar_to_sram && cpu_axi4_64b_arvalid) ? cpu_axi4_64b_ar.lock : '0) |
        ((dma_axi4_64b_ar_to_sram && dma_axi4_64b_arvalid) ? dma_axi4_64b_ar.lock : '0) |
        ((host_axil_64b_ar_to_sram && host_axil_64b_arvalid) ? host_axil_64b_ar.lock : '0);
    assign sram_axi_arcache = ((cpu_axi4_64b_ar_to_sram && cpu_axi4_64b_arvalid) ? cpu_axi4_64b_ar.cache : '0) |
        ((dma_axi4_64b_ar_to_sram && dma_axi4_64b_arvalid) ? dma_axi4_64b_ar.cache : '0) |
        ((host_axil_64b_ar_to_sram && host_axil_64b_arvalid) ? host_axil_64b_ar.cache : '0);
    assign sram_axi_arprot = ((cpu_axi4_64b_ar_to_sram && cpu_axi4_64b_arvalid) ? cpu_axi4_64b_ar.prot : '0) |
        ((dma_axi4_64b_ar_to_sram && dma_axi4_64b_arvalid) ? dma_axi4_64b_ar.prot : '0) |
        ((host_axil_64b_ar_to_sram && host_axil_64b_arvalid) ? host_axil_64b_ar.prot : '0);
    assign sram_axi_arvalid = ((cpu_axi4_64b_ar_to_sram && cpu_axi4_64b_arvalid) ? cpu_axi4_64b_arvalid : '0) |
        ((dma_axi4_64b_ar_to_sram && dma_axi4_64b_arvalid) ? dma_axi4_64b_arvalid : '0) |
        ((host_axil_64b_ar_to_sram && host_axil_64b_arvalid) ? host_axil_64b_arvalid : '0);

    // Rready (slave → owning master, by rid_bridge_id)
    assign sram_axi_rready = ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? cpu_axi4_64b_rready : '0) |
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? dma_axi4_64b_rready : '0) |
        ((sram_axi_rid_bridge_id == 2) && sram_axi_rid_valid ? host_axil_64b_rready : '0);

    // Bridge ID (reads) — picks the originating master's id
    assign sram_axi_bridge_id_ar = ((cpu_axi4_64b_ar_to_sram && cpu_axi4_64b_arvalid) ? cpu_axi4_bridge_id_ar : '0) |
        ((dma_axi4_64b_ar_to_sram && dma_axi4_64b_arvalid) ? dma_axi4_bridge_id_ar : '0) |
        ((host_axil_64b_ar_to_sram && host_axil_64b_arvalid) ? host_axil_bridge_id_ar : '0);


    // ================================================================
    // Slave 2: axil_periph0 (32b)
    // ================================================================
    // Multi-master (3 masters) → axil_periph0
    //   - cpu_axi4 (rw)
    //   - dma_axi4 (rw)
    //   - host_axil (rw)

    wire cpu_axi4_32b_aw_to_axil_periph0 = ((cpu_axi4_32b_aw.addr >= 32'h90000000) && (cpu_axi4_32b_aw.addr <= 32'h9000ffff));
    wire cpu_axi4_32b_ar_to_axil_periph0 = ((cpu_axi4_32b_ar.addr >= 32'h90000000) && (cpu_axi4_32b_ar.addr <= 32'h9000ffff));
    wire dma_axi4_32b_aw_to_axil_periph0 = ((dma_axi4_32b_aw.addr >= 32'h90000000) && (dma_axi4_32b_aw.addr <= 32'h9000ffff));
    wire dma_axi4_32b_ar_to_axil_periph0 = ((dma_axi4_32b_ar.addr >= 32'h90000000) && (dma_axi4_32b_ar.addr <= 32'h9000ffff));
    wire host_axil_32b_aw_to_axil_periph0 = ((host_axil_32b_aw.addr >= 32'h90000000) && (host_axil_32b_aw.addr <= 32'h9000ffff));
    wire host_axil_32b_ar_to_axil_periph0 = ((host_axil_32b_ar.addr >= 32'h90000000) && (host_axil_32b_ar.addr <= 32'h9000ffff));

    // AW channel (OR-merged across writing masters)
    assign axil_periph0_axi_awid = ((cpu_axi4_32b_aw_to_axil_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.id : '0) |
        ((dma_axi4_32b_aw_to_axil_periph0 && dma_axi4_32b_awvalid) ? dma_axi4_32b_aw.id : '0) |
        ((host_axil_32b_aw_to_axil_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.id : '0);
    assign axil_periph0_axi_awaddr = ((cpu_axi4_32b_aw_to_axil_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.addr : '0) |
        ((dma_axi4_32b_aw_to_axil_periph0 && dma_axi4_32b_awvalid) ? dma_axi4_32b_aw.addr : '0) |
        ((host_axil_32b_aw_to_axil_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.addr : '0);
    assign axil_periph0_axi_awlen = ((cpu_axi4_32b_aw_to_axil_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.len : '0) |
        ((dma_axi4_32b_aw_to_axil_periph0 && dma_axi4_32b_awvalid) ? dma_axi4_32b_aw.len : '0) |
        ((host_axil_32b_aw_to_axil_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.len : '0);
    assign axil_periph0_axi_awsize = ((cpu_axi4_32b_aw_to_axil_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.size : '0) |
        ((dma_axi4_32b_aw_to_axil_periph0 && dma_axi4_32b_awvalid) ? dma_axi4_32b_aw.size : '0) |
        ((host_axil_32b_aw_to_axil_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.size : '0);
    assign axil_periph0_axi_awburst = ((cpu_axi4_32b_aw_to_axil_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.burst : '0) |
        ((dma_axi4_32b_aw_to_axil_periph0 && dma_axi4_32b_awvalid) ? dma_axi4_32b_aw.burst : '0) |
        ((host_axil_32b_aw_to_axil_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.burst : '0);
    assign axil_periph0_axi_awlock = ((cpu_axi4_32b_aw_to_axil_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.lock : '0) |
        ((dma_axi4_32b_aw_to_axil_periph0 && dma_axi4_32b_awvalid) ? dma_axi4_32b_aw.lock : '0) |
        ((host_axil_32b_aw_to_axil_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.lock : '0);
    assign axil_periph0_axi_awcache = ((cpu_axi4_32b_aw_to_axil_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.cache : '0) |
        ((dma_axi4_32b_aw_to_axil_periph0 && dma_axi4_32b_awvalid) ? dma_axi4_32b_aw.cache : '0) |
        ((host_axil_32b_aw_to_axil_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.cache : '0);
    assign axil_periph0_axi_awprot = ((cpu_axi4_32b_aw_to_axil_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.prot : '0) |
        ((dma_axi4_32b_aw_to_axil_periph0 && dma_axi4_32b_awvalid) ? dma_axi4_32b_aw.prot : '0) |
        ((host_axil_32b_aw_to_axil_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.prot : '0);
    assign axil_periph0_axi_awvalid = ((cpu_axi4_32b_aw_to_axil_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_awvalid : '0) |
        ((dma_axi4_32b_aw_to_axil_periph0 && dma_axi4_32b_awvalid) ? dma_axi4_32b_awvalid : '0) |
        ((host_axil_32b_aw_to_axil_periph0 && host_axil_32b_awvalid) ? host_axil_32b_awvalid : '0);

    // AW->W tracking FIFO: cpu_axi4 -> axil_periph0
    logic cpu_axi4_32b_w_to_axil_periph0;
    logic [3:0] cpu_axi4_32b_aw_to_axil_periph0_w_wptr, cpu_axi4_32b_aw_to_axil_periph0_w_rptr;
    logic cpu_axi4_32b_aw_to_axil_periph0_w_mem [16];
    logic cpu_axi4_32b_aw_to_axil_periph0_w_push, cpu_axi4_32b_aw_to_axil_periph0_w_pop;
    assign cpu_axi4_32b_aw_to_axil_periph0_w_push = cpu_axi4_32b_awvalid && cpu_axi4_32b_awready && cpu_axi4_32b_aw_to_axil_periph0;
    assign cpu_axi4_32b_aw_to_axil_periph0_w_pop  = cpu_axi4_32b_wvalid && cpu_axi4_32b_wready && cpu_axi4_32b_w.last && cpu_axi4_32b_w_to_axil_periph0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            cpu_axi4_32b_aw_to_axil_periph0_w_wptr <= '0;
            cpu_axi4_32b_aw_to_axil_periph0_w_rptr <= '0;
        end else begin
            if (cpu_axi4_32b_aw_to_axil_periph0_w_push) begin
                cpu_axi4_32b_aw_to_axil_periph0_w_mem[cpu_axi4_32b_aw_to_axil_periph0_w_wptr] <= 1'b1;
                cpu_axi4_32b_aw_to_axil_periph0_w_wptr <= cpu_axi4_32b_aw_to_axil_periph0_w_wptr + 1'b1;
            end
            if (cpu_axi4_32b_aw_to_axil_periph0_w_pop) begin
                cpu_axi4_32b_aw_to_axil_periph0_w_rptr <= cpu_axi4_32b_aw_to_axil_periph0_w_rptr + 1'b1;
            end
        end
    end
    assign cpu_axi4_32b_w_to_axil_periph0 = (cpu_axi4_32b_aw_to_axil_periph0_w_wptr != cpu_axi4_32b_aw_to_axil_periph0_w_rptr) ? cpu_axi4_32b_aw_to_axil_periph0_w_mem[cpu_axi4_32b_aw_to_axil_periph0_w_rptr] : 1'b0;

    // AW->W tracking FIFO: dma_axi4 -> axil_periph0
    logic dma_axi4_32b_w_to_axil_periph0;
    logic [3:0] dma_axi4_32b_aw_to_axil_periph0_w_wptr, dma_axi4_32b_aw_to_axil_periph0_w_rptr;
    logic dma_axi4_32b_aw_to_axil_periph0_w_mem [16];
    logic dma_axi4_32b_aw_to_axil_periph0_w_push, dma_axi4_32b_aw_to_axil_periph0_w_pop;
    assign dma_axi4_32b_aw_to_axil_periph0_w_push = dma_axi4_32b_awvalid && dma_axi4_32b_awready && dma_axi4_32b_aw_to_axil_periph0;
    assign dma_axi4_32b_aw_to_axil_periph0_w_pop  = dma_axi4_32b_wvalid && dma_axi4_32b_wready && dma_axi4_32b_w.last && dma_axi4_32b_w_to_axil_periph0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            dma_axi4_32b_aw_to_axil_periph0_w_wptr <= '0;
            dma_axi4_32b_aw_to_axil_periph0_w_rptr <= '0;
        end else begin
            if (dma_axi4_32b_aw_to_axil_periph0_w_push) begin
                dma_axi4_32b_aw_to_axil_periph0_w_mem[dma_axi4_32b_aw_to_axil_periph0_w_wptr] <= 1'b1;
                dma_axi4_32b_aw_to_axil_periph0_w_wptr <= dma_axi4_32b_aw_to_axil_periph0_w_wptr + 1'b1;
            end
            if (dma_axi4_32b_aw_to_axil_periph0_w_pop) begin
                dma_axi4_32b_aw_to_axil_periph0_w_rptr <= dma_axi4_32b_aw_to_axil_periph0_w_rptr + 1'b1;
            end
        end
    end
    assign dma_axi4_32b_w_to_axil_periph0 = (dma_axi4_32b_aw_to_axil_periph0_w_wptr != dma_axi4_32b_aw_to_axil_periph0_w_rptr) ? dma_axi4_32b_aw_to_axil_periph0_w_mem[dma_axi4_32b_aw_to_axil_periph0_w_rptr] : 1'b0;

    // AW->W tracking FIFO: host_axil -> axil_periph0
    logic host_axil_32b_w_to_axil_periph0;
    logic [3:0] host_axil_32b_aw_to_axil_periph0_w_wptr, host_axil_32b_aw_to_axil_periph0_w_rptr;
    logic host_axil_32b_aw_to_axil_periph0_w_mem [16];
    logic host_axil_32b_aw_to_axil_periph0_w_push, host_axil_32b_aw_to_axil_periph0_w_pop;
    assign host_axil_32b_aw_to_axil_periph0_w_push = host_axil_32b_awvalid && host_axil_32b_awready && host_axil_32b_aw_to_axil_periph0;
    assign host_axil_32b_aw_to_axil_periph0_w_pop  = host_axil_32b_wvalid && host_axil_32b_wready && host_axil_32b_w.last && host_axil_32b_w_to_axil_periph0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            host_axil_32b_aw_to_axil_periph0_w_wptr <= '0;
            host_axil_32b_aw_to_axil_periph0_w_rptr <= '0;
        end else begin
            if (host_axil_32b_aw_to_axil_periph0_w_push) begin
                host_axil_32b_aw_to_axil_periph0_w_mem[host_axil_32b_aw_to_axil_periph0_w_wptr] <= 1'b1;
                host_axil_32b_aw_to_axil_periph0_w_wptr <= host_axil_32b_aw_to_axil_periph0_w_wptr + 1'b1;
            end
            if (host_axil_32b_aw_to_axil_periph0_w_pop) begin
                host_axil_32b_aw_to_axil_periph0_w_rptr <= host_axil_32b_aw_to_axil_periph0_w_rptr + 1'b1;
            end
        end
    end
    assign host_axil_32b_w_to_axil_periph0 = (host_axil_32b_aw_to_axil_periph0_w_wptr != host_axil_32b_aw_to_axil_periph0_w_rptr) ? host_axil_32b_aw_to_axil_periph0_w_mem[host_axil_32b_aw_to_axil_periph0_w_rptr] : 1'b0;

    // W channel (OR-merged across writing masters, gated by w_to_<slave> FIFO)
    assign axil_periph0_axi_wdata = ((cpu_axi4_32b_w_to_axil_periph0 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_w.data : '0) |
        ((dma_axi4_32b_w_to_axil_periph0 && dma_axi4_32b_wvalid) ? dma_axi4_32b_w.data : '0) |
        ((host_axil_32b_w_to_axil_periph0 && host_axil_32b_wvalid) ? host_axil_32b_w.data : '0);
    assign axil_periph0_axi_wstrb = ((cpu_axi4_32b_w_to_axil_periph0 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_w.strb : '0) |
        ((dma_axi4_32b_w_to_axil_periph0 && dma_axi4_32b_wvalid) ? dma_axi4_32b_w.strb : '0) |
        ((host_axil_32b_w_to_axil_periph0 && host_axil_32b_wvalid) ? host_axil_32b_w.strb : '0);
    assign axil_periph0_axi_wlast = ((cpu_axi4_32b_w_to_axil_periph0 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_w.last : '0) |
        ((dma_axi4_32b_w_to_axil_periph0 && dma_axi4_32b_wvalid) ? dma_axi4_32b_w.last : '0) |
        ((host_axil_32b_w_to_axil_periph0 && host_axil_32b_wvalid) ? host_axil_32b_w.last : '0);
    assign axil_periph0_axi_wvalid = ((cpu_axi4_32b_w_to_axil_periph0 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_wvalid : '0) |
        ((dma_axi4_32b_w_to_axil_periph0 && dma_axi4_32b_wvalid) ? dma_axi4_32b_wvalid : '0) |
        ((host_axil_32b_w_to_axil_periph0 && host_axil_32b_wvalid) ? host_axil_32b_wvalid : '0);

    // Bready (slave → owning master, by bid_bridge_id)
    assign axil_periph0_axi_bready = ((axil_periph0_axi_bid_bridge_id == 0) && axil_periph0_axi_bid_valid ? cpu_axi4_32b_bready : '0) |
        ((axil_periph0_axi_bid_bridge_id == 1) && axil_periph0_axi_bid_valid ? dma_axi4_32b_bready : '0) |
        ((axil_periph0_axi_bid_bridge_id == 2) && axil_periph0_axi_bid_valid ? host_axil_32b_bready : '0);

    // Bridge ID (writes) — picks the originating master's id
    assign axil_periph0_axi_bridge_id_aw = ((cpu_axi4_32b_aw_to_axil_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_bridge_id_aw : '0) |
        ((dma_axi4_32b_aw_to_axil_periph0 && dma_axi4_32b_awvalid) ? dma_axi4_bridge_id_aw : '0) |
        ((host_axil_32b_aw_to_axil_periph0 && host_axil_32b_awvalid) ? host_axil_bridge_id_aw : '0);

    // AR channel (OR-merged across reading masters)
    assign axil_periph0_axi_arid = ((cpu_axi4_32b_ar_to_axil_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.id : '0) |
        ((dma_axi4_32b_ar_to_axil_periph0 && dma_axi4_32b_arvalid) ? dma_axi4_32b_ar.id : '0) |
        ((host_axil_32b_ar_to_axil_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.id : '0);
    assign axil_periph0_axi_araddr = ((cpu_axi4_32b_ar_to_axil_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.addr : '0) |
        ((dma_axi4_32b_ar_to_axil_periph0 && dma_axi4_32b_arvalid) ? dma_axi4_32b_ar.addr : '0) |
        ((host_axil_32b_ar_to_axil_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.addr : '0);
    assign axil_periph0_axi_arlen = ((cpu_axi4_32b_ar_to_axil_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.len : '0) |
        ((dma_axi4_32b_ar_to_axil_periph0 && dma_axi4_32b_arvalid) ? dma_axi4_32b_ar.len : '0) |
        ((host_axil_32b_ar_to_axil_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.len : '0);
    assign axil_periph0_axi_arsize = ((cpu_axi4_32b_ar_to_axil_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.size : '0) |
        ((dma_axi4_32b_ar_to_axil_periph0 && dma_axi4_32b_arvalid) ? dma_axi4_32b_ar.size : '0) |
        ((host_axil_32b_ar_to_axil_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.size : '0);
    assign axil_periph0_axi_arburst = ((cpu_axi4_32b_ar_to_axil_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.burst : '0) |
        ((dma_axi4_32b_ar_to_axil_periph0 && dma_axi4_32b_arvalid) ? dma_axi4_32b_ar.burst : '0) |
        ((host_axil_32b_ar_to_axil_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.burst : '0);
    assign axil_periph0_axi_arlock = ((cpu_axi4_32b_ar_to_axil_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.lock : '0) |
        ((dma_axi4_32b_ar_to_axil_periph0 && dma_axi4_32b_arvalid) ? dma_axi4_32b_ar.lock : '0) |
        ((host_axil_32b_ar_to_axil_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.lock : '0);
    assign axil_periph0_axi_arcache = ((cpu_axi4_32b_ar_to_axil_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.cache : '0) |
        ((dma_axi4_32b_ar_to_axil_periph0 && dma_axi4_32b_arvalid) ? dma_axi4_32b_ar.cache : '0) |
        ((host_axil_32b_ar_to_axil_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.cache : '0);
    assign axil_periph0_axi_arprot = ((cpu_axi4_32b_ar_to_axil_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.prot : '0) |
        ((dma_axi4_32b_ar_to_axil_periph0 && dma_axi4_32b_arvalid) ? dma_axi4_32b_ar.prot : '0) |
        ((host_axil_32b_ar_to_axil_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.prot : '0);
    assign axil_periph0_axi_arvalid = ((cpu_axi4_32b_ar_to_axil_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_arvalid : '0) |
        ((dma_axi4_32b_ar_to_axil_periph0 && dma_axi4_32b_arvalid) ? dma_axi4_32b_arvalid : '0) |
        ((host_axil_32b_ar_to_axil_periph0 && host_axil_32b_arvalid) ? host_axil_32b_arvalid : '0);

    // Rready (slave → owning master, by rid_bridge_id)
    assign axil_periph0_axi_rready = ((axil_periph0_axi_rid_bridge_id == 0) && axil_periph0_axi_rid_valid ? cpu_axi4_32b_rready : '0) |
        ((axil_periph0_axi_rid_bridge_id == 1) && axil_periph0_axi_rid_valid ? dma_axi4_32b_rready : '0) |
        ((axil_periph0_axi_rid_bridge_id == 2) && axil_periph0_axi_rid_valid ? host_axil_32b_rready : '0);

    // Bridge ID (reads) — picks the originating master's id
    assign axil_periph0_axi_bridge_id_ar = ((cpu_axi4_32b_ar_to_axil_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_bridge_id_ar : '0) |
        ((dma_axi4_32b_ar_to_axil_periph0 && dma_axi4_32b_arvalid) ? dma_axi4_bridge_id_ar : '0) |
        ((host_axil_32b_ar_to_axil_periph0 && host_axil_32b_arvalid) ? host_axil_bridge_id_ar : '0);


    // ================================================================
    // Slave 3: axil_periph1 (32b)
    // ================================================================
    // Multi-master (2 masters) → axil_periph1
    //   - cpu_axi4 (rw)
    //   - host_axil (rw)

    wire cpu_axi4_32b_aw_to_axil_periph1 = ((cpu_axi4_32b_aw.addr >= 32'h90010000) && (cpu_axi4_32b_aw.addr <= 32'h9001ffff));
    wire cpu_axi4_32b_ar_to_axil_periph1 = ((cpu_axi4_32b_ar.addr >= 32'h90010000) && (cpu_axi4_32b_ar.addr <= 32'h9001ffff));
    wire host_axil_32b_aw_to_axil_periph1 = ((host_axil_32b_aw.addr >= 32'h90010000) && (host_axil_32b_aw.addr <= 32'h9001ffff));
    wire host_axil_32b_ar_to_axil_periph1 = ((host_axil_32b_ar.addr >= 32'h90010000) && (host_axil_32b_ar.addr <= 32'h9001ffff));

    // AW channel (OR-merged across writing masters)
    assign axil_periph1_axi_awid = ((cpu_axi4_32b_aw_to_axil_periph1 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.id : '0) |
        ((host_axil_32b_aw_to_axil_periph1 && host_axil_32b_awvalid) ? host_axil_32b_aw.id : '0);
    assign axil_periph1_axi_awaddr = ((cpu_axi4_32b_aw_to_axil_periph1 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.addr : '0) |
        ((host_axil_32b_aw_to_axil_periph1 && host_axil_32b_awvalid) ? host_axil_32b_aw.addr : '0);
    assign axil_periph1_axi_awlen = ((cpu_axi4_32b_aw_to_axil_periph1 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.len : '0) |
        ((host_axil_32b_aw_to_axil_periph1 && host_axil_32b_awvalid) ? host_axil_32b_aw.len : '0);
    assign axil_periph1_axi_awsize = ((cpu_axi4_32b_aw_to_axil_periph1 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.size : '0) |
        ((host_axil_32b_aw_to_axil_periph1 && host_axil_32b_awvalid) ? host_axil_32b_aw.size : '0);
    assign axil_periph1_axi_awburst = ((cpu_axi4_32b_aw_to_axil_periph1 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.burst : '0) |
        ((host_axil_32b_aw_to_axil_periph1 && host_axil_32b_awvalid) ? host_axil_32b_aw.burst : '0);
    assign axil_periph1_axi_awlock = ((cpu_axi4_32b_aw_to_axil_periph1 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.lock : '0) |
        ((host_axil_32b_aw_to_axil_periph1 && host_axil_32b_awvalid) ? host_axil_32b_aw.lock : '0);
    assign axil_periph1_axi_awcache = ((cpu_axi4_32b_aw_to_axil_periph1 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.cache : '0) |
        ((host_axil_32b_aw_to_axil_periph1 && host_axil_32b_awvalid) ? host_axil_32b_aw.cache : '0);
    assign axil_periph1_axi_awprot = ((cpu_axi4_32b_aw_to_axil_periph1 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.prot : '0) |
        ((host_axil_32b_aw_to_axil_periph1 && host_axil_32b_awvalid) ? host_axil_32b_aw.prot : '0);
    assign axil_periph1_axi_awvalid = ((cpu_axi4_32b_aw_to_axil_periph1 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_awvalid : '0) |
        ((host_axil_32b_aw_to_axil_periph1 && host_axil_32b_awvalid) ? host_axil_32b_awvalid : '0);

    // AW->W tracking FIFO: cpu_axi4 -> axil_periph1
    logic cpu_axi4_32b_w_to_axil_periph1;
    logic [3:0] cpu_axi4_32b_aw_to_axil_periph1_w_wptr, cpu_axi4_32b_aw_to_axil_periph1_w_rptr;
    logic cpu_axi4_32b_aw_to_axil_periph1_w_mem [16];
    logic cpu_axi4_32b_aw_to_axil_periph1_w_push, cpu_axi4_32b_aw_to_axil_periph1_w_pop;
    assign cpu_axi4_32b_aw_to_axil_periph1_w_push = cpu_axi4_32b_awvalid && cpu_axi4_32b_awready && cpu_axi4_32b_aw_to_axil_periph1;
    assign cpu_axi4_32b_aw_to_axil_periph1_w_pop  = cpu_axi4_32b_wvalid && cpu_axi4_32b_wready && cpu_axi4_32b_w.last && cpu_axi4_32b_w_to_axil_periph1;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            cpu_axi4_32b_aw_to_axil_periph1_w_wptr <= '0;
            cpu_axi4_32b_aw_to_axil_periph1_w_rptr <= '0;
        end else begin
            if (cpu_axi4_32b_aw_to_axil_periph1_w_push) begin
                cpu_axi4_32b_aw_to_axil_periph1_w_mem[cpu_axi4_32b_aw_to_axil_periph1_w_wptr] <= 1'b1;
                cpu_axi4_32b_aw_to_axil_periph1_w_wptr <= cpu_axi4_32b_aw_to_axil_periph1_w_wptr + 1'b1;
            end
            if (cpu_axi4_32b_aw_to_axil_periph1_w_pop) begin
                cpu_axi4_32b_aw_to_axil_periph1_w_rptr <= cpu_axi4_32b_aw_to_axil_periph1_w_rptr + 1'b1;
            end
        end
    end
    assign cpu_axi4_32b_w_to_axil_periph1 = (cpu_axi4_32b_aw_to_axil_periph1_w_wptr != cpu_axi4_32b_aw_to_axil_periph1_w_rptr) ? cpu_axi4_32b_aw_to_axil_periph1_w_mem[cpu_axi4_32b_aw_to_axil_periph1_w_rptr] : 1'b0;

    // AW->W tracking FIFO: host_axil -> axil_periph1
    logic host_axil_32b_w_to_axil_periph1;
    logic [3:0] host_axil_32b_aw_to_axil_periph1_w_wptr, host_axil_32b_aw_to_axil_periph1_w_rptr;
    logic host_axil_32b_aw_to_axil_periph1_w_mem [16];
    logic host_axil_32b_aw_to_axil_periph1_w_push, host_axil_32b_aw_to_axil_periph1_w_pop;
    assign host_axil_32b_aw_to_axil_periph1_w_push = host_axil_32b_awvalid && host_axil_32b_awready && host_axil_32b_aw_to_axil_periph1;
    assign host_axil_32b_aw_to_axil_periph1_w_pop  = host_axil_32b_wvalid && host_axil_32b_wready && host_axil_32b_w.last && host_axil_32b_w_to_axil_periph1;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            host_axil_32b_aw_to_axil_periph1_w_wptr <= '0;
            host_axil_32b_aw_to_axil_periph1_w_rptr <= '0;
        end else begin
            if (host_axil_32b_aw_to_axil_periph1_w_push) begin
                host_axil_32b_aw_to_axil_periph1_w_mem[host_axil_32b_aw_to_axil_periph1_w_wptr] <= 1'b1;
                host_axil_32b_aw_to_axil_periph1_w_wptr <= host_axil_32b_aw_to_axil_periph1_w_wptr + 1'b1;
            end
            if (host_axil_32b_aw_to_axil_periph1_w_pop) begin
                host_axil_32b_aw_to_axil_periph1_w_rptr <= host_axil_32b_aw_to_axil_periph1_w_rptr + 1'b1;
            end
        end
    end
    assign host_axil_32b_w_to_axil_periph1 = (host_axil_32b_aw_to_axil_periph1_w_wptr != host_axil_32b_aw_to_axil_periph1_w_rptr) ? host_axil_32b_aw_to_axil_periph1_w_mem[host_axil_32b_aw_to_axil_periph1_w_rptr] : 1'b0;

    // W channel (OR-merged across writing masters, gated by w_to_<slave> FIFO)
    assign axil_periph1_axi_wdata = ((cpu_axi4_32b_w_to_axil_periph1 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_w.data : '0) |
        ((host_axil_32b_w_to_axil_periph1 && host_axil_32b_wvalid) ? host_axil_32b_w.data : '0);
    assign axil_periph1_axi_wstrb = ((cpu_axi4_32b_w_to_axil_periph1 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_w.strb : '0) |
        ((host_axil_32b_w_to_axil_periph1 && host_axil_32b_wvalid) ? host_axil_32b_w.strb : '0);
    assign axil_periph1_axi_wlast = ((cpu_axi4_32b_w_to_axil_periph1 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_w.last : '0) |
        ((host_axil_32b_w_to_axil_periph1 && host_axil_32b_wvalid) ? host_axil_32b_w.last : '0);
    assign axil_periph1_axi_wvalid = ((cpu_axi4_32b_w_to_axil_periph1 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_wvalid : '0) |
        ((host_axil_32b_w_to_axil_periph1 && host_axil_32b_wvalid) ? host_axil_32b_wvalid : '0);

    // Bready (slave → owning master, by bid_bridge_id)
    assign axil_periph1_axi_bready = ((axil_periph1_axi_bid_bridge_id == 0) && axil_periph1_axi_bid_valid ? cpu_axi4_32b_bready : '0) |
        ((axil_periph1_axi_bid_bridge_id == 2) && axil_periph1_axi_bid_valid ? host_axil_32b_bready : '0);

    // Bridge ID (writes) — picks the originating master's id
    assign axil_periph1_axi_bridge_id_aw = ((cpu_axi4_32b_aw_to_axil_periph1 && cpu_axi4_32b_awvalid) ? cpu_axi4_bridge_id_aw : '0) |
        ((host_axil_32b_aw_to_axil_periph1 && host_axil_32b_awvalid) ? host_axil_bridge_id_aw : '0);

    // AR channel (OR-merged across reading masters)
    assign axil_periph1_axi_arid = ((cpu_axi4_32b_ar_to_axil_periph1 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.id : '0) |
        ((host_axil_32b_ar_to_axil_periph1 && host_axil_32b_arvalid) ? host_axil_32b_ar.id : '0);
    assign axil_periph1_axi_araddr = ((cpu_axi4_32b_ar_to_axil_periph1 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.addr : '0) |
        ((host_axil_32b_ar_to_axil_periph1 && host_axil_32b_arvalid) ? host_axil_32b_ar.addr : '0);
    assign axil_periph1_axi_arlen = ((cpu_axi4_32b_ar_to_axil_periph1 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.len : '0) |
        ((host_axil_32b_ar_to_axil_periph1 && host_axil_32b_arvalid) ? host_axil_32b_ar.len : '0);
    assign axil_periph1_axi_arsize = ((cpu_axi4_32b_ar_to_axil_periph1 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.size : '0) |
        ((host_axil_32b_ar_to_axil_periph1 && host_axil_32b_arvalid) ? host_axil_32b_ar.size : '0);
    assign axil_periph1_axi_arburst = ((cpu_axi4_32b_ar_to_axil_periph1 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.burst : '0) |
        ((host_axil_32b_ar_to_axil_periph1 && host_axil_32b_arvalid) ? host_axil_32b_ar.burst : '0);
    assign axil_periph1_axi_arlock = ((cpu_axi4_32b_ar_to_axil_periph1 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.lock : '0) |
        ((host_axil_32b_ar_to_axil_periph1 && host_axil_32b_arvalid) ? host_axil_32b_ar.lock : '0);
    assign axil_periph1_axi_arcache = ((cpu_axi4_32b_ar_to_axil_periph1 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.cache : '0) |
        ((host_axil_32b_ar_to_axil_periph1 && host_axil_32b_arvalid) ? host_axil_32b_ar.cache : '0);
    assign axil_periph1_axi_arprot = ((cpu_axi4_32b_ar_to_axil_periph1 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.prot : '0) |
        ((host_axil_32b_ar_to_axil_periph1 && host_axil_32b_arvalid) ? host_axil_32b_ar.prot : '0);
    assign axil_periph1_axi_arvalid = ((cpu_axi4_32b_ar_to_axil_periph1 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_arvalid : '0) |
        ((host_axil_32b_ar_to_axil_periph1 && host_axil_32b_arvalid) ? host_axil_32b_arvalid : '0);

    // Rready (slave → owning master, by rid_bridge_id)
    assign axil_periph1_axi_rready = ((axil_periph1_axi_rid_bridge_id == 0) && axil_periph1_axi_rid_valid ? cpu_axi4_32b_rready : '0) |
        ((axil_periph1_axi_rid_bridge_id == 2) && axil_periph1_axi_rid_valid ? host_axil_32b_rready : '0);

    // Bridge ID (reads) — picks the originating master's id
    assign axil_periph1_axi_bridge_id_ar = ((cpu_axi4_32b_ar_to_axil_periph1 && cpu_axi4_32b_arvalid) ? cpu_axi4_bridge_id_ar : '0) |
        ((host_axil_32b_ar_to_axil_periph1 && host_axil_32b_arvalid) ? host_axil_bridge_id_ar : '0);


    // ================================================================
    // Slave 4: apb_periph0 (32b)
    // ================================================================
    // Multi-master (2 masters) → apb_periph0
    //   - cpu_axi4 (rw)
    //   - host_axil (rw)

    wire cpu_axi4_32b_aw_to_apb_periph0 = ((cpu_axi4_32b_aw.addr >= 32'ha0000000) && (cpu_axi4_32b_aw.addr <= 32'ha000ffff));
    wire cpu_axi4_32b_ar_to_apb_periph0 = ((cpu_axi4_32b_ar.addr >= 32'ha0000000) && (cpu_axi4_32b_ar.addr <= 32'ha000ffff));
    wire host_axil_32b_aw_to_apb_periph0 = ((host_axil_32b_aw.addr >= 32'ha0000000) && (host_axil_32b_aw.addr <= 32'ha000ffff));
    wire host_axil_32b_ar_to_apb_periph0 = ((host_axil_32b_ar.addr >= 32'ha0000000) && (host_axil_32b_ar.addr <= 32'ha000ffff));

    // AW channel (OR-merged across writing masters)
    assign apb_periph0_axi_awid = ((cpu_axi4_32b_aw_to_apb_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.id : '0) |
        ((host_axil_32b_aw_to_apb_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.id : '0);
    assign apb_periph0_axi_awaddr = ((cpu_axi4_32b_aw_to_apb_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.addr : '0) |
        ((host_axil_32b_aw_to_apb_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.addr : '0);
    assign apb_periph0_axi_awlen = ((cpu_axi4_32b_aw_to_apb_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.len : '0) |
        ((host_axil_32b_aw_to_apb_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.len : '0);
    assign apb_periph0_axi_awsize = ((cpu_axi4_32b_aw_to_apb_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.size : '0) |
        ((host_axil_32b_aw_to_apb_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.size : '0);
    assign apb_periph0_axi_awburst = ((cpu_axi4_32b_aw_to_apb_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.burst : '0) |
        ((host_axil_32b_aw_to_apb_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.burst : '0);
    assign apb_periph0_axi_awlock = ((cpu_axi4_32b_aw_to_apb_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.lock : '0) |
        ((host_axil_32b_aw_to_apb_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.lock : '0);
    assign apb_periph0_axi_awcache = ((cpu_axi4_32b_aw_to_apb_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.cache : '0) |
        ((host_axil_32b_aw_to_apb_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.cache : '0);
    assign apb_periph0_axi_awprot = ((cpu_axi4_32b_aw_to_apb_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_aw.prot : '0) |
        ((host_axil_32b_aw_to_apb_periph0 && host_axil_32b_awvalid) ? host_axil_32b_aw.prot : '0);
    assign apb_periph0_axi_awvalid = ((cpu_axi4_32b_aw_to_apb_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_32b_awvalid : '0) |
        ((host_axil_32b_aw_to_apb_periph0 && host_axil_32b_awvalid) ? host_axil_32b_awvalid : '0);

    // AW->W tracking FIFO: cpu_axi4 -> apb_periph0
    logic cpu_axi4_32b_w_to_apb_periph0;
    logic [3:0] cpu_axi4_32b_aw_to_apb_periph0_w_wptr, cpu_axi4_32b_aw_to_apb_periph0_w_rptr;
    logic cpu_axi4_32b_aw_to_apb_periph0_w_mem [16];
    logic cpu_axi4_32b_aw_to_apb_periph0_w_push, cpu_axi4_32b_aw_to_apb_periph0_w_pop;
    assign cpu_axi4_32b_aw_to_apb_periph0_w_push = cpu_axi4_32b_awvalid && cpu_axi4_32b_awready && cpu_axi4_32b_aw_to_apb_periph0;
    assign cpu_axi4_32b_aw_to_apb_periph0_w_pop  = cpu_axi4_32b_wvalid && cpu_axi4_32b_wready && cpu_axi4_32b_w.last && cpu_axi4_32b_w_to_apb_periph0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            cpu_axi4_32b_aw_to_apb_periph0_w_wptr <= '0;
            cpu_axi4_32b_aw_to_apb_periph0_w_rptr <= '0;
        end else begin
            if (cpu_axi4_32b_aw_to_apb_periph0_w_push) begin
                cpu_axi4_32b_aw_to_apb_periph0_w_mem[cpu_axi4_32b_aw_to_apb_periph0_w_wptr] <= 1'b1;
                cpu_axi4_32b_aw_to_apb_periph0_w_wptr <= cpu_axi4_32b_aw_to_apb_periph0_w_wptr + 1'b1;
            end
            if (cpu_axi4_32b_aw_to_apb_periph0_w_pop) begin
                cpu_axi4_32b_aw_to_apb_periph0_w_rptr <= cpu_axi4_32b_aw_to_apb_periph0_w_rptr + 1'b1;
            end
        end
    end
    assign cpu_axi4_32b_w_to_apb_periph0 = (cpu_axi4_32b_aw_to_apb_periph0_w_wptr != cpu_axi4_32b_aw_to_apb_periph0_w_rptr) ? cpu_axi4_32b_aw_to_apb_periph0_w_mem[cpu_axi4_32b_aw_to_apb_periph0_w_rptr] : 1'b0;

    // AW->W tracking FIFO: host_axil -> apb_periph0
    logic host_axil_32b_w_to_apb_periph0;
    logic [3:0] host_axil_32b_aw_to_apb_periph0_w_wptr, host_axil_32b_aw_to_apb_periph0_w_rptr;
    logic host_axil_32b_aw_to_apb_periph0_w_mem [16];
    logic host_axil_32b_aw_to_apb_periph0_w_push, host_axil_32b_aw_to_apb_periph0_w_pop;
    assign host_axil_32b_aw_to_apb_periph0_w_push = host_axil_32b_awvalid && host_axil_32b_awready && host_axil_32b_aw_to_apb_periph0;
    assign host_axil_32b_aw_to_apb_periph0_w_pop  = host_axil_32b_wvalid && host_axil_32b_wready && host_axil_32b_w.last && host_axil_32b_w_to_apb_periph0;
    always_ff @(posedge aclk or negedge aresetn) begin
        if (!aresetn) begin
            host_axil_32b_aw_to_apb_periph0_w_wptr <= '0;
            host_axil_32b_aw_to_apb_periph0_w_rptr <= '0;
        end else begin
            if (host_axil_32b_aw_to_apb_periph0_w_push) begin
                host_axil_32b_aw_to_apb_periph0_w_mem[host_axil_32b_aw_to_apb_periph0_w_wptr] <= 1'b1;
                host_axil_32b_aw_to_apb_periph0_w_wptr <= host_axil_32b_aw_to_apb_periph0_w_wptr + 1'b1;
            end
            if (host_axil_32b_aw_to_apb_periph0_w_pop) begin
                host_axil_32b_aw_to_apb_periph0_w_rptr <= host_axil_32b_aw_to_apb_periph0_w_rptr + 1'b1;
            end
        end
    end
    assign host_axil_32b_w_to_apb_periph0 = (host_axil_32b_aw_to_apb_periph0_w_wptr != host_axil_32b_aw_to_apb_periph0_w_rptr) ? host_axil_32b_aw_to_apb_periph0_w_mem[host_axil_32b_aw_to_apb_periph0_w_rptr] : 1'b0;

    // W channel (OR-merged across writing masters, gated by w_to_<slave> FIFO)
    assign apb_periph0_axi_wdata = ((cpu_axi4_32b_w_to_apb_periph0 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_w.data : '0) |
        ((host_axil_32b_w_to_apb_periph0 && host_axil_32b_wvalid) ? host_axil_32b_w.data : '0);
    assign apb_periph0_axi_wstrb = ((cpu_axi4_32b_w_to_apb_periph0 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_w.strb : '0) |
        ((host_axil_32b_w_to_apb_periph0 && host_axil_32b_wvalid) ? host_axil_32b_w.strb : '0);
    assign apb_periph0_axi_wlast = ((cpu_axi4_32b_w_to_apb_periph0 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_w.last : '0) |
        ((host_axil_32b_w_to_apb_periph0 && host_axil_32b_wvalid) ? host_axil_32b_w.last : '0);
    assign apb_periph0_axi_wvalid = ((cpu_axi4_32b_w_to_apb_periph0 && cpu_axi4_32b_wvalid) ? cpu_axi4_32b_wvalid : '0) |
        ((host_axil_32b_w_to_apb_periph0 && host_axil_32b_wvalid) ? host_axil_32b_wvalid : '0);

    // Bready (slave → owning master, by bid_bridge_id)
    assign apb_periph0_axi_bready = ((apb_periph0_axi_bid_bridge_id == 0) && apb_periph0_axi_bid_valid ? cpu_axi4_32b_bready : '0) |
        ((apb_periph0_axi_bid_bridge_id == 2) && apb_periph0_axi_bid_valid ? host_axil_32b_bready : '0);

    // Bridge ID (writes) — picks the originating master's id
    assign apb_periph0_axi_bridge_id_aw = ((cpu_axi4_32b_aw_to_apb_periph0 && cpu_axi4_32b_awvalid) ? cpu_axi4_bridge_id_aw : '0) |
        ((host_axil_32b_aw_to_apb_periph0 && host_axil_32b_awvalid) ? host_axil_bridge_id_aw : '0);

    // AR channel (OR-merged across reading masters)
    assign apb_periph0_axi_arid = ((cpu_axi4_32b_ar_to_apb_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.id : '0) |
        ((host_axil_32b_ar_to_apb_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.id : '0);
    assign apb_periph0_axi_araddr = ((cpu_axi4_32b_ar_to_apb_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.addr : '0) |
        ((host_axil_32b_ar_to_apb_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.addr : '0);
    assign apb_periph0_axi_arlen = ((cpu_axi4_32b_ar_to_apb_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.len : '0) |
        ((host_axil_32b_ar_to_apb_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.len : '0);
    assign apb_periph0_axi_arsize = ((cpu_axi4_32b_ar_to_apb_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.size : '0) |
        ((host_axil_32b_ar_to_apb_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.size : '0);
    assign apb_periph0_axi_arburst = ((cpu_axi4_32b_ar_to_apb_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.burst : '0) |
        ((host_axil_32b_ar_to_apb_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.burst : '0);
    assign apb_periph0_axi_arlock = ((cpu_axi4_32b_ar_to_apb_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.lock : '0) |
        ((host_axil_32b_ar_to_apb_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.lock : '0);
    assign apb_periph0_axi_arcache = ((cpu_axi4_32b_ar_to_apb_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.cache : '0) |
        ((host_axil_32b_ar_to_apb_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.cache : '0);
    assign apb_periph0_axi_arprot = ((cpu_axi4_32b_ar_to_apb_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_ar.prot : '0) |
        ((host_axil_32b_ar_to_apb_periph0 && host_axil_32b_arvalid) ? host_axil_32b_ar.prot : '0);
    assign apb_periph0_axi_arvalid = ((cpu_axi4_32b_ar_to_apb_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_32b_arvalid : '0) |
        ((host_axil_32b_ar_to_apb_periph0 && host_axil_32b_arvalid) ? host_axil_32b_arvalid : '0);

    // Rready (slave → owning master, by rid_bridge_id)
    assign apb_periph0_axi_rready = ((apb_periph0_axi_rid_bridge_id == 0) && apb_periph0_axi_rid_valid ? cpu_axi4_32b_rready : '0) |
        ((apb_periph0_axi_rid_bridge_id == 2) && apb_periph0_axi_rid_valid ? host_axil_32b_rready : '0);

    // Bridge ID (reads) — picks the originating master's id
    assign apb_periph0_axi_bridge_id_ar = ((cpu_axi4_32b_ar_to_apb_periph0 && cpu_axi4_32b_arvalid) ? cpu_axi4_bridge_id_ar : '0) |
        ((host_axil_32b_ar_to_apb_periph0 && host_axil_32b_arvalid) ? host_axil_bridge_id_ar : '0);


    // ================================================================
    // Response MUXes (OR together all slave responses)
    // ================================================================

    // Master: cpu_axi4, Width path: 32b
    assign cpu_axi4_32b_awready = 
        (cpu_axi4_32b_aw_to_axil_periph0 ? axil_periph0_axi_awready : '0) |
        (cpu_axi4_32b_aw_to_axil_periph1 ? axil_periph1_axi_awready : '0) |
        (cpu_axi4_32b_aw_to_apb_periph0 ? apb_periph0_axi_awready : '0);

    assign cpu_axi4_32b_wready = 
        (cpu_axi4_32b_w_to_axil_periph0 ? axil_periph0_axi_wready : '0) |
        (cpu_axi4_32b_w_to_axil_periph1 ? axil_periph1_axi_wready : '0) |
        (cpu_axi4_32b_w_to_apb_periph0 ? apb_periph0_axi_wready : '0);

    assign cpu_axi4_32b_b.id = 
        ((axil_periph0_axi_bid_bridge_id == 0) && axil_periph0_axi_bid_valid ? axil_periph0_axi_bid : '0) |
        ((axil_periph1_axi_bid_bridge_id == 0) && axil_periph1_axi_bid_valid ? axil_periph1_axi_bid : '0) |
        ((apb_periph0_axi_bid_bridge_id == 0) && apb_periph0_axi_bid_valid ? apb_periph0_axi_bid : '0);

    assign cpu_axi4_32b_b.resp = 
        ((axil_periph0_axi_bid_bridge_id == 0) && axil_periph0_axi_bid_valid ? axil_periph0_axi_bresp : '0) |
        ((axil_periph1_axi_bid_bridge_id == 0) && axil_periph1_axi_bid_valid ? axil_periph1_axi_bresp : '0) |
        ((apb_periph0_axi_bid_bridge_id == 0) && apb_periph0_axi_bid_valid ? apb_periph0_axi_bresp : '0);

    assign cpu_axi4_32b_bvalid = 
        ((axil_periph0_axi_bid_bridge_id == 0) && axil_periph0_axi_bid_valid ? axil_periph0_axi_bvalid : '0) |
        ((axil_periph1_axi_bid_bridge_id == 0) && axil_periph1_axi_bid_valid ? axil_periph1_axi_bvalid : '0) |
        ((apb_periph0_axi_bid_bridge_id == 0) && apb_periph0_axi_bid_valid ? apb_periph0_axi_bvalid : '0);

    assign cpu_axi4_32b_arready = 
        (cpu_axi4_32b_ar_to_axil_periph0 ? axil_periph0_axi_arready : '0) |
        (cpu_axi4_32b_ar_to_axil_periph1 ? axil_periph1_axi_arready : '0) |
        (cpu_axi4_32b_ar_to_apb_periph0 ? apb_periph0_axi_arready : '0);

    assign cpu_axi4_32b_r.id = 
        ((axil_periph0_axi_rid_bridge_id == 0) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rid : '0) |
        ((axil_periph1_axi_rid_bridge_id == 0) && axil_periph1_axi_rid_valid ? axil_periph1_axi_rid : '0) |
        ((apb_periph0_axi_rid_bridge_id == 0) && apb_periph0_axi_rid_valid ? apb_periph0_axi_rid : '0);

    assign cpu_axi4_32b_r.data = 
        ((axil_periph0_axi_rid_bridge_id == 0) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rdata : 32'b0) |
        ((axil_periph1_axi_rid_bridge_id == 0) && axil_periph1_axi_rid_valid ? axil_periph1_axi_rdata : 32'b0) |
        ((apb_periph0_axi_rid_bridge_id == 0) && apb_periph0_axi_rid_valid ? apb_periph0_axi_rdata : 32'b0);

    assign cpu_axi4_32b_r.resp = 
        ((axil_periph0_axi_rid_bridge_id == 0) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rresp : '0) |
        ((axil_periph1_axi_rid_bridge_id == 0) && axil_periph1_axi_rid_valid ? axil_periph1_axi_rresp : '0) |
        ((apb_periph0_axi_rid_bridge_id == 0) && apb_periph0_axi_rid_valid ? apb_periph0_axi_rresp : '0);

    assign cpu_axi4_32b_r.last = 
        ((axil_periph0_axi_rid_bridge_id == 0) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rlast : '0) |
        ((axil_periph1_axi_rid_bridge_id == 0) && axil_periph1_axi_rid_valid ? axil_periph1_axi_rlast : '0) |
        ((apb_periph0_axi_rid_bridge_id == 0) && apb_periph0_axi_rid_valid ? apb_periph0_axi_rlast : '0);

    assign cpu_axi4_32b_rvalid = 
        ((axil_periph0_axi_rid_bridge_id == 0) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rvalid : '0) |
        ((axil_periph1_axi_rid_bridge_id == 0) && axil_periph1_axi_rid_valid ? axil_periph1_axi_rvalid : '0) |
        ((apb_periph0_axi_rid_bridge_id == 0) && apb_periph0_axi_rid_valid ? apb_periph0_axi_rvalid : '0);


    // Master: cpu_axi4, Width path: 64b
    assign cpu_axi4_64b_awready = 
        (cpu_axi4_64b_aw_to_sram ? sram_axi_awready : '0);

    assign cpu_axi4_64b_wready = 
        (cpu_axi4_64b_w_to_sram ? sram_axi_wready : '0);

    assign cpu_axi4_64b_b.id = 
        ((sram_axi_bid_bridge_id == 0) && sram_axi_bid_valid ? sram_axi_bid : '0);

    assign cpu_axi4_64b_b.resp = 
        ((sram_axi_bid_bridge_id == 0) && sram_axi_bid_valid ? sram_axi_bresp : '0);

    assign cpu_axi4_64b_bvalid = 
        ((sram_axi_bid_bridge_id == 0) && sram_axi_bid_valid ? sram_axi_bvalid : '0);

    assign cpu_axi4_64b_arready = 
        (cpu_axi4_64b_ar_to_sram ? sram_axi_arready : '0);

    assign cpu_axi4_64b_r.id = 
        ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? sram_axi_rid : '0);

    assign cpu_axi4_64b_r.data = 
        ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? sram_axi_rdata : 64'b0);

    assign cpu_axi4_64b_r.resp = 
        ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? sram_axi_rresp : '0);

    assign cpu_axi4_64b_r.last = 
        ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? sram_axi_rlast : '0);

    assign cpu_axi4_64b_rvalid = 
        ((sram_axi_rid_bridge_id == 0) && sram_axi_rid_valid ? sram_axi_rvalid : '0);


    // Master: cpu_axi4, Width path: 128b
    assign cpu_axi4_128b_awready = 
        (cpu_axi4_128b_aw_to_ddr0 ? ddr0_axi_awready : '0);

    assign cpu_axi4_128b_wready = 
        (cpu_axi4_128b_w_to_ddr0 ? ddr0_axi_wready : '0);

    assign cpu_axi4_128b_b.id = 
        ((ddr0_axi_bid_bridge_id == 0) && ddr0_axi_bid_valid ? ddr0_axi_bid : '0);

    assign cpu_axi4_128b_b.resp = 
        ((ddr0_axi_bid_bridge_id == 0) && ddr0_axi_bid_valid ? ddr0_axi_bresp : '0);

    assign cpu_axi4_128b_bvalid = 
        ((ddr0_axi_bid_bridge_id == 0) && ddr0_axi_bid_valid ? ddr0_axi_bvalid : '0);

    assign cpu_axi4_128b_arready = 
        (cpu_axi4_128b_ar_to_ddr0 ? ddr0_axi_arready : '0);

    assign cpu_axi4_128b_r.id = 
        ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? ddr0_axi_rid : '0);

    assign cpu_axi4_128b_r.data = 
        ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? ddr0_axi_rdata : 128'b0);

    assign cpu_axi4_128b_r.resp = 
        ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? ddr0_axi_rresp : '0);

    assign cpu_axi4_128b_r.last = 
        ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? ddr0_axi_rlast : '0);

    assign cpu_axi4_128b_rvalid = 
        ((ddr0_axi_rid_bridge_id == 0) && ddr0_axi_rid_valid ? ddr0_axi_rvalid : '0);


    // Master: dma_axi4, Width path: 32b
    assign dma_axi4_32b_awready = 
        (dma_axi4_32b_aw_to_axil_periph0 ? axil_periph0_axi_awready : '0);

    assign dma_axi4_32b_wready = 
        (dma_axi4_32b_w_to_axil_periph0 ? axil_periph0_axi_wready : '0);

    assign dma_axi4_32b_b.id = 
        ((axil_periph0_axi_bid_bridge_id == 1) && axil_periph0_axi_bid_valid ? axil_periph0_axi_bid : '0);

    assign dma_axi4_32b_b.resp = 
        ((axil_periph0_axi_bid_bridge_id == 1) && axil_periph0_axi_bid_valid ? axil_periph0_axi_bresp : '0);

    assign dma_axi4_32b_bvalid = 
        ((axil_periph0_axi_bid_bridge_id == 1) && axil_periph0_axi_bid_valid ? axil_periph0_axi_bvalid : '0);

    assign dma_axi4_32b_arready = 
        (dma_axi4_32b_ar_to_axil_periph0 ? axil_periph0_axi_arready : '0);

    assign dma_axi4_32b_r.id = 
        ((axil_periph0_axi_rid_bridge_id == 1) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rid : '0);

    assign dma_axi4_32b_r.data = 
        ((axil_periph0_axi_rid_bridge_id == 1) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rdata : 32'b0);

    assign dma_axi4_32b_r.resp = 
        ((axil_periph0_axi_rid_bridge_id == 1) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rresp : '0);

    assign dma_axi4_32b_r.last = 
        ((axil_periph0_axi_rid_bridge_id == 1) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rlast : '0);

    assign dma_axi4_32b_rvalid = 
        ((axil_periph0_axi_rid_bridge_id == 1) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rvalid : '0);


    // Master: dma_axi4, Width path: 64b
    assign dma_axi4_64b_awready = 
        (dma_axi4_64b_aw_to_sram ? sram_axi_awready : '0);

    assign dma_axi4_64b_wready = 
        (dma_axi4_64b_w_to_sram ? sram_axi_wready : '0);

    assign dma_axi4_64b_b.id = 
        ((sram_axi_bid_bridge_id == 1) && sram_axi_bid_valid ? sram_axi_bid : '0);

    assign dma_axi4_64b_b.resp = 
        ((sram_axi_bid_bridge_id == 1) && sram_axi_bid_valid ? sram_axi_bresp : '0);

    assign dma_axi4_64b_bvalid = 
        ((sram_axi_bid_bridge_id == 1) && sram_axi_bid_valid ? sram_axi_bvalid : '0);

    assign dma_axi4_64b_arready = 
        (dma_axi4_64b_ar_to_sram ? sram_axi_arready : '0);

    assign dma_axi4_64b_r.id = 
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? sram_axi_rid : '0);

    assign dma_axi4_64b_r.data = 
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? sram_axi_rdata : 64'b0);

    assign dma_axi4_64b_r.resp = 
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? sram_axi_rresp : '0);

    assign dma_axi4_64b_r.last = 
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? sram_axi_rlast : '0);

    assign dma_axi4_64b_rvalid = 
        ((sram_axi_rid_bridge_id == 1) && sram_axi_rid_valid ? sram_axi_rvalid : '0);


    // Master: dma_axi4, Width path: 128b
    assign dma_axi4_128b_awready = 
        (dma_axi4_128b_aw_to_ddr0 ? ddr0_axi_awready : '0);

    assign dma_axi4_128b_wready = 
        (dma_axi4_128b_w_to_ddr0 ? ddr0_axi_wready : '0);

    assign dma_axi4_128b_b.id = 
        ((ddr0_axi_bid_bridge_id == 1) && ddr0_axi_bid_valid ? ddr0_axi_bid : '0);

    assign dma_axi4_128b_b.resp = 
        ((ddr0_axi_bid_bridge_id == 1) && ddr0_axi_bid_valid ? ddr0_axi_bresp : '0);

    assign dma_axi4_128b_bvalid = 
        ((ddr0_axi_bid_bridge_id == 1) && ddr0_axi_bid_valid ? ddr0_axi_bvalid : '0);

    assign dma_axi4_128b_arready = 
        (dma_axi4_128b_ar_to_ddr0 ? ddr0_axi_arready : '0);

    assign dma_axi4_128b_r.id = 
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? ddr0_axi_rid : '0);

    assign dma_axi4_128b_r.data = 
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? ddr0_axi_rdata : 128'b0);

    assign dma_axi4_128b_r.resp = 
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? ddr0_axi_rresp : '0);

    assign dma_axi4_128b_r.last = 
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? ddr0_axi_rlast : '0);

    assign dma_axi4_128b_rvalid = 
        ((ddr0_axi_rid_bridge_id == 1) && ddr0_axi_rid_valid ? ddr0_axi_rvalid : '0);


    // Master: host_axil, Width path: 32b
    assign host_axil_32b_awready = 
        (host_axil_32b_aw_to_axil_periph0 ? axil_periph0_axi_awready : '0) |
        (host_axil_32b_aw_to_axil_periph1 ? axil_periph1_axi_awready : '0) |
        (host_axil_32b_aw_to_apb_periph0 ? apb_periph0_axi_awready : '0);

    assign host_axil_32b_wready = 
        (host_axil_32b_w_to_axil_periph0 ? axil_periph0_axi_wready : '0) |
        (host_axil_32b_w_to_axil_periph1 ? axil_periph1_axi_wready : '0) |
        (host_axil_32b_w_to_apb_periph0 ? apb_periph0_axi_wready : '0);

    assign host_axil_32b_b.id = 
        ((axil_periph0_axi_bid_bridge_id == 2) && axil_periph0_axi_bid_valid ? axil_periph0_axi_bid : '0) |
        ((axil_periph1_axi_bid_bridge_id == 2) && axil_periph1_axi_bid_valid ? axil_periph1_axi_bid : '0) |
        ((apb_periph0_axi_bid_bridge_id == 2) && apb_periph0_axi_bid_valid ? apb_periph0_axi_bid : '0);

    assign host_axil_32b_b.resp = 
        ((axil_periph0_axi_bid_bridge_id == 2) && axil_periph0_axi_bid_valid ? axil_periph0_axi_bresp : '0) |
        ((axil_periph1_axi_bid_bridge_id == 2) && axil_periph1_axi_bid_valid ? axil_periph1_axi_bresp : '0) |
        ((apb_periph0_axi_bid_bridge_id == 2) && apb_periph0_axi_bid_valid ? apb_periph0_axi_bresp : '0);

    assign host_axil_32b_bvalid = 
        ((axil_periph0_axi_bid_bridge_id == 2) && axil_periph0_axi_bid_valid ? axil_periph0_axi_bvalid : '0) |
        ((axil_periph1_axi_bid_bridge_id == 2) && axil_periph1_axi_bid_valid ? axil_periph1_axi_bvalid : '0) |
        ((apb_periph0_axi_bid_bridge_id == 2) && apb_periph0_axi_bid_valid ? apb_periph0_axi_bvalid : '0);

    assign host_axil_32b_arready = 
        (host_axil_32b_ar_to_axil_periph0 ? axil_periph0_axi_arready : '0) |
        (host_axil_32b_ar_to_axil_periph1 ? axil_periph1_axi_arready : '0) |
        (host_axil_32b_ar_to_apb_periph0 ? apb_periph0_axi_arready : '0);

    assign host_axil_32b_r.id = 
        ((axil_periph0_axi_rid_bridge_id == 2) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rid : '0) |
        ((axil_periph1_axi_rid_bridge_id == 2) && axil_periph1_axi_rid_valid ? axil_periph1_axi_rid : '0) |
        ((apb_periph0_axi_rid_bridge_id == 2) && apb_periph0_axi_rid_valid ? apb_periph0_axi_rid : '0);

    assign host_axil_32b_r.data = 
        ((axil_periph0_axi_rid_bridge_id == 2) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rdata : 32'b0) |
        ((axil_periph1_axi_rid_bridge_id == 2) && axil_periph1_axi_rid_valid ? axil_periph1_axi_rdata : 32'b0) |
        ((apb_periph0_axi_rid_bridge_id == 2) && apb_periph0_axi_rid_valid ? apb_periph0_axi_rdata : 32'b0);

    assign host_axil_32b_r.resp = 
        ((axil_periph0_axi_rid_bridge_id == 2) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rresp : '0) |
        ((axil_periph1_axi_rid_bridge_id == 2) && axil_periph1_axi_rid_valid ? axil_periph1_axi_rresp : '0) |
        ((apb_periph0_axi_rid_bridge_id == 2) && apb_periph0_axi_rid_valid ? apb_periph0_axi_rresp : '0);

    assign host_axil_32b_r.last = 
        ((axil_periph0_axi_rid_bridge_id == 2) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rlast : '0) |
        ((axil_periph1_axi_rid_bridge_id == 2) && axil_periph1_axi_rid_valid ? axil_periph1_axi_rlast : '0) |
        ((apb_periph0_axi_rid_bridge_id == 2) && apb_periph0_axi_rid_valid ? apb_periph0_axi_rlast : '0);

    assign host_axil_32b_rvalid = 
        ((axil_periph0_axi_rid_bridge_id == 2) && axil_periph0_axi_rid_valid ? axil_periph0_axi_rvalid : '0) |
        ((axil_periph1_axi_rid_bridge_id == 2) && axil_periph1_axi_rid_valid ? axil_periph1_axi_rvalid : '0) |
        ((apb_periph0_axi_rid_bridge_id == 2) && apb_periph0_axi_rid_valid ? apb_periph0_axi_rvalid : '0);


    // Master: host_axil, Width path: 64b
    assign host_axil_64b_awready = 
        (host_axil_64b_aw_to_sram ? sram_axi_awready : '0);

    assign host_axil_64b_wready = 
        (host_axil_64b_w_to_sram ? sram_axi_wready : '0);

    assign host_axil_64b_b.id = 
        ((sram_axi_bid_bridge_id == 2) && sram_axi_bid_valid ? sram_axi_bid : '0);

    assign host_axil_64b_b.resp = 
        ((sram_axi_bid_bridge_id == 2) && sram_axi_bid_valid ? sram_axi_bresp : '0);

    assign host_axil_64b_bvalid = 
        ((sram_axi_bid_bridge_id == 2) && sram_axi_bid_valid ? sram_axi_bvalid : '0);

    assign host_axil_64b_arready = 
        (host_axil_64b_ar_to_sram ? sram_axi_arready : '0);

    assign host_axil_64b_r.id = 
        ((sram_axi_rid_bridge_id == 2) && sram_axi_rid_valid ? sram_axi_rid : '0);

    assign host_axil_64b_r.data = 
        ((sram_axi_rid_bridge_id == 2) && sram_axi_rid_valid ? sram_axi_rdata : 64'b0);

    assign host_axil_64b_r.resp = 
        ((sram_axi_rid_bridge_id == 2) && sram_axi_rid_valid ? sram_axi_rresp : '0);

    assign host_axil_64b_r.last = 
        ((sram_axi_rid_bridge_id == 2) && sram_axi_rid_valid ? sram_axi_rlast : '0);

    assign host_axil_64b_rvalid = 
        ((sram_axi_rid_bridge_id == 2) && sram_axi_rid_valid ? sram_axi_rvalid : '0);


endmodule : bridge_b_axi4_axil_3x5_xbar
