// Bridge: bridge_b_axi4_axil_3x5
// Generated by: BridgeModuleGenerator
// 
// Architecture:
//   Master → Master Adapter → Crossbar → Slave Adapter → Slave
//
//   Master Adapter contains:
//   - Timing wrapper (axi4_slave_wr/rd)
//   - Address decode
//   - Width adaptation
//
//   Slave Adapter contains:
//   - Timing wrapper (axi4_master_wr/rd) or Protocol converter (axi4_to_apb/axil)

`timescale 1ns / 1ps

import bridge_b_axi4_axil_3x5_pkg::*;

module bridge_b_axi4_axil_3x5 (
    input  logic aclk,
    input  logic aresetn,

    // Master 0: cpu_axi4 (rw)
    // Master: cpu_axi4 (axi4, rw)
    input  logic [3:0]  cpu_axi_awid,
    input  logic [31:0]  cpu_axi_awaddr,
    input  logic [7:0]  cpu_axi_awlen,
    input  logic [2:0]  cpu_axi_awsize,
    input  logic [1:0]  cpu_axi_awburst,
    input  logic         cpu_axi_awlock,
    input  logic [3:0]  cpu_axi_awcache,
    input  logic [2:0]  cpu_axi_awprot,
    input  logic [3:0]  cpu_axi_awqos,
    input  logic [3:0]  cpu_axi_awregion,
    input  logic         cpu_axi_awuser,
    input  logic         cpu_axi_awvalid,
    output  logic         cpu_axi_awready,

    input  logic [63:0]  cpu_axi_wdata,
    input  logic [7:0]  cpu_axi_wstrb,
    input  logic         cpu_axi_wlast,
    input  logic         cpu_axi_wuser,
    input  logic         cpu_axi_wvalid,
    output  logic         cpu_axi_wready,

    output  logic [3:0]  cpu_axi_bid,
    output  logic [1:0]  cpu_axi_bresp,
    output  logic         cpu_axi_buser,
    output  logic         cpu_axi_bvalid,
    input  logic         cpu_axi_bready,

    input  logic [3:0]  cpu_axi_arid,
    input  logic [31:0]  cpu_axi_araddr,
    input  logic [7:0]  cpu_axi_arlen,
    input  logic [2:0]  cpu_axi_arsize,
    input  logic [1:0]  cpu_axi_arburst,
    input  logic         cpu_axi_arlock,
    input  logic [3:0]  cpu_axi_arcache,
    input  logic [2:0]  cpu_axi_arprot,
    input  logic [3:0]  cpu_axi_arqos,
    input  logic [3:0]  cpu_axi_arregion,
    input  logic         cpu_axi_aruser,
    input  logic         cpu_axi_arvalid,
    output  logic         cpu_axi_arready,

    output  logic [3:0]  cpu_axi_rid,
    output  logic [63:0]  cpu_axi_rdata,
    output  logic [1:0]  cpu_axi_rresp,
    output  logic         cpu_axi_rlast,
    output  logic         cpu_axi_ruser,
    output  logic         cpu_axi_rvalid,
    input  logic         cpu_axi_rready,

    // Master 1: dma_axi4 (rw)
    // Master: dma_axi4 (axi4, rw)
    input  logic [3:0]  dma_axi_awid,
    input  logic [31:0]  dma_axi_awaddr,
    input  logic [7:0]  dma_axi_awlen,
    input  logic [2:0]  dma_axi_awsize,
    input  logic [1:0]  dma_axi_awburst,
    input  logic         dma_axi_awlock,
    input  logic [3:0]  dma_axi_awcache,
    input  logic [2:0]  dma_axi_awprot,
    input  logic [3:0]  dma_axi_awqos,
    input  logic [3:0]  dma_axi_awregion,
    input  logic         dma_axi_awuser,
    input  logic         dma_axi_awvalid,
    output  logic         dma_axi_awready,

    input  logic [127:0]  dma_axi_wdata,
    input  logic [15:0]  dma_axi_wstrb,
    input  logic         dma_axi_wlast,
    input  logic         dma_axi_wuser,
    input  logic         dma_axi_wvalid,
    output  logic         dma_axi_wready,

    output  logic [3:0]  dma_axi_bid,
    output  logic [1:0]  dma_axi_bresp,
    output  logic         dma_axi_buser,
    output  logic         dma_axi_bvalid,
    input  logic         dma_axi_bready,

    input  logic [3:0]  dma_axi_arid,
    input  logic [31:0]  dma_axi_araddr,
    input  logic [7:0]  dma_axi_arlen,
    input  logic [2:0]  dma_axi_arsize,
    input  logic [1:0]  dma_axi_arburst,
    input  logic         dma_axi_arlock,
    input  logic [3:0]  dma_axi_arcache,
    input  logic [2:0]  dma_axi_arprot,
    input  logic [3:0]  dma_axi_arqos,
    input  logic [3:0]  dma_axi_arregion,
    input  logic         dma_axi_aruser,
    input  logic         dma_axi_arvalid,
    output  logic         dma_axi_arready,

    output  logic [3:0]  dma_axi_rid,
    output  logic [127:0]  dma_axi_rdata,
    output  logic [1:0]  dma_axi_rresp,
    output  logic         dma_axi_rlast,
    output  logic         dma_axi_ruser,
    output  logic         dma_axi_rvalid,
    input  logic         dma_axi_rready,

    // Master 2: host_axil (rw)
    // Master: host_axil (axil, rw)
    input  logic [31:0] host_axil_awaddr,
    input  logic [2:0]            host_axil_awprot,
    input  logic                  host_axil_awvalid,
    output logic                  host_axil_awready,
    input  logic [31:0] host_axil_wdata,
    input  logic [3:0] host_axil_wstrb,
    input  logic                  host_axil_wvalid,
    output logic                  host_axil_wready,
    output logic [1:0]            host_axil_bresp,
    output logic                  host_axil_bvalid,
    input  logic                  host_axil_bready,
    input  logic [31:0] host_axil_araddr,
    input  logic [2:0]            host_axil_arprot,
    input  logic                  host_axil_arvalid,
    output logic                  host_axil_arready,
    output logic [31:0] host_axil_rdata,
    output logic [1:0]            host_axil_rresp,
    output logic                  host_axil_rvalid,
    input  logic                  host_axil_rready,

    // Slave 0: ddr0
    // AXI4 Slave: ddr0
    output  logic [3:0]  ddr0_s_axi_awid,
    output  logic [31:0]  ddr0_s_axi_awaddr,
    output  logic [7:0]  ddr0_s_axi_awlen,
    output  logic [2:0]  ddr0_s_axi_awsize,
    output  logic [1:0]  ddr0_s_axi_awburst,
    output  logic         ddr0_s_axi_awlock,
    output  logic [3:0]  ddr0_s_axi_awcache,
    output  logic [2:0]  ddr0_s_axi_awprot,
    output  logic [3:0]  ddr0_s_axi_awqos,
    output  logic [3:0]  ddr0_s_axi_awregion,
    output  logic         ddr0_s_axi_awuser,
    output  logic         ddr0_s_axi_awvalid,
    input  logic         ddr0_s_axi_awready,

    output  logic [127:0]  ddr0_s_axi_wdata,
    output  logic [15:0]  ddr0_s_axi_wstrb,
    output  logic         ddr0_s_axi_wlast,
    output  logic         ddr0_s_axi_wuser,
    output  logic         ddr0_s_axi_wvalid,
    input  logic         ddr0_s_axi_wready,

    input  logic [3:0]  ddr0_s_axi_bid,
    input  logic [1:0]  ddr0_s_axi_bresp,
    input  logic         ddr0_s_axi_buser,
    input  logic         ddr0_s_axi_bvalid,
    output  logic         ddr0_s_axi_bready,

    output  logic [3:0]  ddr0_s_axi_arid,
    output  logic [31:0]  ddr0_s_axi_araddr,
    output  logic [7:0]  ddr0_s_axi_arlen,
    output  logic [2:0]  ddr0_s_axi_arsize,
    output  logic [1:0]  ddr0_s_axi_arburst,
    output  logic         ddr0_s_axi_arlock,
    output  logic [3:0]  ddr0_s_axi_arcache,
    output  logic [2:0]  ddr0_s_axi_arprot,
    output  logic [3:0]  ddr0_s_axi_arqos,
    output  logic [3:0]  ddr0_s_axi_arregion,
    output  logic         ddr0_s_axi_aruser,
    output  logic         ddr0_s_axi_arvalid,
    input  logic         ddr0_s_axi_arready,

    input  logic [3:0]  ddr0_s_axi_rid,
    input  logic [127:0]  ddr0_s_axi_rdata,
    input  logic [1:0]  ddr0_s_axi_rresp,
    input  logic         ddr0_s_axi_rlast,
    input  logic         ddr0_s_axi_ruser,
    input  logic         ddr0_s_axi_rvalid,
    output  logic         ddr0_s_axi_rready,

    // Slave 1: sram
    // AXI4 Slave: sram
    output  logic [3:0]  sram_s_axi_awid,
    output  logic [31:0]  sram_s_axi_awaddr,
    output  logic [7:0]  sram_s_axi_awlen,
    output  logic [2:0]  sram_s_axi_awsize,
    output  logic [1:0]  sram_s_axi_awburst,
    output  logic         sram_s_axi_awlock,
    output  logic [3:0]  sram_s_axi_awcache,
    output  logic [2:0]  sram_s_axi_awprot,
    output  logic [3:0]  sram_s_axi_awqos,
    output  logic [3:0]  sram_s_axi_awregion,
    output  logic         sram_s_axi_awuser,
    output  logic         sram_s_axi_awvalid,
    input  logic         sram_s_axi_awready,

    output  logic [63:0]  sram_s_axi_wdata,
    output  logic [7:0]  sram_s_axi_wstrb,
    output  logic         sram_s_axi_wlast,
    output  logic         sram_s_axi_wuser,
    output  logic         sram_s_axi_wvalid,
    input  logic         sram_s_axi_wready,

    input  logic [3:0]  sram_s_axi_bid,
    input  logic [1:0]  sram_s_axi_bresp,
    input  logic         sram_s_axi_buser,
    input  logic         sram_s_axi_bvalid,
    output  logic         sram_s_axi_bready,

    output  logic [3:0]  sram_s_axi_arid,
    output  logic [31:0]  sram_s_axi_araddr,
    output  logic [7:0]  sram_s_axi_arlen,
    output  logic [2:0]  sram_s_axi_arsize,
    output  logic [1:0]  sram_s_axi_arburst,
    output  logic         sram_s_axi_arlock,
    output  logic [3:0]  sram_s_axi_arcache,
    output  logic [2:0]  sram_s_axi_arprot,
    output  logic [3:0]  sram_s_axi_arqos,
    output  logic [3:0]  sram_s_axi_arregion,
    output  logic         sram_s_axi_aruser,
    output  logic         sram_s_axi_arvalid,
    input  logic         sram_s_axi_arready,

    input  logic [3:0]  sram_s_axi_rid,
    input  logic [63:0]  sram_s_axi_rdata,
    input  logic [1:0]  sram_s_axi_rresp,
    input  logic         sram_s_axi_rlast,
    input  logic         sram_s_axi_ruser,
    input  logic         sram_s_axi_rvalid,
    output  logic         sram_s_axi_rready,

    // Slave 2: axil_periph0
    // AXI4-Lite Slave: axil_periph0
    output logic [31:0] axil_periph0_awaddr,
    output logic [2:0]            axil_periph0_awprot,
    output logic                  axil_periph0_awvalid,
    input  logic                  axil_periph0_awready,
    output logic [31:0] axil_periph0_wdata,
    output logic [3:0] axil_periph0_wstrb,
    output logic                  axil_periph0_wvalid,
    input  logic                  axil_periph0_wready,
    input  logic [1:0]            axil_periph0_bresp,
    input  logic                  axil_periph0_bvalid,
    output logic                  axil_periph0_bready,
    output logic [31:0] axil_periph0_araddr,
    output logic [2:0]            axil_periph0_arprot,
    output logic                  axil_periph0_arvalid,
    input  logic                  axil_periph0_arready,
    input  logic [31:0] axil_periph0_rdata,
    input  logic [1:0]            axil_periph0_rresp,
    input  logic                  axil_periph0_rvalid,
    output logic                  axil_periph0_rready,

    // Slave 3: axil_periph1
    // AXI4-Lite Slave: axil_periph1
    output logic [31:0] axil_periph1_awaddr,
    output logic [2:0]            axil_periph1_awprot,
    output logic                  axil_periph1_awvalid,
    input  logic                  axil_periph1_awready,
    output logic [31:0] axil_periph1_wdata,
    output logic [3:0] axil_periph1_wstrb,
    output logic                  axil_periph1_wvalid,
    input  logic                  axil_periph1_wready,
    input  logic [1:0]            axil_periph1_bresp,
    input  logic                  axil_periph1_bvalid,
    output logic                  axil_periph1_bready,
    output logic [31:0] axil_periph1_araddr,
    output logic [2:0]            axil_periph1_arprot,
    output logic                  axil_periph1_arvalid,
    input  logic                  axil_periph1_arready,
    input  logic [31:0] axil_periph1_rdata,
    input  logic [1:0]            axil_periph1_rresp,
    input  logic                  axil_periph1_rvalid,
    output logic                  axil_periph1_rready,

    // Slave 4: apb_periph0
    // APB Slave: apb_periph0
    output  logic         apb_periph0_PSEL,
    output  logic [31:0]  apb_periph0_PADDR,
    output  logic         apb_periph0_PENABLE,
    output  logic         apb_periph0_PWRITE,
    output  logic [31:0]  apb_periph0_PWDATA,
    output  logic [3:0]  apb_periph0_PSTRB,
    output  logic [2:0]  apb_periph0_PPROT,
    input  logic [31:0]  apb_periph0_PRDATA,
    input  logic         apb_periph0_PREADY,
    input  logic         apb_periph0_PSLVERR
);

    localparam NUM_SLAVES = 5;

    // cpu_axi4 Adapter outputs
    logic [NUM_SLAVES-1:0] cpu_axi4_slave_select_aw;
    logic [BRIDGE_ID_WIDTH-1:0] cpu_axi4_bridge_id_aw;
    logic [NUM_SLAVES-1:0] cpu_axi4_slave_select_ar;
    logic [BRIDGE_ID_WIDTH-1:0] cpu_axi4_bridge_id_ar;
    // 32b path
    axi4_aw_t     cpu_axi4_32b_aw;
    logic         cpu_axi4_32b_awvalid;
    logic         cpu_axi4_32b_awready;
    axi4_w_32b_t  cpu_axi4_32b_w;
    logic         cpu_axi4_32b_wvalid;
    logic         cpu_axi4_32b_wready;
    axi4_b_t      cpu_axi4_32b_b;
    logic         cpu_axi4_32b_bvalid;
    logic         cpu_axi4_32b_bready;
    axi4_ar_t     cpu_axi4_32b_ar;
    logic         cpu_axi4_32b_arvalid;
    logic         cpu_axi4_32b_arready;
    axi4_r_32b_t  cpu_axi4_32b_r;
    logic         cpu_axi4_32b_rvalid;
    logic         cpu_axi4_32b_rready;
    // 64b path
    axi4_aw_t     cpu_axi4_64b_aw;
    logic         cpu_axi4_64b_awvalid;
    logic         cpu_axi4_64b_awready;
    axi4_w_64b_t  cpu_axi4_64b_w;
    logic         cpu_axi4_64b_wvalid;
    logic         cpu_axi4_64b_wready;
    axi4_b_t      cpu_axi4_64b_b;
    logic         cpu_axi4_64b_bvalid;
    logic         cpu_axi4_64b_bready;
    axi4_ar_t     cpu_axi4_64b_ar;
    logic         cpu_axi4_64b_arvalid;
    logic         cpu_axi4_64b_arready;
    axi4_r_64b_t  cpu_axi4_64b_r;
    logic         cpu_axi4_64b_rvalid;
    logic         cpu_axi4_64b_rready;
    // 128b path
    axi4_aw_t     cpu_axi4_128b_aw;
    logic         cpu_axi4_128b_awvalid;
    logic         cpu_axi4_128b_awready;
    axi4_w_128b_t  cpu_axi4_128b_w;
    logic         cpu_axi4_128b_wvalid;
    logic         cpu_axi4_128b_wready;
    axi4_b_t      cpu_axi4_128b_b;
    logic         cpu_axi4_128b_bvalid;
    logic         cpu_axi4_128b_bready;
    axi4_ar_t     cpu_axi4_128b_ar;
    logic         cpu_axi4_128b_arvalid;
    logic         cpu_axi4_128b_arready;
    axi4_r_128b_t  cpu_axi4_128b_r;
    logic         cpu_axi4_128b_rvalid;
    logic         cpu_axi4_128b_rready;

    // dma_axi4 Adapter outputs
    logic [NUM_SLAVES-1:0] dma_axi4_slave_select_aw;
    logic [BRIDGE_ID_WIDTH-1:0] dma_axi4_bridge_id_aw;
    logic [NUM_SLAVES-1:0] dma_axi4_slave_select_ar;
    logic [BRIDGE_ID_WIDTH-1:0] dma_axi4_bridge_id_ar;
    // 32b path
    axi4_aw_t     dma_axi4_32b_aw;
    logic         dma_axi4_32b_awvalid;
    logic         dma_axi4_32b_awready;
    axi4_w_32b_t  dma_axi4_32b_w;
    logic         dma_axi4_32b_wvalid;
    logic         dma_axi4_32b_wready;
    axi4_b_t      dma_axi4_32b_b;
    logic         dma_axi4_32b_bvalid;
    logic         dma_axi4_32b_bready;
    axi4_ar_t     dma_axi4_32b_ar;
    logic         dma_axi4_32b_arvalid;
    logic         dma_axi4_32b_arready;
    axi4_r_32b_t  dma_axi4_32b_r;
    logic         dma_axi4_32b_rvalid;
    logic         dma_axi4_32b_rready;
    // 64b path
    axi4_aw_t     dma_axi4_64b_aw;
    logic         dma_axi4_64b_awvalid;
    logic         dma_axi4_64b_awready;
    axi4_w_64b_t  dma_axi4_64b_w;
    logic         dma_axi4_64b_wvalid;
    logic         dma_axi4_64b_wready;
    axi4_b_t      dma_axi4_64b_b;
    logic         dma_axi4_64b_bvalid;
    logic         dma_axi4_64b_bready;
    axi4_ar_t     dma_axi4_64b_ar;
    logic         dma_axi4_64b_arvalid;
    logic         dma_axi4_64b_arready;
    axi4_r_64b_t  dma_axi4_64b_r;
    logic         dma_axi4_64b_rvalid;
    logic         dma_axi4_64b_rready;
    // 128b path
    axi4_aw_t     dma_axi4_128b_aw;
    logic         dma_axi4_128b_awvalid;
    logic         dma_axi4_128b_awready;
    axi4_w_128b_t  dma_axi4_128b_w;
    logic         dma_axi4_128b_wvalid;
    logic         dma_axi4_128b_wready;
    axi4_b_t      dma_axi4_128b_b;
    logic         dma_axi4_128b_bvalid;
    logic         dma_axi4_128b_bready;
    axi4_ar_t     dma_axi4_128b_ar;
    logic         dma_axi4_128b_arvalid;
    logic         dma_axi4_128b_arready;
    axi4_r_128b_t  dma_axi4_128b_r;
    logic         dma_axi4_128b_rvalid;
    logic         dma_axi4_128b_rready;

    // host_axil Adapter outputs
    logic [NUM_SLAVES-1:0] host_axil_slave_select_aw;
    logic [BRIDGE_ID_WIDTH-1:0] host_axil_bridge_id_aw;
    logic [NUM_SLAVES-1:0] host_axil_slave_select_ar;
    logic [BRIDGE_ID_WIDTH-1:0] host_axil_bridge_id_ar;
    // 32b path
    axi4_aw_t     host_axil_32b_aw;
    logic         host_axil_32b_awvalid;
    logic         host_axil_32b_awready;
    axi4_w_32b_t  host_axil_32b_w;
    logic         host_axil_32b_wvalid;
    logic         host_axil_32b_wready;
    axi4_b_t      host_axil_32b_b;
    logic         host_axil_32b_bvalid;
    logic         host_axil_32b_bready;
    axi4_ar_t     host_axil_32b_ar;
    logic         host_axil_32b_arvalid;
    logic         host_axil_32b_arready;
    axi4_r_32b_t  host_axil_32b_r;
    logic         host_axil_32b_rvalid;
    logic         host_axil_32b_rready;
    // 64b path
    axi4_aw_t     host_axil_64b_aw;
    logic         host_axil_64b_awvalid;
    logic         host_axil_64b_awready;
    axi4_w_64b_t  host_axil_64b_w;
    logic         host_axil_64b_wvalid;
    logic         host_axil_64b_wready;
    axi4_b_t      host_axil_64b_b;
    logic         host_axil_64b_bvalid;
    logic         host_axil_64b_bready;
    axi4_ar_t     host_axil_64b_ar;
    logic         host_axil_64b_arvalid;
    logic         host_axil_64b_arready;
    axi4_r_64b_t  host_axil_64b_r;
    logic         host_axil_64b_rvalid;
    logic         host_axil_64b_rready;

    // Crossbar-to-Slave Internal AXI4 Signals
    // ddr0 (AXI4, 128b AXI4 interface)
    logic [3:0]            xbar_ddr0_axi_awid;
    logic [31:0]               xbar_ddr0_axi_awaddr;
    logic [7:0]                xbar_ddr0_axi_awlen;
    logic [2:0]                xbar_ddr0_axi_awsize;
    logic [1:0]                xbar_ddr0_axi_awburst;
    logic                      xbar_ddr0_axi_awlock;
    logic [3:0]                xbar_ddr0_axi_awcache;
    logic [2:0]                xbar_ddr0_axi_awprot;
    logic [3:0]                xbar_ddr0_axi_awqos;
    logic [3:0]                xbar_ddr0_axi_awregion;
    logic                      xbar_ddr0_axi_awuser;
    logic                      xbar_ddr0_axi_awvalid;
    logic                      xbar_ddr0_axi_awready;
    logic [127:0] xbar_ddr0_axi_wdata;
    logic [15:0] xbar_ddr0_axi_wstrb;
    logic                      xbar_ddr0_axi_wlast;
    logic                      xbar_ddr0_axi_wuser;
    logic                      xbar_ddr0_axi_wvalid;
    logic                      xbar_ddr0_axi_wready;
    logic [3:0]            xbar_ddr0_axi_bid;
    logic [1:0]                xbar_ddr0_axi_bresp;
    logic                      xbar_ddr0_axi_buser;
    logic                      xbar_ddr0_axi_bvalid;
    logic                      xbar_ddr0_axi_bready;
    logic [3:0]            xbar_ddr0_axi_arid;
    logic [31:0]               xbar_ddr0_axi_araddr;
    logic [7:0]                xbar_ddr0_axi_arlen;
    logic [2:0]                xbar_ddr0_axi_arsize;
    logic [1:0]                xbar_ddr0_axi_arburst;
    logic                      xbar_ddr0_axi_arlock;
    logic [3:0]                xbar_ddr0_axi_arcache;
    logic [2:0]                xbar_ddr0_axi_arprot;
    logic [3:0]                xbar_ddr0_axi_arqos;
    logic [3:0]                xbar_ddr0_axi_arregion;
    logic                      xbar_ddr0_axi_aruser;
    logic                      xbar_ddr0_axi_arvalid;
    logic                      xbar_ddr0_axi_arready;
    logic [3:0]            xbar_ddr0_axi_rid;
    logic [127:0] xbar_ddr0_axi_rdata;
    logic [1:0]                xbar_ddr0_axi_rresp;
    logic                      xbar_ddr0_axi_rlast;
    logic                      xbar_ddr0_axi_ruser;
    logic                      xbar_ddr0_axi_rvalid;
    logic                      xbar_ddr0_axi_rready;
    logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_bridge_id_aw;
    logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_bid_bridge_id;
    logic                       ddr0_axi_bid_valid;
    logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_bridge_id_ar;
    logic [BRIDGE_ID_WIDTH-1:0] ddr0_axi_rid_bridge_id;
    logic                       ddr0_axi_rid_valid;

    // sram (AXI4, 64b AXI4 interface)
    logic [3:0]            xbar_sram_axi_awid;
    logic [31:0]               xbar_sram_axi_awaddr;
    logic [7:0]                xbar_sram_axi_awlen;
    logic [2:0]                xbar_sram_axi_awsize;
    logic [1:0]                xbar_sram_axi_awburst;
    logic                      xbar_sram_axi_awlock;
    logic [3:0]                xbar_sram_axi_awcache;
    logic [2:0]                xbar_sram_axi_awprot;
    logic [3:0]                xbar_sram_axi_awqos;
    logic [3:0]                xbar_sram_axi_awregion;
    logic                      xbar_sram_axi_awuser;
    logic                      xbar_sram_axi_awvalid;
    logic                      xbar_sram_axi_awready;
    logic [63:0] xbar_sram_axi_wdata;
    logic [7:0] xbar_sram_axi_wstrb;
    logic                      xbar_sram_axi_wlast;
    logic                      xbar_sram_axi_wuser;
    logic                      xbar_sram_axi_wvalid;
    logic                      xbar_sram_axi_wready;
    logic [3:0]            xbar_sram_axi_bid;
    logic [1:0]                xbar_sram_axi_bresp;
    logic                      xbar_sram_axi_buser;
    logic                      xbar_sram_axi_bvalid;
    logic                      xbar_sram_axi_bready;
    logic [3:0]            xbar_sram_axi_arid;
    logic [31:0]               xbar_sram_axi_araddr;
    logic [7:0]                xbar_sram_axi_arlen;
    logic [2:0]                xbar_sram_axi_arsize;
    logic [1:0]                xbar_sram_axi_arburst;
    logic                      xbar_sram_axi_arlock;
    logic [3:0]                xbar_sram_axi_arcache;
    logic [2:0]                xbar_sram_axi_arprot;
    logic [3:0]                xbar_sram_axi_arqos;
    logic [3:0]                xbar_sram_axi_arregion;
    logic                      xbar_sram_axi_aruser;
    logic                      xbar_sram_axi_arvalid;
    logic                      xbar_sram_axi_arready;
    logic [3:0]            xbar_sram_axi_rid;
    logic [63:0] xbar_sram_axi_rdata;
    logic [1:0]                xbar_sram_axi_rresp;
    logic                      xbar_sram_axi_rlast;
    logic                      xbar_sram_axi_ruser;
    logic                      xbar_sram_axi_rvalid;
    logic                      xbar_sram_axi_rready;
    logic [BRIDGE_ID_WIDTH-1:0] sram_axi_bridge_id_aw;
    logic [BRIDGE_ID_WIDTH-1:0] sram_axi_bid_bridge_id;
    logic                       sram_axi_bid_valid;
    logic [BRIDGE_ID_WIDTH-1:0] sram_axi_bridge_id_ar;
    logic [BRIDGE_ID_WIDTH-1:0] sram_axi_rid_bridge_id;
    logic                       sram_axi_rid_valid;

    // axil_periph0 (AXIL, 32b AXI4 interface)
    logic [3:0]            xbar_axil_periph0_axi_awid;
    logic [31:0]               xbar_axil_periph0_axi_awaddr;
    logic [7:0]                xbar_axil_periph0_axi_awlen;
    logic [2:0]                xbar_axil_periph0_axi_awsize;
    logic [1:0]                xbar_axil_periph0_axi_awburst;
    logic                      xbar_axil_periph0_axi_awlock;
    logic [3:0]                xbar_axil_periph0_axi_awcache;
    logic [2:0]                xbar_axil_periph0_axi_awprot;
    logic [3:0]                xbar_axil_periph0_axi_awqos;
    logic [3:0]                xbar_axil_periph0_axi_awregion;
    logic                      xbar_axil_periph0_axi_awuser;
    logic                      xbar_axil_periph0_axi_awvalid;
    logic                      xbar_axil_periph0_axi_awready;
    logic [31:0] xbar_axil_periph0_axi_wdata;
    logic [3:0] xbar_axil_periph0_axi_wstrb;
    logic                      xbar_axil_periph0_axi_wlast;
    logic                      xbar_axil_periph0_axi_wuser;
    logic                      xbar_axil_periph0_axi_wvalid;
    logic                      xbar_axil_periph0_axi_wready;
    logic [3:0]            xbar_axil_periph0_axi_bid;
    logic [1:0]                xbar_axil_periph0_axi_bresp;
    logic                      xbar_axil_periph0_axi_buser;
    logic                      xbar_axil_periph0_axi_bvalid;
    logic                      xbar_axil_periph0_axi_bready;
    logic [3:0]            xbar_axil_periph0_axi_arid;
    logic [31:0]               xbar_axil_periph0_axi_araddr;
    logic [7:0]                xbar_axil_periph0_axi_arlen;
    logic [2:0]                xbar_axil_periph0_axi_arsize;
    logic [1:0]                xbar_axil_periph0_axi_arburst;
    logic                      xbar_axil_periph0_axi_arlock;
    logic [3:0]                xbar_axil_periph0_axi_arcache;
    logic [2:0]                xbar_axil_periph0_axi_arprot;
    logic [3:0]                xbar_axil_periph0_axi_arqos;
    logic [3:0]                xbar_axil_periph0_axi_arregion;
    logic                      xbar_axil_periph0_axi_aruser;
    logic                      xbar_axil_periph0_axi_arvalid;
    logic                      xbar_axil_periph0_axi_arready;
    logic [3:0]            xbar_axil_periph0_axi_rid;
    logic [31:0] xbar_axil_periph0_axi_rdata;
    logic [1:0]                xbar_axil_periph0_axi_rresp;
    logic                      xbar_axil_periph0_axi_rlast;
    logic                      xbar_axil_periph0_axi_ruser;
    logic                      xbar_axil_periph0_axi_rvalid;
    logic                      xbar_axil_periph0_axi_rready;
    logic [BRIDGE_ID_WIDTH-1:0] axil_periph0_axi_bridge_id_aw;
    logic [BRIDGE_ID_WIDTH-1:0] axil_periph0_axi_bid_bridge_id;
    logic                       axil_periph0_axi_bid_valid;
    logic [BRIDGE_ID_WIDTH-1:0] axil_periph0_axi_bridge_id_ar;
    logic [BRIDGE_ID_WIDTH-1:0] axil_periph0_axi_rid_bridge_id;
    logic                       axil_periph0_axi_rid_valid;

    // axil_periph1 (AXIL, 32b AXI4 interface)
    logic [3:0]            xbar_axil_periph1_axi_awid;
    logic [31:0]               xbar_axil_periph1_axi_awaddr;
    logic [7:0]                xbar_axil_periph1_axi_awlen;
    logic [2:0]                xbar_axil_periph1_axi_awsize;
    logic [1:0]                xbar_axil_periph1_axi_awburst;
    logic                      xbar_axil_periph1_axi_awlock;
    logic [3:0]                xbar_axil_periph1_axi_awcache;
    logic [2:0]                xbar_axil_periph1_axi_awprot;
    logic [3:0]                xbar_axil_periph1_axi_awqos;
    logic [3:0]                xbar_axil_periph1_axi_awregion;
    logic                      xbar_axil_periph1_axi_awuser;
    logic                      xbar_axil_periph1_axi_awvalid;
    logic                      xbar_axil_periph1_axi_awready;
    logic [31:0] xbar_axil_periph1_axi_wdata;
    logic [3:0] xbar_axil_periph1_axi_wstrb;
    logic                      xbar_axil_periph1_axi_wlast;
    logic                      xbar_axil_periph1_axi_wuser;
    logic                      xbar_axil_periph1_axi_wvalid;
    logic                      xbar_axil_periph1_axi_wready;
    logic [3:0]            xbar_axil_periph1_axi_bid;
    logic [1:0]                xbar_axil_periph1_axi_bresp;
    logic                      xbar_axil_periph1_axi_buser;
    logic                      xbar_axil_periph1_axi_bvalid;
    logic                      xbar_axil_periph1_axi_bready;
    logic [3:0]            xbar_axil_periph1_axi_arid;
    logic [31:0]               xbar_axil_periph1_axi_araddr;
    logic [7:0]                xbar_axil_periph1_axi_arlen;
    logic [2:0]                xbar_axil_periph1_axi_arsize;
    logic [1:0]                xbar_axil_periph1_axi_arburst;
    logic                      xbar_axil_periph1_axi_arlock;
    logic [3:0]                xbar_axil_periph1_axi_arcache;
    logic [2:0]                xbar_axil_periph1_axi_arprot;
    logic [3:0]                xbar_axil_periph1_axi_arqos;
    logic [3:0]                xbar_axil_periph1_axi_arregion;
    logic                      xbar_axil_periph1_axi_aruser;
    logic                      xbar_axil_periph1_axi_arvalid;
    logic                      xbar_axil_periph1_axi_arready;
    logic [3:0]            xbar_axil_periph1_axi_rid;
    logic [31:0] xbar_axil_periph1_axi_rdata;
    logic [1:0]                xbar_axil_periph1_axi_rresp;
    logic                      xbar_axil_periph1_axi_rlast;
    logic                      xbar_axil_periph1_axi_ruser;
    logic                      xbar_axil_periph1_axi_rvalid;
    logic                      xbar_axil_periph1_axi_rready;
    logic [BRIDGE_ID_WIDTH-1:0] axil_periph1_axi_bridge_id_aw;
    logic [BRIDGE_ID_WIDTH-1:0] axil_periph1_axi_bid_bridge_id;
    logic                       axil_periph1_axi_bid_valid;
    logic [BRIDGE_ID_WIDTH-1:0] axil_periph1_axi_bridge_id_ar;
    logic [BRIDGE_ID_WIDTH-1:0] axil_periph1_axi_rid_bridge_id;
    logic                       axil_periph1_axi_rid_valid;

    // apb_periph0 (APB, 32b AXI4 interface)
    logic [3:0]            xbar_apb_periph0_axi_awid;
    logic [31:0]               xbar_apb_periph0_axi_awaddr;
    logic [7:0]                xbar_apb_periph0_axi_awlen;
    logic [2:0]                xbar_apb_periph0_axi_awsize;
    logic [1:0]                xbar_apb_periph0_axi_awburst;
    logic                      xbar_apb_periph0_axi_awlock;
    logic [3:0]                xbar_apb_periph0_axi_awcache;
    logic [2:0]                xbar_apb_periph0_axi_awprot;
    logic [3:0]                xbar_apb_periph0_axi_awqos;
    logic [3:0]                xbar_apb_periph0_axi_awregion;
    logic                      xbar_apb_periph0_axi_awuser;
    logic                      xbar_apb_periph0_axi_awvalid;
    logic                      xbar_apb_periph0_axi_awready;
    logic [31:0] xbar_apb_periph0_axi_wdata;
    logic [3:0] xbar_apb_periph0_axi_wstrb;
    logic                      xbar_apb_periph0_axi_wlast;
    logic                      xbar_apb_periph0_axi_wuser;
    logic                      xbar_apb_periph0_axi_wvalid;
    logic                      xbar_apb_periph0_axi_wready;
    logic [3:0]            xbar_apb_periph0_axi_bid;
    logic [1:0]                xbar_apb_periph0_axi_bresp;
    logic                      xbar_apb_periph0_axi_buser;
    logic                      xbar_apb_periph0_axi_bvalid;
    logic                      xbar_apb_periph0_axi_bready;
    logic [3:0]            xbar_apb_periph0_axi_arid;
    logic [31:0]               xbar_apb_periph0_axi_araddr;
    logic [7:0]                xbar_apb_periph0_axi_arlen;
    logic [2:0]                xbar_apb_periph0_axi_arsize;
    logic [1:0]                xbar_apb_periph0_axi_arburst;
    logic                      xbar_apb_periph0_axi_arlock;
    logic [3:0]                xbar_apb_periph0_axi_arcache;
    logic [2:0]                xbar_apb_periph0_axi_arprot;
    logic [3:0]                xbar_apb_periph0_axi_arqos;
    logic [3:0]                xbar_apb_periph0_axi_arregion;
    logic                      xbar_apb_periph0_axi_aruser;
    logic                      xbar_apb_periph0_axi_arvalid;
    logic                      xbar_apb_periph0_axi_arready;
    logic [3:0]            xbar_apb_periph0_axi_rid;
    logic [31:0] xbar_apb_periph0_axi_rdata;
    logic [1:0]                xbar_apb_periph0_axi_rresp;
    logic                      xbar_apb_periph0_axi_rlast;
    logic                      xbar_apb_periph0_axi_ruser;
    logic                      xbar_apb_periph0_axi_rvalid;
    logic                      xbar_apb_periph0_axi_rready;
    logic [BRIDGE_ID_WIDTH-1:0] apb_periph0_axi_bridge_id_aw;
    logic [BRIDGE_ID_WIDTH-1:0] apb_periph0_axi_bid_bridge_id;
    logic                       apb_periph0_axi_bid_valid;
    logic [BRIDGE_ID_WIDTH-1:0] apb_periph0_axi_bridge_id_ar;
    logic [BRIDGE_ID_WIDTH-1:0] apb_periph0_axi_rid_bridge_id;
    logic                       apb_periph0_axi_rid_valid;

    // ================================================================
    // CPU_AXI4 Adapter
    // ================================================================
    cpu_axi4_adapter u_cpu_axi4_adapter (
        .aclk(aclk),
        .aresetn(aresetn),

        // External interface
        .cpu_axi_awid(cpu_axi_awid),
        .cpu_axi_awaddr(cpu_axi_awaddr),
        .cpu_axi_awlen(cpu_axi_awlen),
        .cpu_axi_awsize(cpu_axi_awsize),
        .cpu_axi_awburst(cpu_axi_awburst),
        .cpu_axi_awlock(cpu_axi_awlock),
        .cpu_axi_awcache(cpu_axi_awcache),
        .cpu_axi_awprot(cpu_axi_awprot),
        .cpu_axi_awqos(cpu_axi_awqos),
        .cpu_axi_awregion(cpu_axi_awregion),
        .cpu_axi_awuser(cpu_axi_awuser),
        .cpu_axi_awvalid(cpu_axi_awvalid),
        .cpu_axi_awready(cpu_axi_awready),
        .cpu_axi_wdata(cpu_axi_wdata),
        .cpu_axi_wstrb(cpu_axi_wstrb),
        .cpu_axi_wlast(cpu_axi_wlast),
        .cpu_axi_wuser(cpu_axi_wuser),
        .cpu_axi_wvalid(cpu_axi_wvalid),
        .cpu_axi_wready(cpu_axi_wready),
        .cpu_axi_bid(cpu_axi_bid),
        .cpu_axi_bresp(cpu_axi_bresp),
        .cpu_axi_buser(cpu_axi_buser),
        .cpu_axi_bvalid(cpu_axi_bvalid),
        .cpu_axi_bready(cpu_axi_bready),
        .cpu_axi_arid(cpu_axi_arid),
        .cpu_axi_araddr(cpu_axi_araddr),
        .cpu_axi_arlen(cpu_axi_arlen),
        .cpu_axi_arsize(cpu_axi_arsize),
        .cpu_axi_arburst(cpu_axi_arburst),
        .cpu_axi_arlock(cpu_axi_arlock),
        .cpu_axi_arcache(cpu_axi_arcache),
        .cpu_axi_arprot(cpu_axi_arprot),
        .cpu_axi_arqos(cpu_axi_arqos),
        .cpu_axi_arregion(cpu_axi_arregion),
        .cpu_axi_aruser(cpu_axi_aruser),
        .cpu_axi_arvalid(cpu_axi_arvalid),
        .cpu_axi_arready(cpu_axi_arready),
        .cpu_axi_rid(cpu_axi_rid),
        .cpu_axi_rdata(cpu_axi_rdata),
        .cpu_axi_rresp(cpu_axi_rresp),
        .cpu_axi_rlast(cpu_axi_rlast),
        .cpu_axi_ruser(cpu_axi_ruser),
        .cpu_axi_rvalid(cpu_axi_rvalid),
        .cpu_axi_rready(cpu_axi_rready),

        // Decode outputs
        .slave_select_aw(cpu_axi4_slave_select_aw),
        .bridge_id_aw(cpu_axi4_bridge_id_aw),
        .slave_select_ar(cpu_axi4_slave_select_ar),
        .bridge_id_ar(cpu_axi4_bridge_id_ar),

        // 32b path
        .cpu_axi4_32b_aw(cpu_axi4_32b_aw),
        .cpu_axi4_32b_awvalid(cpu_axi4_32b_awvalid),
        .cpu_axi4_32b_awready(cpu_axi4_32b_awready),
        .cpu_axi4_32b_w(cpu_axi4_32b_w),
        .cpu_axi4_32b_wvalid(cpu_axi4_32b_wvalid),
        .cpu_axi4_32b_wready(cpu_axi4_32b_wready),
        .cpu_axi4_32b_b(cpu_axi4_32b_b),
        .cpu_axi4_32b_bvalid(cpu_axi4_32b_bvalid),
        .cpu_axi4_32b_bready(cpu_axi4_32b_bready),
        .cpu_axi4_32b_ar(cpu_axi4_32b_ar),
        .cpu_axi4_32b_arvalid(cpu_axi4_32b_arvalid),
        .cpu_axi4_32b_arready(cpu_axi4_32b_arready),
        .cpu_axi4_32b_r(cpu_axi4_32b_r),
        .cpu_axi4_32b_rvalid(cpu_axi4_32b_rvalid),
        .cpu_axi4_32b_rready(cpu_axi4_32b_rready),

        // 64b path
        .cpu_axi4_64b_aw(cpu_axi4_64b_aw),
        .cpu_axi4_64b_awvalid(cpu_axi4_64b_awvalid),
        .cpu_axi4_64b_awready(cpu_axi4_64b_awready),
        .cpu_axi4_64b_w(cpu_axi4_64b_w),
        .cpu_axi4_64b_wvalid(cpu_axi4_64b_wvalid),
        .cpu_axi4_64b_wready(cpu_axi4_64b_wready),
        .cpu_axi4_64b_b(cpu_axi4_64b_b),
        .cpu_axi4_64b_bvalid(cpu_axi4_64b_bvalid),
        .cpu_axi4_64b_bready(cpu_axi4_64b_bready),
        .cpu_axi4_64b_ar(cpu_axi4_64b_ar),
        .cpu_axi4_64b_arvalid(cpu_axi4_64b_arvalid),
        .cpu_axi4_64b_arready(cpu_axi4_64b_arready),
        .cpu_axi4_64b_r(cpu_axi4_64b_r),
        .cpu_axi4_64b_rvalid(cpu_axi4_64b_rvalid),
        .cpu_axi4_64b_rready(cpu_axi4_64b_rready),

        // 128b path
        .cpu_axi4_128b_aw(cpu_axi4_128b_aw),
        .cpu_axi4_128b_awvalid(cpu_axi4_128b_awvalid),
        .cpu_axi4_128b_awready(cpu_axi4_128b_awready),
        .cpu_axi4_128b_w(cpu_axi4_128b_w),
        .cpu_axi4_128b_wvalid(cpu_axi4_128b_wvalid),
        .cpu_axi4_128b_wready(cpu_axi4_128b_wready),
        .cpu_axi4_128b_b(cpu_axi4_128b_b),
        .cpu_axi4_128b_bvalid(cpu_axi4_128b_bvalid),
        .cpu_axi4_128b_bready(cpu_axi4_128b_bready),
        .cpu_axi4_128b_ar(cpu_axi4_128b_ar),
        .cpu_axi4_128b_arvalid(cpu_axi4_128b_arvalid),
        .cpu_axi4_128b_arready(cpu_axi4_128b_arready),
        .cpu_axi4_128b_r(cpu_axi4_128b_r),
        .cpu_axi4_128b_rvalid(cpu_axi4_128b_rvalid),
        .cpu_axi4_128b_rready(cpu_axi4_128b_rready)
    );

    // ================================================================
    // DMA_AXI4 Adapter
    // ================================================================
    dma_axi4_adapter u_dma_axi4_adapter (
        .aclk(aclk),
        .aresetn(aresetn),

        // External interface
        .dma_axi_awid(dma_axi_awid),
        .dma_axi_awaddr(dma_axi_awaddr),
        .dma_axi_awlen(dma_axi_awlen),
        .dma_axi_awsize(dma_axi_awsize),
        .dma_axi_awburst(dma_axi_awburst),
        .dma_axi_awlock(dma_axi_awlock),
        .dma_axi_awcache(dma_axi_awcache),
        .dma_axi_awprot(dma_axi_awprot),
        .dma_axi_awqos(dma_axi_awqos),
        .dma_axi_awregion(dma_axi_awregion),
        .dma_axi_awuser(dma_axi_awuser),
        .dma_axi_awvalid(dma_axi_awvalid),
        .dma_axi_awready(dma_axi_awready),
        .dma_axi_wdata(dma_axi_wdata),
        .dma_axi_wstrb(dma_axi_wstrb),
        .dma_axi_wlast(dma_axi_wlast),
        .dma_axi_wuser(dma_axi_wuser),
        .dma_axi_wvalid(dma_axi_wvalid),
        .dma_axi_wready(dma_axi_wready),
        .dma_axi_bid(dma_axi_bid),
        .dma_axi_bresp(dma_axi_bresp),
        .dma_axi_buser(dma_axi_buser),
        .dma_axi_bvalid(dma_axi_bvalid),
        .dma_axi_bready(dma_axi_bready),
        .dma_axi_arid(dma_axi_arid),
        .dma_axi_araddr(dma_axi_araddr),
        .dma_axi_arlen(dma_axi_arlen),
        .dma_axi_arsize(dma_axi_arsize),
        .dma_axi_arburst(dma_axi_arburst),
        .dma_axi_arlock(dma_axi_arlock),
        .dma_axi_arcache(dma_axi_arcache),
        .dma_axi_arprot(dma_axi_arprot),
        .dma_axi_arqos(dma_axi_arqos),
        .dma_axi_arregion(dma_axi_arregion),
        .dma_axi_aruser(dma_axi_aruser),
        .dma_axi_arvalid(dma_axi_arvalid),
        .dma_axi_arready(dma_axi_arready),
        .dma_axi_rid(dma_axi_rid),
        .dma_axi_rdata(dma_axi_rdata),
        .dma_axi_rresp(dma_axi_rresp),
        .dma_axi_rlast(dma_axi_rlast),
        .dma_axi_ruser(dma_axi_ruser),
        .dma_axi_rvalid(dma_axi_rvalid),
        .dma_axi_rready(dma_axi_rready),

        // Decode outputs
        .slave_select_aw(dma_axi4_slave_select_aw),
        .bridge_id_aw(dma_axi4_bridge_id_aw),
        .slave_select_ar(dma_axi4_slave_select_ar),
        .bridge_id_ar(dma_axi4_bridge_id_ar),

        // 32b path
        .dma_axi4_32b_aw(dma_axi4_32b_aw),
        .dma_axi4_32b_awvalid(dma_axi4_32b_awvalid),
        .dma_axi4_32b_awready(dma_axi4_32b_awready),
        .dma_axi4_32b_w(dma_axi4_32b_w),
        .dma_axi4_32b_wvalid(dma_axi4_32b_wvalid),
        .dma_axi4_32b_wready(dma_axi4_32b_wready),
        .dma_axi4_32b_b(dma_axi4_32b_b),
        .dma_axi4_32b_bvalid(dma_axi4_32b_bvalid),
        .dma_axi4_32b_bready(dma_axi4_32b_bready),
        .dma_axi4_32b_ar(dma_axi4_32b_ar),
        .dma_axi4_32b_arvalid(dma_axi4_32b_arvalid),
        .dma_axi4_32b_arready(dma_axi4_32b_arready),
        .dma_axi4_32b_r(dma_axi4_32b_r),
        .dma_axi4_32b_rvalid(dma_axi4_32b_rvalid),
        .dma_axi4_32b_rready(dma_axi4_32b_rready),

        // 64b path
        .dma_axi4_64b_aw(dma_axi4_64b_aw),
        .dma_axi4_64b_awvalid(dma_axi4_64b_awvalid),
        .dma_axi4_64b_awready(dma_axi4_64b_awready),
        .dma_axi4_64b_w(dma_axi4_64b_w),
        .dma_axi4_64b_wvalid(dma_axi4_64b_wvalid),
        .dma_axi4_64b_wready(dma_axi4_64b_wready),
        .dma_axi4_64b_b(dma_axi4_64b_b),
        .dma_axi4_64b_bvalid(dma_axi4_64b_bvalid),
        .dma_axi4_64b_bready(dma_axi4_64b_bready),
        .dma_axi4_64b_ar(dma_axi4_64b_ar),
        .dma_axi4_64b_arvalid(dma_axi4_64b_arvalid),
        .dma_axi4_64b_arready(dma_axi4_64b_arready),
        .dma_axi4_64b_r(dma_axi4_64b_r),
        .dma_axi4_64b_rvalid(dma_axi4_64b_rvalid),
        .dma_axi4_64b_rready(dma_axi4_64b_rready),

        // 128b path
        .dma_axi4_128b_aw(dma_axi4_128b_aw),
        .dma_axi4_128b_awvalid(dma_axi4_128b_awvalid),
        .dma_axi4_128b_awready(dma_axi4_128b_awready),
        .dma_axi4_128b_w(dma_axi4_128b_w),
        .dma_axi4_128b_wvalid(dma_axi4_128b_wvalid),
        .dma_axi4_128b_wready(dma_axi4_128b_wready),
        .dma_axi4_128b_b(dma_axi4_128b_b),
        .dma_axi4_128b_bvalid(dma_axi4_128b_bvalid),
        .dma_axi4_128b_bready(dma_axi4_128b_bready),
        .dma_axi4_128b_ar(dma_axi4_128b_ar),
        .dma_axi4_128b_arvalid(dma_axi4_128b_arvalid),
        .dma_axi4_128b_arready(dma_axi4_128b_arready),
        .dma_axi4_128b_r(dma_axi4_128b_r),
        .dma_axi4_128b_rvalid(dma_axi4_128b_rvalid),
        .dma_axi4_128b_rready(dma_axi4_128b_rready)
    );

    // ================================================================
    // HOST_AXIL Adapter
    // ================================================================
    host_axil_adapter u_host_axil_adapter (
        .aclk(aclk),
        .aresetn(aresetn),

        // External interface
        .host_axil_awid(0'h0),
        .host_axil_awaddr(host_axil_awaddr),
        .host_axil_awlen(8'h0),
        .host_axil_awsize(3'd2),
        .host_axil_awburst(2'b01),
        .host_axil_awlock(1'b0),
        .host_axil_awcache(4'h0),
        .host_axil_awprot(host_axil_awprot),
        .host_axil_awqos(4'h0),
        .host_axil_awregion(4'h0),
        .host_axil_awuser(1'b0),
        .host_axil_awvalid(host_axil_awvalid),
        .host_axil_awready(host_axil_awready),
        .host_axil_wdata(host_axil_wdata),
        .host_axil_wstrb(host_axil_wstrb),
        .host_axil_wlast(1'b1),
        .host_axil_wuser(1'b0),
        .host_axil_wvalid(host_axil_wvalid),
        .host_axil_wready(host_axil_wready),
        .host_axil_bid(),
        .host_axil_bresp(host_axil_bresp),
        .host_axil_buser(),
        .host_axil_bvalid(host_axil_bvalid),
        .host_axil_bready(host_axil_bready),
        .host_axil_arid(0'h0),
        .host_axil_araddr(host_axil_araddr),
        .host_axil_arlen(8'h0),
        .host_axil_arsize(3'd2),
        .host_axil_arburst(2'b01),
        .host_axil_arlock(1'b0),
        .host_axil_arcache(4'h0),
        .host_axil_arprot(host_axil_arprot),
        .host_axil_arqos(4'h0),
        .host_axil_arregion(4'h0),
        .host_axil_aruser(1'b0),
        .host_axil_arvalid(host_axil_arvalid),
        .host_axil_arready(host_axil_arready),
        .host_axil_rid(),
        .host_axil_rdata(host_axil_rdata),
        .host_axil_rresp(host_axil_rresp),
        .host_axil_rlast(),
        .host_axil_ruser(),
        .host_axil_rvalid(host_axil_rvalid),
        .host_axil_rready(host_axil_rready),

        // Decode outputs
        .slave_select_aw(host_axil_slave_select_aw),
        .bridge_id_aw(host_axil_bridge_id_aw),
        .slave_select_ar(host_axil_slave_select_ar),
        .bridge_id_ar(host_axil_bridge_id_ar),

        // 32b path
        .host_axil_32b_aw(host_axil_32b_aw),
        .host_axil_32b_awvalid(host_axil_32b_awvalid),
        .host_axil_32b_awready(host_axil_32b_awready),
        .host_axil_32b_w(host_axil_32b_w),
        .host_axil_32b_wvalid(host_axil_32b_wvalid),
        .host_axil_32b_wready(host_axil_32b_wready),
        .host_axil_32b_b(host_axil_32b_b),
        .host_axil_32b_bvalid(host_axil_32b_bvalid),
        .host_axil_32b_bready(host_axil_32b_bready),
        .host_axil_32b_ar(host_axil_32b_ar),
        .host_axil_32b_arvalid(host_axil_32b_arvalid),
        .host_axil_32b_arready(host_axil_32b_arready),
        .host_axil_32b_r(host_axil_32b_r),
        .host_axil_32b_rvalid(host_axil_32b_rvalid),
        .host_axil_32b_rready(host_axil_32b_rready),

        // 64b path
        .host_axil_64b_aw(host_axil_64b_aw),
        .host_axil_64b_awvalid(host_axil_64b_awvalid),
        .host_axil_64b_awready(host_axil_64b_awready),
        .host_axil_64b_w(host_axil_64b_w),
        .host_axil_64b_wvalid(host_axil_64b_wvalid),
        .host_axil_64b_wready(host_axil_64b_wready),
        .host_axil_64b_b(host_axil_64b_b),
        .host_axil_64b_bvalid(host_axil_64b_bvalid),
        .host_axil_64b_bready(host_axil_64b_bready),
        .host_axil_64b_ar(host_axil_64b_ar),
        .host_axil_64b_arvalid(host_axil_64b_arvalid),
        .host_axil_64b_arready(host_axil_64b_arready),
        .host_axil_64b_r(host_axil_64b_r),
        .host_axil_64b_rvalid(host_axil_64b_rvalid),
        .host_axil_64b_rready(host_axil_64b_rready)
    );

    // ================================================================
    // Crossbar Module Instantiation
    // ================================================================
    bridge_b_axi4_axil_3x5_xbar u_xbar (
        .aclk(aclk),
        .aresetn(aresetn),

        // cpu_axi4 adapter outputs
        .cpu_axi4_slave_select_aw(cpu_axi4_slave_select_aw),
        .cpu_axi4_bridge_id_aw(cpu_axi4_bridge_id_aw),
        .cpu_axi4_slave_select_ar(cpu_axi4_slave_select_ar),
        .cpu_axi4_bridge_id_ar(cpu_axi4_bridge_id_ar),
        // 32b path
        .cpu_axi4_32b_aw(cpu_axi4_32b_aw),
        .cpu_axi4_32b_awvalid(cpu_axi4_32b_awvalid),
        .cpu_axi4_32b_awready(cpu_axi4_32b_awready),
        .cpu_axi4_32b_w(cpu_axi4_32b_w),
        .cpu_axi4_32b_wvalid(cpu_axi4_32b_wvalid),
        .cpu_axi4_32b_wready(cpu_axi4_32b_wready),
        .cpu_axi4_32b_b(cpu_axi4_32b_b),
        .cpu_axi4_32b_bvalid(cpu_axi4_32b_bvalid),
        .cpu_axi4_32b_bready(cpu_axi4_32b_bready),
        .cpu_axi4_32b_ar(cpu_axi4_32b_ar),
        .cpu_axi4_32b_arvalid(cpu_axi4_32b_arvalid),
        .cpu_axi4_32b_arready(cpu_axi4_32b_arready),
        .cpu_axi4_32b_r(cpu_axi4_32b_r),
        .cpu_axi4_32b_rvalid(cpu_axi4_32b_rvalid),
        .cpu_axi4_32b_rready(cpu_axi4_32b_rready),
        // 64b path
        .cpu_axi4_64b_aw(cpu_axi4_64b_aw),
        .cpu_axi4_64b_awvalid(cpu_axi4_64b_awvalid),
        .cpu_axi4_64b_awready(cpu_axi4_64b_awready),
        .cpu_axi4_64b_w(cpu_axi4_64b_w),
        .cpu_axi4_64b_wvalid(cpu_axi4_64b_wvalid),
        .cpu_axi4_64b_wready(cpu_axi4_64b_wready),
        .cpu_axi4_64b_b(cpu_axi4_64b_b),
        .cpu_axi4_64b_bvalid(cpu_axi4_64b_bvalid),
        .cpu_axi4_64b_bready(cpu_axi4_64b_bready),
        .cpu_axi4_64b_ar(cpu_axi4_64b_ar),
        .cpu_axi4_64b_arvalid(cpu_axi4_64b_arvalid),
        .cpu_axi4_64b_arready(cpu_axi4_64b_arready),
        .cpu_axi4_64b_r(cpu_axi4_64b_r),
        .cpu_axi4_64b_rvalid(cpu_axi4_64b_rvalid),
        .cpu_axi4_64b_rready(cpu_axi4_64b_rready),
        // 128b path
        .cpu_axi4_128b_aw(cpu_axi4_128b_aw),
        .cpu_axi4_128b_awvalid(cpu_axi4_128b_awvalid),
        .cpu_axi4_128b_awready(cpu_axi4_128b_awready),
        .cpu_axi4_128b_w(cpu_axi4_128b_w),
        .cpu_axi4_128b_wvalid(cpu_axi4_128b_wvalid),
        .cpu_axi4_128b_wready(cpu_axi4_128b_wready),
        .cpu_axi4_128b_b(cpu_axi4_128b_b),
        .cpu_axi4_128b_bvalid(cpu_axi4_128b_bvalid),
        .cpu_axi4_128b_bready(cpu_axi4_128b_bready),
        .cpu_axi4_128b_ar(cpu_axi4_128b_ar),
        .cpu_axi4_128b_arvalid(cpu_axi4_128b_arvalid),
        .cpu_axi4_128b_arready(cpu_axi4_128b_arready),
        .cpu_axi4_128b_r(cpu_axi4_128b_r),
        .cpu_axi4_128b_rvalid(cpu_axi4_128b_rvalid),
        .cpu_axi4_128b_rready(cpu_axi4_128b_rready),

        // dma_axi4 adapter outputs
        .dma_axi4_slave_select_aw(dma_axi4_slave_select_aw),
        .dma_axi4_bridge_id_aw(dma_axi4_bridge_id_aw),
        .dma_axi4_slave_select_ar(dma_axi4_slave_select_ar),
        .dma_axi4_bridge_id_ar(dma_axi4_bridge_id_ar),
        // 32b path
        .dma_axi4_32b_aw(dma_axi4_32b_aw),
        .dma_axi4_32b_awvalid(dma_axi4_32b_awvalid),
        .dma_axi4_32b_awready(dma_axi4_32b_awready),
        .dma_axi4_32b_w(dma_axi4_32b_w),
        .dma_axi4_32b_wvalid(dma_axi4_32b_wvalid),
        .dma_axi4_32b_wready(dma_axi4_32b_wready),
        .dma_axi4_32b_b(dma_axi4_32b_b),
        .dma_axi4_32b_bvalid(dma_axi4_32b_bvalid),
        .dma_axi4_32b_bready(dma_axi4_32b_bready),
        .dma_axi4_32b_ar(dma_axi4_32b_ar),
        .dma_axi4_32b_arvalid(dma_axi4_32b_arvalid),
        .dma_axi4_32b_arready(dma_axi4_32b_arready),
        .dma_axi4_32b_r(dma_axi4_32b_r),
        .dma_axi4_32b_rvalid(dma_axi4_32b_rvalid),
        .dma_axi4_32b_rready(dma_axi4_32b_rready),
        // 64b path
        .dma_axi4_64b_aw(dma_axi4_64b_aw),
        .dma_axi4_64b_awvalid(dma_axi4_64b_awvalid),
        .dma_axi4_64b_awready(dma_axi4_64b_awready),
        .dma_axi4_64b_w(dma_axi4_64b_w),
        .dma_axi4_64b_wvalid(dma_axi4_64b_wvalid),
        .dma_axi4_64b_wready(dma_axi4_64b_wready),
        .dma_axi4_64b_b(dma_axi4_64b_b),
        .dma_axi4_64b_bvalid(dma_axi4_64b_bvalid),
        .dma_axi4_64b_bready(dma_axi4_64b_bready),
        .dma_axi4_64b_ar(dma_axi4_64b_ar),
        .dma_axi4_64b_arvalid(dma_axi4_64b_arvalid),
        .dma_axi4_64b_arready(dma_axi4_64b_arready),
        .dma_axi4_64b_r(dma_axi4_64b_r),
        .dma_axi4_64b_rvalid(dma_axi4_64b_rvalid),
        .dma_axi4_64b_rready(dma_axi4_64b_rready),
        // 128b path
        .dma_axi4_128b_aw(dma_axi4_128b_aw),
        .dma_axi4_128b_awvalid(dma_axi4_128b_awvalid),
        .dma_axi4_128b_awready(dma_axi4_128b_awready),
        .dma_axi4_128b_w(dma_axi4_128b_w),
        .dma_axi4_128b_wvalid(dma_axi4_128b_wvalid),
        .dma_axi4_128b_wready(dma_axi4_128b_wready),
        .dma_axi4_128b_b(dma_axi4_128b_b),
        .dma_axi4_128b_bvalid(dma_axi4_128b_bvalid),
        .dma_axi4_128b_bready(dma_axi4_128b_bready),
        .dma_axi4_128b_ar(dma_axi4_128b_ar),
        .dma_axi4_128b_arvalid(dma_axi4_128b_arvalid),
        .dma_axi4_128b_arready(dma_axi4_128b_arready),
        .dma_axi4_128b_r(dma_axi4_128b_r),
        .dma_axi4_128b_rvalid(dma_axi4_128b_rvalid),
        .dma_axi4_128b_rready(dma_axi4_128b_rready),

        // host_axil adapter outputs
        .host_axil_slave_select_aw(host_axil_slave_select_aw),
        .host_axil_bridge_id_aw(host_axil_bridge_id_aw),
        .host_axil_slave_select_ar(host_axil_slave_select_ar),
        .host_axil_bridge_id_ar(host_axil_bridge_id_ar),
        // 32b path
        .host_axil_32b_aw(host_axil_32b_aw),
        .host_axil_32b_awvalid(host_axil_32b_awvalid),
        .host_axil_32b_awready(host_axil_32b_awready),
        .host_axil_32b_w(host_axil_32b_w),
        .host_axil_32b_wvalid(host_axil_32b_wvalid),
        .host_axil_32b_wready(host_axil_32b_wready),
        .host_axil_32b_b(host_axil_32b_b),
        .host_axil_32b_bvalid(host_axil_32b_bvalid),
        .host_axil_32b_bready(host_axil_32b_bready),
        .host_axil_32b_ar(host_axil_32b_ar),
        .host_axil_32b_arvalid(host_axil_32b_arvalid),
        .host_axil_32b_arready(host_axil_32b_arready),
        .host_axil_32b_r(host_axil_32b_r),
        .host_axil_32b_rvalid(host_axil_32b_rvalid),
        .host_axil_32b_rready(host_axil_32b_rready),
        // 64b path
        .host_axil_64b_aw(host_axil_64b_aw),
        .host_axil_64b_awvalid(host_axil_64b_awvalid),
        .host_axil_64b_awready(host_axil_64b_awready),
        .host_axil_64b_w(host_axil_64b_w),
        .host_axil_64b_wvalid(host_axil_64b_wvalid),
        .host_axil_64b_wready(host_axil_64b_wready),
        .host_axil_64b_b(host_axil_64b_b),
        .host_axil_64b_bvalid(host_axil_64b_bvalid),
        .host_axil_64b_bready(host_axil_64b_bready),
        .host_axil_64b_ar(host_axil_64b_ar),
        .host_axil_64b_arvalid(host_axil_64b_arvalid),
        .host_axil_64b_arready(host_axil_64b_arready),
        .host_axil_64b_r(host_axil_64b_r),
        .host_axil_64b_rvalid(host_axil_64b_rvalid),
        .host_axil_64b_rready(host_axil_64b_rready),

        // Slave 0: ddr0
        .ddr0_axi_awid(xbar_ddr0_axi_awid),
        .ddr0_axi_awaddr(xbar_ddr0_axi_awaddr),
        .ddr0_axi_awlen(xbar_ddr0_axi_awlen),
        .ddr0_axi_awsize(xbar_ddr0_axi_awsize),
        .ddr0_axi_awburst(xbar_ddr0_axi_awburst),
        .ddr0_axi_awlock(xbar_ddr0_axi_awlock),
        .ddr0_axi_awcache(xbar_ddr0_axi_awcache),
        .ddr0_axi_awprot(xbar_ddr0_axi_awprot),
        .ddr0_axi_awqos(xbar_ddr0_axi_awqos),
        .ddr0_axi_awregion(xbar_ddr0_axi_awregion),
        .ddr0_axi_awuser(xbar_ddr0_axi_awuser),
        .ddr0_axi_awvalid(xbar_ddr0_axi_awvalid),
        .ddr0_axi_awready(xbar_ddr0_axi_awready),
        .ddr0_axi_wdata(xbar_ddr0_axi_wdata),
        .ddr0_axi_wstrb(xbar_ddr0_axi_wstrb),
        .ddr0_axi_wlast(xbar_ddr0_axi_wlast),
        .ddr0_axi_wuser(xbar_ddr0_axi_wuser),
        .ddr0_axi_wvalid(xbar_ddr0_axi_wvalid),
        .ddr0_axi_wready(xbar_ddr0_axi_wready),
        .ddr0_axi_bid(xbar_ddr0_axi_bid),
        .ddr0_axi_bresp(xbar_ddr0_axi_bresp),
        .ddr0_axi_buser(xbar_ddr0_axi_buser),
        .ddr0_axi_bvalid(xbar_ddr0_axi_bvalid),
        .ddr0_axi_bready(xbar_ddr0_axi_bready),
        .ddr0_axi_arid(xbar_ddr0_axi_arid),
        .ddr0_axi_araddr(xbar_ddr0_axi_araddr),
        .ddr0_axi_arlen(xbar_ddr0_axi_arlen),
        .ddr0_axi_arsize(xbar_ddr0_axi_arsize),
        .ddr0_axi_arburst(xbar_ddr0_axi_arburst),
        .ddr0_axi_arlock(xbar_ddr0_axi_arlock),
        .ddr0_axi_arcache(xbar_ddr0_axi_arcache),
        .ddr0_axi_arprot(xbar_ddr0_axi_arprot),
        .ddr0_axi_arqos(xbar_ddr0_axi_arqos),
        .ddr0_axi_arregion(xbar_ddr0_axi_arregion),
        .ddr0_axi_aruser(xbar_ddr0_axi_aruser),
        .ddr0_axi_arvalid(xbar_ddr0_axi_arvalid),
        .ddr0_axi_arready(xbar_ddr0_axi_arready),
        .ddr0_axi_rid(xbar_ddr0_axi_rid),
        .ddr0_axi_rdata(xbar_ddr0_axi_rdata),
        .ddr0_axi_rresp(xbar_ddr0_axi_rresp),
        .ddr0_axi_rlast(xbar_ddr0_axi_rlast),
        .ddr0_axi_ruser(xbar_ddr0_axi_ruser),
        .ddr0_axi_rvalid(xbar_ddr0_axi_rvalid),
        .ddr0_axi_rready(xbar_ddr0_axi_rready),
        .ddr0_axi_bridge_id_aw(ddr0_axi_bridge_id_aw),
        .ddr0_axi_bid_bridge_id(ddr0_axi_bid_bridge_id),
        .ddr0_axi_bid_valid(ddr0_axi_bid_valid),

        .ddr0_axi_bridge_id_ar(ddr0_axi_bridge_id_ar),
        .ddr0_axi_rid_bridge_id(ddr0_axi_rid_bridge_id),
        .ddr0_axi_rid_valid(ddr0_axi_rid_valid),

        // Slave 1: sram
        .sram_axi_awid(xbar_sram_axi_awid),
        .sram_axi_awaddr(xbar_sram_axi_awaddr),
        .sram_axi_awlen(xbar_sram_axi_awlen),
        .sram_axi_awsize(xbar_sram_axi_awsize),
        .sram_axi_awburst(xbar_sram_axi_awburst),
        .sram_axi_awlock(xbar_sram_axi_awlock),
        .sram_axi_awcache(xbar_sram_axi_awcache),
        .sram_axi_awprot(xbar_sram_axi_awprot),
        .sram_axi_awqos(xbar_sram_axi_awqos),
        .sram_axi_awregion(xbar_sram_axi_awregion),
        .sram_axi_awuser(xbar_sram_axi_awuser),
        .sram_axi_awvalid(xbar_sram_axi_awvalid),
        .sram_axi_awready(xbar_sram_axi_awready),
        .sram_axi_wdata(xbar_sram_axi_wdata),
        .sram_axi_wstrb(xbar_sram_axi_wstrb),
        .sram_axi_wlast(xbar_sram_axi_wlast),
        .sram_axi_wuser(xbar_sram_axi_wuser),
        .sram_axi_wvalid(xbar_sram_axi_wvalid),
        .sram_axi_wready(xbar_sram_axi_wready),
        .sram_axi_bid(xbar_sram_axi_bid),
        .sram_axi_bresp(xbar_sram_axi_bresp),
        .sram_axi_buser(xbar_sram_axi_buser),
        .sram_axi_bvalid(xbar_sram_axi_bvalid),
        .sram_axi_bready(xbar_sram_axi_bready),
        .sram_axi_arid(xbar_sram_axi_arid),
        .sram_axi_araddr(xbar_sram_axi_araddr),
        .sram_axi_arlen(xbar_sram_axi_arlen),
        .sram_axi_arsize(xbar_sram_axi_arsize),
        .sram_axi_arburst(xbar_sram_axi_arburst),
        .sram_axi_arlock(xbar_sram_axi_arlock),
        .sram_axi_arcache(xbar_sram_axi_arcache),
        .sram_axi_arprot(xbar_sram_axi_arprot),
        .sram_axi_arqos(xbar_sram_axi_arqos),
        .sram_axi_arregion(xbar_sram_axi_arregion),
        .sram_axi_aruser(xbar_sram_axi_aruser),
        .sram_axi_arvalid(xbar_sram_axi_arvalid),
        .sram_axi_arready(xbar_sram_axi_arready),
        .sram_axi_rid(xbar_sram_axi_rid),
        .sram_axi_rdata(xbar_sram_axi_rdata),
        .sram_axi_rresp(xbar_sram_axi_rresp),
        .sram_axi_rlast(xbar_sram_axi_rlast),
        .sram_axi_ruser(xbar_sram_axi_ruser),
        .sram_axi_rvalid(xbar_sram_axi_rvalid),
        .sram_axi_rready(xbar_sram_axi_rready),
        .sram_axi_bridge_id_aw(sram_axi_bridge_id_aw),
        .sram_axi_bid_bridge_id(sram_axi_bid_bridge_id),
        .sram_axi_bid_valid(sram_axi_bid_valid),

        .sram_axi_bridge_id_ar(sram_axi_bridge_id_ar),
        .sram_axi_rid_bridge_id(sram_axi_rid_bridge_id),
        .sram_axi_rid_valid(sram_axi_rid_valid),

        // Slave 2: axil_periph0
        .axil_periph0_axi_awid(xbar_axil_periph0_axi_awid),
        .axil_periph0_axi_awaddr(xbar_axil_periph0_axi_awaddr),
        .axil_periph0_axi_awlen(xbar_axil_periph0_axi_awlen),
        .axil_periph0_axi_awsize(xbar_axil_periph0_axi_awsize),
        .axil_periph0_axi_awburst(xbar_axil_periph0_axi_awburst),
        .axil_periph0_axi_awlock(xbar_axil_periph0_axi_awlock),
        .axil_periph0_axi_awcache(xbar_axil_periph0_axi_awcache),
        .axil_periph0_axi_awprot(xbar_axil_periph0_axi_awprot),
        .axil_periph0_axi_awqos(xbar_axil_periph0_axi_awqos),
        .axil_periph0_axi_awregion(xbar_axil_periph0_axi_awregion),
        .axil_periph0_axi_awuser(xbar_axil_periph0_axi_awuser),
        .axil_periph0_axi_awvalid(xbar_axil_periph0_axi_awvalid),
        .axil_periph0_axi_awready(xbar_axil_periph0_axi_awready),
        .axil_periph0_axi_wdata(xbar_axil_periph0_axi_wdata),
        .axil_periph0_axi_wstrb(xbar_axil_periph0_axi_wstrb),
        .axil_periph0_axi_wlast(xbar_axil_periph0_axi_wlast),
        .axil_periph0_axi_wuser(xbar_axil_periph0_axi_wuser),
        .axil_periph0_axi_wvalid(xbar_axil_periph0_axi_wvalid),
        .axil_periph0_axi_wready(xbar_axil_periph0_axi_wready),
        .axil_periph0_axi_bid(xbar_axil_periph0_axi_bid),
        .axil_periph0_axi_bresp(xbar_axil_periph0_axi_bresp),
        .axil_periph0_axi_buser(xbar_axil_periph0_axi_buser),
        .axil_periph0_axi_bvalid(xbar_axil_periph0_axi_bvalid),
        .axil_periph0_axi_bready(xbar_axil_periph0_axi_bready),
        .axil_periph0_axi_arid(xbar_axil_periph0_axi_arid),
        .axil_periph0_axi_araddr(xbar_axil_periph0_axi_araddr),
        .axil_periph0_axi_arlen(xbar_axil_periph0_axi_arlen),
        .axil_periph0_axi_arsize(xbar_axil_periph0_axi_arsize),
        .axil_periph0_axi_arburst(xbar_axil_periph0_axi_arburst),
        .axil_periph0_axi_arlock(xbar_axil_periph0_axi_arlock),
        .axil_periph0_axi_arcache(xbar_axil_periph0_axi_arcache),
        .axil_periph0_axi_arprot(xbar_axil_periph0_axi_arprot),
        .axil_periph0_axi_arqos(xbar_axil_periph0_axi_arqos),
        .axil_periph0_axi_arregion(xbar_axil_periph0_axi_arregion),
        .axil_periph0_axi_aruser(xbar_axil_periph0_axi_aruser),
        .axil_periph0_axi_arvalid(xbar_axil_periph0_axi_arvalid),
        .axil_periph0_axi_arready(xbar_axil_periph0_axi_arready),
        .axil_periph0_axi_rid(xbar_axil_periph0_axi_rid),
        .axil_periph0_axi_rdata(xbar_axil_periph0_axi_rdata),
        .axil_periph0_axi_rresp(xbar_axil_periph0_axi_rresp),
        .axil_periph0_axi_rlast(xbar_axil_periph0_axi_rlast),
        .axil_periph0_axi_ruser(xbar_axil_periph0_axi_ruser),
        .axil_periph0_axi_rvalid(xbar_axil_periph0_axi_rvalid),
        .axil_periph0_axi_rready(xbar_axil_periph0_axi_rready),
        .axil_periph0_axi_bridge_id_aw(axil_periph0_axi_bridge_id_aw),
        .axil_periph0_axi_bid_bridge_id(axil_periph0_axi_bid_bridge_id),
        .axil_periph0_axi_bid_valid(axil_periph0_axi_bid_valid),

        .axil_periph0_axi_bridge_id_ar(axil_periph0_axi_bridge_id_ar),
        .axil_periph0_axi_rid_bridge_id(axil_periph0_axi_rid_bridge_id),
        .axil_periph0_axi_rid_valid(axil_periph0_axi_rid_valid),

        // Slave 3: axil_periph1
        .axil_periph1_axi_awid(xbar_axil_periph1_axi_awid),
        .axil_periph1_axi_awaddr(xbar_axil_periph1_axi_awaddr),
        .axil_periph1_axi_awlen(xbar_axil_periph1_axi_awlen),
        .axil_periph1_axi_awsize(xbar_axil_periph1_axi_awsize),
        .axil_periph1_axi_awburst(xbar_axil_periph1_axi_awburst),
        .axil_periph1_axi_awlock(xbar_axil_periph1_axi_awlock),
        .axil_periph1_axi_awcache(xbar_axil_periph1_axi_awcache),
        .axil_periph1_axi_awprot(xbar_axil_periph1_axi_awprot),
        .axil_periph1_axi_awqos(xbar_axil_periph1_axi_awqos),
        .axil_periph1_axi_awregion(xbar_axil_periph1_axi_awregion),
        .axil_periph1_axi_awuser(xbar_axil_periph1_axi_awuser),
        .axil_periph1_axi_awvalid(xbar_axil_periph1_axi_awvalid),
        .axil_periph1_axi_awready(xbar_axil_periph1_axi_awready),
        .axil_periph1_axi_wdata(xbar_axil_periph1_axi_wdata),
        .axil_periph1_axi_wstrb(xbar_axil_periph1_axi_wstrb),
        .axil_periph1_axi_wlast(xbar_axil_periph1_axi_wlast),
        .axil_periph1_axi_wuser(xbar_axil_periph1_axi_wuser),
        .axil_periph1_axi_wvalid(xbar_axil_periph1_axi_wvalid),
        .axil_periph1_axi_wready(xbar_axil_periph1_axi_wready),
        .axil_periph1_axi_bid(xbar_axil_periph1_axi_bid),
        .axil_periph1_axi_bresp(xbar_axil_periph1_axi_bresp),
        .axil_periph1_axi_buser(xbar_axil_periph1_axi_buser),
        .axil_periph1_axi_bvalid(xbar_axil_periph1_axi_bvalid),
        .axil_periph1_axi_bready(xbar_axil_periph1_axi_bready),
        .axil_periph1_axi_arid(xbar_axil_periph1_axi_arid),
        .axil_periph1_axi_araddr(xbar_axil_periph1_axi_araddr),
        .axil_periph1_axi_arlen(xbar_axil_periph1_axi_arlen),
        .axil_periph1_axi_arsize(xbar_axil_periph1_axi_arsize),
        .axil_periph1_axi_arburst(xbar_axil_periph1_axi_arburst),
        .axil_periph1_axi_arlock(xbar_axil_periph1_axi_arlock),
        .axil_periph1_axi_arcache(xbar_axil_periph1_axi_arcache),
        .axil_periph1_axi_arprot(xbar_axil_periph1_axi_arprot),
        .axil_periph1_axi_arqos(xbar_axil_periph1_axi_arqos),
        .axil_periph1_axi_arregion(xbar_axil_periph1_axi_arregion),
        .axil_periph1_axi_aruser(xbar_axil_periph1_axi_aruser),
        .axil_periph1_axi_arvalid(xbar_axil_periph1_axi_arvalid),
        .axil_periph1_axi_arready(xbar_axil_periph1_axi_arready),
        .axil_periph1_axi_rid(xbar_axil_periph1_axi_rid),
        .axil_periph1_axi_rdata(xbar_axil_periph1_axi_rdata),
        .axil_periph1_axi_rresp(xbar_axil_periph1_axi_rresp),
        .axil_periph1_axi_rlast(xbar_axil_periph1_axi_rlast),
        .axil_periph1_axi_ruser(xbar_axil_periph1_axi_ruser),
        .axil_periph1_axi_rvalid(xbar_axil_periph1_axi_rvalid),
        .axil_periph1_axi_rready(xbar_axil_periph1_axi_rready),
        .axil_periph1_axi_bridge_id_aw(axil_periph1_axi_bridge_id_aw),
        .axil_periph1_axi_bid_bridge_id(axil_periph1_axi_bid_bridge_id),
        .axil_periph1_axi_bid_valid(axil_periph1_axi_bid_valid),

        .axil_periph1_axi_bridge_id_ar(axil_periph1_axi_bridge_id_ar),
        .axil_periph1_axi_rid_bridge_id(axil_periph1_axi_rid_bridge_id),
        .axil_periph1_axi_rid_valid(axil_periph1_axi_rid_valid),

        // Slave 4: apb_periph0
        .apb_periph0_axi_awid(xbar_apb_periph0_axi_awid),
        .apb_periph0_axi_awaddr(xbar_apb_periph0_axi_awaddr),
        .apb_periph0_axi_awlen(xbar_apb_periph0_axi_awlen),
        .apb_periph0_axi_awsize(xbar_apb_periph0_axi_awsize),
        .apb_periph0_axi_awburst(xbar_apb_periph0_axi_awburst),
        .apb_periph0_axi_awlock(xbar_apb_periph0_axi_awlock),
        .apb_periph0_axi_awcache(xbar_apb_periph0_axi_awcache),
        .apb_periph0_axi_awprot(xbar_apb_periph0_axi_awprot),
        .apb_periph0_axi_awqos(xbar_apb_periph0_axi_awqos),
        .apb_periph0_axi_awregion(xbar_apb_periph0_axi_awregion),
        .apb_periph0_axi_awuser(xbar_apb_periph0_axi_awuser),
        .apb_periph0_axi_awvalid(xbar_apb_periph0_axi_awvalid),
        .apb_periph0_axi_awready(xbar_apb_periph0_axi_awready),
        .apb_periph0_axi_wdata(xbar_apb_periph0_axi_wdata),
        .apb_periph0_axi_wstrb(xbar_apb_periph0_axi_wstrb),
        .apb_periph0_axi_wlast(xbar_apb_periph0_axi_wlast),
        .apb_periph0_axi_wuser(xbar_apb_periph0_axi_wuser),
        .apb_periph0_axi_wvalid(xbar_apb_periph0_axi_wvalid),
        .apb_periph0_axi_wready(xbar_apb_periph0_axi_wready),
        .apb_periph0_axi_bid(xbar_apb_periph0_axi_bid),
        .apb_periph0_axi_bresp(xbar_apb_periph0_axi_bresp),
        .apb_periph0_axi_buser(xbar_apb_periph0_axi_buser),
        .apb_periph0_axi_bvalid(xbar_apb_periph0_axi_bvalid),
        .apb_periph0_axi_bready(xbar_apb_periph0_axi_bready),
        .apb_periph0_axi_arid(xbar_apb_periph0_axi_arid),
        .apb_periph0_axi_araddr(xbar_apb_periph0_axi_araddr),
        .apb_periph0_axi_arlen(xbar_apb_periph0_axi_arlen),
        .apb_periph0_axi_arsize(xbar_apb_periph0_axi_arsize),
        .apb_periph0_axi_arburst(xbar_apb_periph0_axi_arburst),
        .apb_periph0_axi_arlock(xbar_apb_periph0_axi_arlock),
        .apb_periph0_axi_arcache(xbar_apb_periph0_axi_arcache),
        .apb_periph0_axi_arprot(xbar_apb_periph0_axi_arprot),
        .apb_periph0_axi_arqos(xbar_apb_periph0_axi_arqos),
        .apb_periph0_axi_arregion(xbar_apb_periph0_axi_arregion),
        .apb_periph0_axi_aruser(xbar_apb_periph0_axi_aruser),
        .apb_periph0_axi_arvalid(xbar_apb_periph0_axi_arvalid),
        .apb_periph0_axi_arready(xbar_apb_periph0_axi_arready),
        .apb_periph0_axi_rid(xbar_apb_periph0_axi_rid),
        .apb_periph0_axi_rdata(xbar_apb_periph0_axi_rdata),
        .apb_periph0_axi_rresp(xbar_apb_periph0_axi_rresp),
        .apb_periph0_axi_rlast(xbar_apb_periph0_axi_rlast),
        .apb_periph0_axi_ruser(xbar_apb_periph0_axi_ruser),
        .apb_periph0_axi_rvalid(xbar_apb_periph0_axi_rvalid),
        .apb_periph0_axi_rready(xbar_apb_periph0_axi_rready),
        .apb_periph0_axi_bridge_id_aw(apb_periph0_axi_bridge_id_aw),
        .apb_periph0_axi_bid_bridge_id(apb_periph0_axi_bid_bridge_id),
        .apb_periph0_axi_bid_valid(apb_periph0_axi_bid_valid),

        .apb_periph0_axi_bridge_id_ar(apb_periph0_axi_bridge_id_ar),
        .apb_periph0_axi_rid_bridge_id(apb_periph0_axi_rid_bridge_id),
        .apb_periph0_axi_rid_valid(apb_periph0_axi_rid_valid)
    );

    // ================================================================
    // Slave Adapter Instantiations
    // AXI4 slaves: timing-isolation wrapper (axi4_master_wr/rd)
    // APB / AXIL slaves: protocol-converter wrapper
    // All adapters carry bridge_id tracking FIFOs.
    // ================================================================

    // ddr0 adapter (AXI4, crossbar → external slave)
    ddr0_adapter u_ddr0_adapter (
        .aclk(aclk),
        .aresetn(aresetn),

        // Crossbar interface (xbar_ddr0_axi_*)
        .xbar_ddr0_axi_awid(xbar_ddr0_axi_awid),
        .xbar_ddr0_axi_awaddr(xbar_ddr0_axi_awaddr),
        .xbar_ddr0_axi_awlen(xbar_ddr0_axi_awlen),
        .xbar_ddr0_axi_awsize(xbar_ddr0_axi_awsize),
        .xbar_ddr0_axi_awburst(xbar_ddr0_axi_awburst),
        .xbar_ddr0_axi_awlock(xbar_ddr0_axi_awlock),
        .xbar_ddr0_axi_awcache(xbar_ddr0_axi_awcache),
        .xbar_ddr0_axi_awprot(xbar_ddr0_axi_awprot),
        .xbar_ddr0_axi_awqos(xbar_ddr0_axi_awqos),
        .xbar_ddr0_axi_awregion(xbar_ddr0_axi_awregion),
        .xbar_ddr0_axi_awuser(xbar_ddr0_axi_awuser),
        .xbar_ddr0_axi_awvalid(xbar_ddr0_axi_awvalid),
        .xbar_ddr0_axi_awready(xbar_ddr0_axi_awready),
        .xbar_ddr0_axi_wdata(xbar_ddr0_axi_wdata),
        .xbar_ddr0_axi_wstrb(xbar_ddr0_axi_wstrb),
        .xbar_ddr0_axi_wlast(xbar_ddr0_axi_wlast),
        .xbar_ddr0_axi_wuser(xbar_ddr0_axi_wuser),
        .xbar_ddr0_axi_wvalid(xbar_ddr0_axi_wvalid),
        .xbar_ddr0_axi_wready(xbar_ddr0_axi_wready),
        .xbar_ddr0_axi_bid(xbar_ddr0_axi_bid),
        .xbar_ddr0_axi_bresp(xbar_ddr0_axi_bresp),
        .xbar_ddr0_axi_buser(xbar_ddr0_axi_buser),
        .xbar_ddr0_axi_bvalid(xbar_ddr0_axi_bvalid),
        .xbar_ddr0_axi_bready(xbar_ddr0_axi_bready),
        .xbar_ddr0_axi_arid(xbar_ddr0_axi_arid),
        .xbar_ddr0_axi_araddr(xbar_ddr0_axi_araddr),
        .xbar_ddr0_axi_arlen(xbar_ddr0_axi_arlen),
        .xbar_ddr0_axi_arsize(xbar_ddr0_axi_arsize),
        .xbar_ddr0_axi_arburst(xbar_ddr0_axi_arburst),
        .xbar_ddr0_axi_arlock(xbar_ddr0_axi_arlock),
        .xbar_ddr0_axi_arcache(xbar_ddr0_axi_arcache),
        .xbar_ddr0_axi_arprot(xbar_ddr0_axi_arprot),
        .xbar_ddr0_axi_arqos(xbar_ddr0_axi_arqos),
        .xbar_ddr0_axi_arregion(xbar_ddr0_axi_arregion),
        .xbar_ddr0_axi_aruser(xbar_ddr0_axi_aruser),
        .xbar_ddr0_axi_arvalid(xbar_ddr0_axi_arvalid),
        .xbar_ddr0_axi_arready(xbar_ddr0_axi_arready),
        .xbar_ddr0_axi_rid(xbar_ddr0_axi_rid),
        .xbar_ddr0_axi_rdata(xbar_ddr0_axi_rdata),
        .xbar_ddr0_axi_rresp(xbar_ddr0_axi_rresp),
        .xbar_ddr0_axi_rlast(xbar_ddr0_axi_rlast),
        .xbar_ddr0_axi_ruser(xbar_ddr0_axi_ruser),
        .xbar_ddr0_axi_rvalid(xbar_ddr0_axi_rvalid),
        .xbar_ddr0_axi_rready(xbar_ddr0_axi_rready),

        // External AXI4 interface (ddr0_s_axi_*)
        .ddr0_s_axi_awid(ddr0_s_axi_awid),
        .ddr0_s_axi_awaddr(ddr0_s_axi_awaddr),
        .ddr0_s_axi_awlen(ddr0_s_axi_awlen),
        .ddr0_s_axi_awsize(ddr0_s_axi_awsize),
        .ddr0_s_axi_awburst(ddr0_s_axi_awburst),
        .ddr0_s_axi_awlock(ddr0_s_axi_awlock),
        .ddr0_s_axi_awcache(ddr0_s_axi_awcache),
        .ddr0_s_axi_awprot(ddr0_s_axi_awprot),
        .ddr0_s_axi_awqos(ddr0_s_axi_awqos),
        .ddr0_s_axi_awregion(ddr0_s_axi_awregion),
        .ddr0_s_axi_awuser(ddr0_s_axi_awuser),
        .ddr0_s_axi_awvalid(ddr0_s_axi_awvalid),
        .ddr0_s_axi_awready(ddr0_s_axi_awready),
        .ddr0_s_axi_wdata(ddr0_s_axi_wdata),
        .ddr0_s_axi_wstrb(ddr0_s_axi_wstrb),
        .ddr0_s_axi_wlast(ddr0_s_axi_wlast),
        .ddr0_s_axi_wuser(ddr0_s_axi_wuser),
        .ddr0_s_axi_wvalid(ddr0_s_axi_wvalid),
        .ddr0_s_axi_wready(ddr0_s_axi_wready),
        .ddr0_s_axi_bid(ddr0_s_axi_bid),
        .ddr0_s_axi_bresp(ddr0_s_axi_bresp),
        .ddr0_s_axi_buser(ddr0_s_axi_buser),
        .ddr0_s_axi_bvalid(ddr0_s_axi_bvalid),
        .ddr0_s_axi_bready(ddr0_s_axi_bready),
        .ddr0_s_axi_arid(ddr0_s_axi_arid),
        .ddr0_s_axi_araddr(ddr0_s_axi_araddr),
        .ddr0_s_axi_arlen(ddr0_s_axi_arlen),
        .ddr0_s_axi_arsize(ddr0_s_axi_arsize),
        .ddr0_s_axi_arburst(ddr0_s_axi_arburst),
        .ddr0_s_axi_arlock(ddr0_s_axi_arlock),
        .ddr0_s_axi_arcache(ddr0_s_axi_arcache),
        .ddr0_s_axi_arprot(ddr0_s_axi_arprot),
        .ddr0_s_axi_arqos(ddr0_s_axi_arqos),
        .ddr0_s_axi_arregion(ddr0_s_axi_arregion),
        .ddr0_s_axi_aruser(ddr0_s_axi_aruser),
        .ddr0_s_axi_arvalid(ddr0_s_axi_arvalid),
        .ddr0_s_axi_arready(ddr0_s_axi_arready),
        .ddr0_s_axi_rid(ddr0_s_axi_rid),
        .ddr0_s_axi_rdata(ddr0_s_axi_rdata),
        .ddr0_s_axi_rresp(ddr0_s_axi_rresp),
        .ddr0_s_axi_rlast(ddr0_s_axi_rlast),
        .ddr0_s_axi_ruser(ddr0_s_axi_ruser),
        .ddr0_s_axi_rvalid(ddr0_s_axi_rvalid),
        .ddr0_s_axi_rready(ddr0_s_axi_rready),

        // Bridge ID tracking
        .xbar_bridge_id_aw(ddr0_axi_bridge_id_aw),
        .bid_bridge_id(ddr0_axi_bid_bridge_id),
        .bid_valid(ddr0_axi_bid_valid),
        .xbar_bridge_id_ar(ddr0_axi_bridge_id_ar),
        .rid_bridge_id(ddr0_axi_rid_bridge_id),
        .rid_valid(ddr0_axi_rid_valid)
    );

    // sram adapter (AXI4, crossbar → external slave)
    sram_adapter u_sram_adapter (
        .aclk(aclk),
        .aresetn(aresetn),

        // Crossbar interface (xbar_sram_axi_*)
        .xbar_sram_axi_awid(xbar_sram_axi_awid),
        .xbar_sram_axi_awaddr(xbar_sram_axi_awaddr),
        .xbar_sram_axi_awlen(xbar_sram_axi_awlen),
        .xbar_sram_axi_awsize(xbar_sram_axi_awsize),
        .xbar_sram_axi_awburst(xbar_sram_axi_awburst),
        .xbar_sram_axi_awlock(xbar_sram_axi_awlock),
        .xbar_sram_axi_awcache(xbar_sram_axi_awcache),
        .xbar_sram_axi_awprot(xbar_sram_axi_awprot),
        .xbar_sram_axi_awqos(xbar_sram_axi_awqos),
        .xbar_sram_axi_awregion(xbar_sram_axi_awregion),
        .xbar_sram_axi_awuser(xbar_sram_axi_awuser),
        .xbar_sram_axi_awvalid(xbar_sram_axi_awvalid),
        .xbar_sram_axi_awready(xbar_sram_axi_awready),
        .xbar_sram_axi_wdata(xbar_sram_axi_wdata),
        .xbar_sram_axi_wstrb(xbar_sram_axi_wstrb),
        .xbar_sram_axi_wlast(xbar_sram_axi_wlast),
        .xbar_sram_axi_wuser(xbar_sram_axi_wuser),
        .xbar_sram_axi_wvalid(xbar_sram_axi_wvalid),
        .xbar_sram_axi_wready(xbar_sram_axi_wready),
        .xbar_sram_axi_bid(xbar_sram_axi_bid),
        .xbar_sram_axi_bresp(xbar_sram_axi_bresp),
        .xbar_sram_axi_buser(xbar_sram_axi_buser),
        .xbar_sram_axi_bvalid(xbar_sram_axi_bvalid),
        .xbar_sram_axi_bready(xbar_sram_axi_bready),
        .xbar_sram_axi_arid(xbar_sram_axi_arid),
        .xbar_sram_axi_araddr(xbar_sram_axi_araddr),
        .xbar_sram_axi_arlen(xbar_sram_axi_arlen),
        .xbar_sram_axi_arsize(xbar_sram_axi_arsize),
        .xbar_sram_axi_arburst(xbar_sram_axi_arburst),
        .xbar_sram_axi_arlock(xbar_sram_axi_arlock),
        .xbar_sram_axi_arcache(xbar_sram_axi_arcache),
        .xbar_sram_axi_arprot(xbar_sram_axi_arprot),
        .xbar_sram_axi_arqos(xbar_sram_axi_arqos),
        .xbar_sram_axi_arregion(xbar_sram_axi_arregion),
        .xbar_sram_axi_aruser(xbar_sram_axi_aruser),
        .xbar_sram_axi_arvalid(xbar_sram_axi_arvalid),
        .xbar_sram_axi_arready(xbar_sram_axi_arready),
        .xbar_sram_axi_rid(xbar_sram_axi_rid),
        .xbar_sram_axi_rdata(xbar_sram_axi_rdata),
        .xbar_sram_axi_rresp(xbar_sram_axi_rresp),
        .xbar_sram_axi_rlast(xbar_sram_axi_rlast),
        .xbar_sram_axi_ruser(xbar_sram_axi_ruser),
        .xbar_sram_axi_rvalid(xbar_sram_axi_rvalid),
        .xbar_sram_axi_rready(xbar_sram_axi_rready),

        // External AXI4 interface (sram_s_axi_*)
        .sram_s_axi_awid(sram_s_axi_awid),
        .sram_s_axi_awaddr(sram_s_axi_awaddr),
        .sram_s_axi_awlen(sram_s_axi_awlen),
        .sram_s_axi_awsize(sram_s_axi_awsize),
        .sram_s_axi_awburst(sram_s_axi_awburst),
        .sram_s_axi_awlock(sram_s_axi_awlock),
        .sram_s_axi_awcache(sram_s_axi_awcache),
        .sram_s_axi_awprot(sram_s_axi_awprot),
        .sram_s_axi_awqos(sram_s_axi_awqos),
        .sram_s_axi_awregion(sram_s_axi_awregion),
        .sram_s_axi_awuser(sram_s_axi_awuser),
        .sram_s_axi_awvalid(sram_s_axi_awvalid),
        .sram_s_axi_awready(sram_s_axi_awready),
        .sram_s_axi_wdata(sram_s_axi_wdata),
        .sram_s_axi_wstrb(sram_s_axi_wstrb),
        .sram_s_axi_wlast(sram_s_axi_wlast),
        .sram_s_axi_wuser(sram_s_axi_wuser),
        .sram_s_axi_wvalid(sram_s_axi_wvalid),
        .sram_s_axi_wready(sram_s_axi_wready),
        .sram_s_axi_bid(sram_s_axi_bid),
        .sram_s_axi_bresp(sram_s_axi_bresp),
        .sram_s_axi_buser(sram_s_axi_buser),
        .sram_s_axi_bvalid(sram_s_axi_bvalid),
        .sram_s_axi_bready(sram_s_axi_bready),
        .sram_s_axi_arid(sram_s_axi_arid),
        .sram_s_axi_araddr(sram_s_axi_araddr),
        .sram_s_axi_arlen(sram_s_axi_arlen),
        .sram_s_axi_arsize(sram_s_axi_arsize),
        .sram_s_axi_arburst(sram_s_axi_arburst),
        .sram_s_axi_arlock(sram_s_axi_arlock),
        .sram_s_axi_arcache(sram_s_axi_arcache),
        .sram_s_axi_arprot(sram_s_axi_arprot),
        .sram_s_axi_arqos(sram_s_axi_arqos),
        .sram_s_axi_arregion(sram_s_axi_arregion),
        .sram_s_axi_aruser(sram_s_axi_aruser),
        .sram_s_axi_arvalid(sram_s_axi_arvalid),
        .sram_s_axi_arready(sram_s_axi_arready),
        .sram_s_axi_rid(sram_s_axi_rid),
        .sram_s_axi_rdata(sram_s_axi_rdata),
        .sram_s_axi_rresp(sram_s_axi_rresp),
        .sram_s_axi_rlast(sram_s_axi_rlast),
        .sram_s_axi_ruser(sram_s_axi_ruser),
        .sram_s_axi_rvalid(sram_s_axi_rvalid),
        .sram_s_axi_rready(sram_s_axi_rready),

        // Bridge ID tracking
        .xbar_bridge_id_aw(sram_axi_bridge_id_aw),
        .bid_bridge_id(sram_axi_bid_bridge_id),
        .bid_valid(sram_axi_bid_valid),
        .xbar_bridge_id_ar(sram_axi_bridge_id_ar),
        .rid_bridge_id(sram_axi_rid_bridge_id),
        .rid_valid(sram_axi_rid_valid)
    );

    // axil_periph0 adapter (AXIL, crossbar → external slave)
    axil_periph0_adapter u_axil_periph0_adapter (
        .aclk(aclk),
        .aresetn(aresetn),

        // Crossbar interface (xbar_axil_periph0_axi_*)
        .xbar_axil_periph0_axi_awid(xbar_axil_periph0_axi_awid),
        .xbar_axil_periph0_axi_awaddr(xbar_axil_periph0_axi_awaddr),
        .xbar_axil_periph0_axi_awlen(xbar_axil_periph0_axi_awlen),
        .xbar_axil_periph0_axi_awsize(xbar_axil_periph0_axi_awsize),
        .xbar_axil_periph0_axi_awburst(xbar_axil_periph0_axi_awburst),
        .xbar_axil_periph0_axi_awlock(xbar_axil_periph0_axi_awlock),
        .xbar_axil_periph0_axi_awcache(xbar_axil_periph0_axi_awcache),
        .xbar_axil_periph0_axi_awprot(xbar_axil_periph0_axi_awprot),
        .xbar_axil_periph0_axi_awqos(xbar_axil_periph0_axi_awqos),
        .xbar_axil_periph0_axi_awregion(xbar_axil_periph0_axi_awregion),
        .xbar_axil_periph0_axi_awuser(xbar_axil_periph0_axi_awuser),
        .xbar_axil_periph0_axi_awvalid(xbar_axil_periph0_axi_awvalid),
        .xbar_axil_periph0_axi_awready(xbar_axil_periph0_axi_awready),
        .xbar_axil_periph0_axi_wdata(xbar_axil_periph0_axi_wdata),
        .xbar_axil_periph0_axi_wstrb(xbar_axil_periph0_axi_wstrb),
        .xbar_axil_periph0_axi_wlast(xbar_axil_periph0_axi_wlast),
        .xbar_axil_periph0_axi_wuser(xbar_axil_periph0_axi_wuser),
        .xbar_axil_periph0_axi_wvalid(xbar_axil_periph0_axi_wvalid),
        .xbar_axil_periph0_axi_wready(xbar_axil_periph0_axi_wready),
        .xbar_axil_periph0_axi_bid(xbar_axil_periph0_axi_bid),
        .xbar_axil_periph0_axi_bresp(xbar_axil_periph0_axi_bresp),
        .xbar_axil_periph0_axi_buser(xbar_axil_periph0_axi_buser),
        .xbar_axil_periph0_axi_bvalid(xbar_axil_periph0_axi_bvalid),
        .xbar_axil_periph0_axi_bready(xbar_axil_periph0_axi_bready),
        .xbar_axil_periph0_axi_arid(xbar_axil_periph0_axi_arid),
        .xbar_axil_periph0_axi_araddr(xbar_axil_periph0_axi_araddr),
        .xbar_axil_periph0_axi_arlen(xbar_axil_periph0_axi_arlen),
        .xbar_axil_periph0_axi_arsize(xbar_axil_periph0_axi_arsize),
        .xbar_axil_periph0_axi_arburst(xbar_axil_periph0_axi_arburst),
        .xbar_axil_periph0_axi_arlock(xbar_axil_periph0_axi_arlock),
        .xbar_axil_periph0_axi_arcache(xbar_axil_periph0_axi_arcache),
        .xbar_axil_periph0_axi_arprot(xbar_axil_periph0_axi_arprot),
        .xbar_axil_periph0_axi_arqos(xbar_axil_periph0_axi_arqos),
        .xbar_axil_periph0_axi_arregion(xbar_axil_periph0_axi_arregion),
        .xbar_axil_periph0_axi_aruser(xbar_axil_periph0_axi_aruser),
        .xbar_axil_periph0_axi_arvalid(xbar_axil_periph0_axi_arvalid),
        .xbar_axil_periph0_axi_arready(xbar_axil_periph0_axi_arready),
        .xbar_axil_periph0_axi_rid(xbar_axil_periph0_axi_rid),
        .xbar_axil_periph0_axi_rdata(xbar_axil_periph0_axi_rdata),
        .xbar_axil_periph0_axi_rresp(xbar_axil_periph0_axi_rresp),
        .xbar_axil_periph0_axi_rlast(xbar_axil_periph0_axi_rlast),
        .xbar_axil_periph0_axi_ruser(xbar_axil_periph0_axi_ruser),
        .xbar_axil_periph0_axi_rvalid(xbar_axil_periph0_axi_rvalid),
        .xbar_axil_periph0_axi_rready(xbar_axil_periph0_axi_rready),

        // External AXI4-Lite interface (axil_periph0_*)
        .axil_periph0_awaddr(axil_periph0_awaddr),
        .axil_periph0_awprot(axil_periph0_awprot),
        .axil_periph0_awvalid(axil_periph0_awvalid),
        .axil_periph0_awready(axil_periph0_awready),
        .axil_periph0_wdata(axil_periph0_wdata),
        .axil_periph0_wstrb(axil_periph0_wstrb),
        .axil_periph0_wvalid(axil_periph0_wvalid),
        .axil_periph0_wready(axil_periph0_wready),
        .axil_periph0_bresp(axil_periph0_bresp),
        .axil_periph0_bvalid(axil_periph0_bvalid),
        .axil_periph0_bready(axil_periph0_bready),
        .axil_periph0_araddr(axil_periph0_araddr),
        .axil_periph0_arprot(axil_periph0_arprot),
        .axil_periph0_arvalid(axil_periph0_arvalid),
        .axil_periph0_arready(axil_periph0_arready),
        .axil_periph0_rdata(axil_periph0_rdata),
        .axil_periph0_rresp(axil_periph0_rresp),
        .axil_periph0_rvalid(axil_periph0_rvalid),
        .axil_periph0_rready(axil_periph0_rready),

        // Bridge ID tracking
        .xbar_bridge_id_aw(axil_periph0_axi_bridge_id_aw),
        .bid_bridge_id(axil_periph0_axi_bid_bridge_id),
        .bid_valid(axil_periph0_axi_bid_valid),
        .xbar_bridge_id_ar(axil_periph0_axi_bridge_id_ar),
        .rid_bridge_id(axil_periph0_axi_rid_bridge_id),
        .rid_valid(axil_periph0_axi_rid_valid)
    );

    // axil_periph1 adapter (AXIL, crossbar → external slave)
    axil_periph1_adapter u_axil_periph1_adapter (
        .aclk(aclk),
        .aresetn(aresetn),

        // Crossbar interface (xbar_axil_periph1_axi_*)
        .xbar_axil_periph1_axi_awid(xbar_axil_periph1_axi_awid),
        .xbar_axil_periph1_axi_awaddr(xbar_axil_periph1_axi_awaddr),
        .xbar_axil_periph1_axi_awlen(xbar_axil_periph1_axi_awlen),
        .xbar_axil_periph1_axi_awsize(xbar_axil_periph1_axi_awsize),
        .xbar_axil_periph1_axi_awburst(xbar_axil_periph1_axi_awburst),
        .xbar_axil_periph1_axi_awlock(xbar_axil_periph1_axi_awlock),
        .xbar_axil_periph1_axi_awcache(xbar_axil_periph1_axi_awcache),
        .xbar_axil_periph1_axi_awprot(xbar_axil_periph1_axi_awprot),
        .xbar_axil_periph1_axi_awqos(xbar_axil_periph1_axi_awqos),
        .xbar_axil_periph1_axi_awregion(xbar_axil_periph1_axi_awregion),
        .xbar_axil_periph1_axi_awuser(xbar_axil_periph1_axi_awuser),
        .xbar_axil_periph1_axi_awvalid(xbar_axil_periph1_axi_awvalid),
        .xbar_axil_periph1_axi_awready(xbar_axil_periph1_axi_awready),
        .xbar_axil_periph1_axi_wdata(xbar_axil_periph1_axi_wdata),
        .xbar_axil_periph1_axi_wstrb(xbar_axil_periph1_axi_wstrb),
        .xbar_axil_periph1_axi_wlast(xbar_axil_periph1_axi_wlast),
        .xbar_axil_periph1_axi_wuser(xbar_axil_periph1_axi_wuser),
        .xbar_axil_periph1_axi_wvalid(xbar_axil_periph1_axi_wvalid),
        .xbar_axil_periph1_axi_wready(xbar_axil_periph1_axi_wready),
        .xbar_axil_periph1_axi_bid(xbar_axil_periph1_axi_bid),
        .xbar_axil_periph1_axi_bresp(xbar_axil_periph1_axi_bresp),
        .xbar_axil_periph1_axi_buser(xbar_axil_periph1_axi_buser),
        .xbar_axil_periph1_axi_bvalid(xbar_axil_periph1_axi_bvalid),
        .xbar_axil_periph1_axi_bready(xbar_axil_periph1_axi_bready),
        .xbar_axil_periph1_axi_arid(xbar_axil_periph1_axi_arid),
        .xbar_axil_periph1_axi_araddr(xbar_axil_periph1_axi_araddr),
        .xbar_axil_periph1_axi_arlen(xbar_axil_periph1_axi_arlen),
        .xbar_axil_periph1_axi_arsize(xbar_axil_periph1_axi_arsize),
        .xbar_axil_periph1_axi_arburst(xbar_axil_periph1_axi_arburst),
        .xbar_axil_periph1_axi_arlock(xbar_axil_periph1_axi_arlock),
        .xbar_axil_periph1_axi_arcache(xbar_axil_periph1_axi_arcache),
        .xbar_axil_periph1_axi_arprot(xbar_axil_periph1_axi_arprot),
        .xbar_axil_periph1_axi_arqos(xbar_axil_periph1_axi_arqos),
        .xbar_axil_periph1_axi_arregion(xbar_axil_periph1_axi_arregion),
        .xbar_axil_periph1_axi_aruser(xbar_axil_periph1_axi_aruser),
        .xbar_axil_periph1_axi_arvalid(xbar_axil_periph1_axi_arvalid),
        .xbar_axil_periph1_axi_arready(xbar_axil_periph1_axi_arready),
        .xbar_axil_periph1_axi_rid(xbar_axil_periph1_axi_rid),
        .xbar_axil_periph1_axi_rdata(xbar_axil_periph1_axi_rdata),
        .xbar_axil_periph1_axi_rresp(xbar_axil_periph1_axi_rresp),
        .xbar_axil_periph1_axi_rlast(xbar_axil_periph1_axi_rlast),
        .xbar_axil_periph1_axi_ruser(xbar_axil_periph1_axi_ruser),
        .xbar_axil_periph1_axi_rvalid(xbar_axil_periph1_axi_rvalid),
        .xbar_axil_periph1_axi_rready(xbar_axil_periph1_axi_rready),

        // External AXI4-Lite interface (axil_periph1_*)
        .axil_periph1_awaddr(axil_periph1_awaddr),
        .axil_periph1_awprot(axil_periph1_awprot),
        .axil_periph1_awvalid(axil_periph1_awvalid),
        .axil_periph1_awready(axil_periph1_awready),
        .axil_periph1_wdata(axil_periph1_wdata),
        .axil_periph1_wstrb(axil_periph1_wstrb),
        .axil_periph1_wvalid(axil_periph1_wvalid),
        .axil_periph1_wready(axil_periph1_wready),
        .axil_periph1_bresp(axil_periph1_bresp),
        .axil_periph1_bvalid(axil_periph1_bvalid),
        .axil_periph1_bready(axil_periph1_bready),
        .axil_periph1_araddr(axil_periph1_araddr),
        .axil_periph1_arprot(axil_periph1_arprot),
        .axil_periph1_arvalid(axil_periph1_arvalid),
        .axil_periph1_arready(axil_periph1_arready),
        .axil_periph1_rdata(axil_periph1_rdata),
        .axil_periph1_rresp(axil_periph1_rresp),
        .axil_periph1_rvalid(axil_periph1_rvalid),
        .axil_periph1_rready(axil_periph1_rready),

        // Bridge ID tracking
        .xbar_bridge_id_aw(axil_periph1_axi_bridge_id_aw),
        .bid_bridge_id(axil_periph1_axi_bid_bridge_id),
        .bid_valid(axil_periph1_axi_bid_valid),
        .xbar_bridge_id_ar(axil_periph1_axi_bridge_id_ar),
        .rid_bridge_id(axil_periph1_axi_rid_bridge_id),
        .rid_valid(axil_periph1_axi_rid_valid)
    );

    // apb_periph0 adapter (APB, crossbar → external slave)
    apb_periph0_adapter u_apb_periph0_adapter (
        .aclk(aclk),
        .aresetn(aresetn),

        // Crossbar interface (xbar_apb_periph0_axi_*)
        .xbar_apb_periph0_axi_awid(xbar_apb_periph0_axi_awid),
        .xbar_apb_periph0_axi_awaddr(xbar_apb_periph0_axi_awaddr),
        .xbar_apb_periph0_axi_awlen(xbar_apb_periph0_axi_awlen),
        .xbar_apb_periph0_axi_awsize(xbar_apb_periph0_axi_awsize),
        .xbar_apb_periph0_axi_awburst(xbar_apb_periph0_axi_awburst),
        .xbar_apb_periph0_axi_awlock(xbar_apb_periph0_axi_awlock),
        .xbar_apb_periph0_axi_awcache(xbar_apb_periph0_axi_awcache),
        .xbar_apb_periph0_axi_awprot(xbar_apb_periph0_axi_awprot),
        .xbar_apb_periph0_axi_awqos(xbar_apb_periph0_axi_awqos),
        .xbar_apb_periph0_axi_awregion(xbar_apb_periph0_axi_awregion),
        .xbar_apb_periph0_axi_awuser(xbar_apb_periph0_axi_awuser),
        .xbar_apb_periph0_axi_awvalid(xbar_apb_periph0_axi_awvalid),
        .xbar_apb_periph0_axi_awready(xbar_apb_periph0_axi_awready),
        .xbar_apb_periph0_axi_wdata(xbar_apb_periph0_axi_wdata),
        .xbar_apb_periph0_axi_wstrb(xbar_apb_periph0_axi_wstrb),
        .xbar_apb_periph0_axi_wlast(xbar_apb_periph0_axi_wlast),
        .xbar_apb_periph0_axi_wuser(xbar_apb_periph0_axi_wuser),
        .xbar_apb_periph0_axi_wvalid(xbar_apb_periph0_axi_wvalid),
        .xbar_apb_periph0_axi_wready(xbar_apb_periph0_axi_wready),
        .xbar_apb_periph0_axi_bid(xbar_apb_periph0_axi_bid),
        .xbar_apb_periph0_axi_bresp(xbar_apb_periph0_axi_bresp),
        .xbar_apb_periph0_axi_buser(xbar_apb_periph0_axi_buser),
        .xbar_apb_periph0_axi_bvalid(xbar_apb_periph0_axi_bvalid),
        .xbar_apb_periph0_axi_bready(xbar_apb_periph0_axi_bready),
        .xbar_apb_periph0_axi_arid(xbar_apb_periph0_axi_arid),
        .xbar_apb_periph0_axi_araddr(xbar_apb_periph0_axi_araddr),
        .xbar_apb_periph0_axi_arlen(xbar_apb_periph0_axi_arlen),
        .xbar_apb_periph0_axi_arsize(xbar_apb_periph0_axi_arsize),
        .xbar_apb_periph0_axi_arburst(xbar_apb_periph0_axi_arburst),
        .xbar_apb_periph0_axi_arlock(xbar_apb_periph0_axi_arlock),
        .xbar_apb_periph0_axi_arcache(xbar_apb_periph0_axi_arcache),
        .xbar_apb_periph0_axi_arprot(xbar_apb_periph0_axi_arprot),
        .xbar_apb_periph0_axi_arqos(xbar_apb_periph0_axi_arqos),
        .xbar_apb_periph0_axi_arregion(xbar_apb_periph0_axi_arregion),
        .xbar_apb_periph0_axi_aruser(xbar_apb_periph0_axi_aruser),
        .xbar_apb_periph0_axi_arvalid(xbar_apb_periph0_axi_arvalid),
        .xbar_apb_periph0_axi_arready(xbar_apb_periph0_axi_arready),
        .xbar_apb_periph0_axi_rid(xbar_apb_periph0_axi_rid),
        .xbar_apb_periph0_axi_rdata(xbar_apb_periph0_axi_rdata),
        .xbar_apb_periph0_axi_rresp(xbar_apb_periph0_axi_rresp),
        .xbar_apb_periph0_axi_rlast(xbar_apb_periph0_axi_rlast),
        .xbar_apb_periph0_axi_ruser(xbar_apb_periph0_axi_ruser),
        .xbar_apb_periph0_axi_rvalid(xbar_apb_periph0_axi_rvalid),
        .xbar_apb_periph0_axi_rready(xbar_apb_periph0_axi_rready),

        // External APB interface (apb_periph0_*)
        .apb_periph0_PADDR(apb_periph0_PADDR),
        .apb_periph0_PSEL(apb_periph0_PSEL),
        .apb_periph0_PENABLE(apb_periph0_PENABLE),
        .apb_periph0_PWRITE(apb_periph0_PWRITE),
        .apb_periph0_PWDATA(apb_periph0_PWDATA),
        .apb_periph0_PSTRB(apb_periph0_PSTRB),
        .apb_periph0_PPROT(apb_periph0_PPROT),
        .apb_periph0_PRDATA(apb_periph0_PRDATA),
        .apb_periph0_PSLVERR(apb_periph0_PSLVERR),
        .apb_periph0_PREADY(apb_periph0_PREADY),

        // Bridge ID tracking
        .xbar_bridge_id_aw(apb_periph0_axi_bridge_id_aw),
        .bid_bridge_id(apb_periph0_axi_bid_bridge_id),
        .bid_valid(apb_periph0_axi_bid_valid),
        .xbar_bridge_id_ar(apb_periph0_axi_bridge_id_ar),
        .rid_bridge_id(apb_periph0_axi_rid_bridge_id),
        .rid_valid(apb_periph0_axi_rid_valid)
    );

endmodule : bridge_b_axi4_axil_3x5
